# pylint: disable=missing-module-docstring,missing-class-docstring,missing-function-docstring
# Generated by Django 5.0.6 on 2024-06-14 19:59

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.snippets.blocks
from django.db import migrations, models

import smarter.apps.cms.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0093_uploadedfile"),
    ]

    operations = [
        migrations.CreateModel(
            name="RawHtmlPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField([("html", wagtail.blocks.RawHTMLBlock())], blank=True, null=True),
                ),
                (
                    "sidebar",
                    wagtail.fields.StreamField(
                        [
                            (
                                "html_block",
                                wagtail.snippets.blocks.SnippetChooserBlock(smarter.apps.cms.models.RawHtmlSnippet),
                            )
                        ],
                        blank=True,
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="RawHtmlSnippet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Snippet Name")),
                ("html", models.TextField(verbose_name="HTML Content")),
            ],
        ),
    ]
