# pylint: disable=all
# Generated by Django 5.2.7 on 2026-01-25 15:29

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models

import smarter.apps.cms.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0095_groupsitepermission"),
    ]

    operations = [
        migrations.CreateModel(
            name="RawHtmlPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("html", 0)],
                        blank=True,
                        block_lookup={0: ("wagtail.blocks.RawHTMLBlock", (), {})},
                        null=True,
                    ),
                ),
                (
                    "sidebar",
                    wagtail.fields.StreamField(
                        [("html_block", 0)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.snippets.blocks.SnippetChooserBlock",
                                (smarter.apps.cms.models.RawHtmlSnippet,),
                                {},
                            )
                        },
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="RawHtmlSnippet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Snippet Name")),
                ("html", models.TextField(verbose_name="HTML Content")),
            ],
        ),
    ]
