# Generated by Django 5.0.6 on 2024-06-13 20:45

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="docspage",
            name="body",
            field=wagtail.fields.StreamField([("html", wagtail.blocks.RawHTMLBlock())], blank=True, null=True),
        ),
    ]
