# pylint: disable=unused-wildcard-import, wildcard-import, unused-import, wrong-import-position
"""
Smarter base settings module, shared by all environments. See smarter_settings
for strongly-typed, project-specific settings overrides.

notes:

- Generated by 'django-admin startproject' using Django 5.0.2.
- For more information on this file, see https://docs.djangoproject.com/en/5.0/topics/settings/
- For the full list of settings and their values, see https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import glob
import hashlib
import logging
import logging.config
import math
import os
import re
import secrets
import subprocess
import sys
import time
import urllib.parse
from pathlib import Path

from corsheaders.defaults import default_headers
from django import get_version
from django.core.cache import cache
from django.db import connections
from django.db.utils import OperationalError
from social_core.backends.linkedin import LinkedinOAuth2

from smarter.__version__ import __version__ as smarter_version
from smarter.common.conf import settings as smarter_settings
from smarter.common.const import SMARTER_PLATFORM_SUBDOMAIN
from smarter.common.helpers.aws_helpers import aws_helper

# Add proprietary settings for the project
from .smarter import *  # noqa: E402, F401, W0401


logger = logging.getLogger(__name__)


ALLOWED_HOSTS = ["*"]
"""
A list of strings representing the host/domain names that this Django site can serve.
Smarter implements its own middleware to validate host names.
See smarter.apps.chatbot.middleware.security.SmarterSecurityMiddleware.

Default: ["*"]

See: https://docs.djangoproject.com/en/stable/ref/settings/#allowed-hosts
"""

LOCAL_HOSTS = smarter_settings.local_hosts
"""
Supplemental list of local host/domain names that this Django site can serve.
This is specicific to Smarter and not officially part of Django settings.
"""

# to disable redis/celery in collectstatic
if "collectstatic" in sys.argv:
    CELERY_TASK_ALWAYS_EAGER = True

CORS_ORIGIN_ALLOW_ALL = False
"""
A boolean that determines whether to allow all origins to make cross-site HTTP requests.
Smarter defaults this to False and uses CORS_ALLOWED_ORIGIN_REGEXES to restrict allowed origins.
See smarter.lib.django.middleware.cors.SmarterCorsMiddleware.

This affects the Access-Control-Allow-Origin header in responses to cross-site requests. It
affects the behavior for smarter-chat React frontend applications making requests to the Smarter API.

Modifications to this will require comensurate changes to the CORS headers sent by
a Smarter Chat host (e.g. AWS CloudFront distribution) to avoid CORS errors in browsers.

See `React Integration <https://docs.smarter.sh/en/latest/developers/architecture/lib/react-integration.html#django-react-integration>`__
"""

CORS_ALLOW_HEADERS = list(default_headers) + [
    "x-api-key",
    "accept-encoding",
    "dnt",
    "origin",
]
"""
A list of non-standard HTTP headers that are allowed in cross-site HTTP requests. Smarter
Chat frontends pass the Smarter API key in the 'x-api-key' header.

See `React Integration <https://docs.smarter.sh/en/latest/developers/architecture/lib/react-integration.html#django-react-integration>`__
"""

CORS_ALLOW_CREDENTIALS = True
"""
A boolean that determines whether to allow cookies to be included in cross-site HTTP requests.
Smarter defaults this to True to allow session cookies to be sent by smarter-chat React frontends.

See `React Integration <https://docs.smarter.sh/en/latest/developers/architecture/lib/react-integration.html#django-react-integration>`__
"""
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https?://[\w-]+\.(\d+-\d+-\d+)\.api\.localhost:\d+$",
    r"^https?://[\w-]+\.localhost:\d+$",
    r"^https?://[\w-]\.api\.localhost:\d+$",
]
"""
A list of regular expressions representing the origins that are allowed to make cross-site HTTP requests.
Smarter uses this setting to restrict allowed origins for CORS requests from smarter-chat React frontends.

See `React Integration <https://docs.smarter.sh/en/latest/developers/architecture/lib/react-integration.html#django-react-integration>`__
"""

CORS_ALLOWED_ORIGINS = []
"""
A list of origins that are allowed to make cross-site HTTP requests. This is initialized here as an empty list
because base_aws.py and other environment-specific settings files will append to this list based on derived
settings values in smarter_settings.

See `React Integration <https://docs.smarter.sh/en/latest/developers/architecture/lib/react-integration.html#django-react-integration>`__
"""

# -------------------------------
# Cross Site Request Forgery (CSRF) settings
# -------------------------------
CSRF_COOKIE_SECURE = False
"""
A boolean that determines whether the CSRF cookie should be marked as "secure". This is set to
False in base settings but **should** be set to True in production environments. Note that
there are challenges with setting this to True if the Smarter platform is behind a load balancer or
reverse proxy that terminates SSL.

See:

- `Django reference: <https://docs.djangoproject.com/en/5.0/ref/settings/#csrf-cookie-secure>`__
- `Smarter Chat: <https://github.com/smarter-sh/smarter-chat/README.md>`__
- `React Integration <https://docs.smarter.sh/en/latest/developers/architecture/lib/react-integration.html#django-react-integration>`__
"""

CSRF_COOKIE_NAME = "csrftoken"
"""
The name of the CSRF cookie. Default is 'csrftoken'. This is a placeholder for Smarter-specific
functionality in smarter.lib.django.middleware.csrf.SmarterCsrfViewMiddleware.

See:

- https://docs.djangoproject.com/en/5.0/ref/settings/#csrf-cookie-name
- `Smarter Chat: <https://github.com/smarter-sh/smarter-chat/README.md>`__
- `React Integration <https://docs.smarter.sh/en/latest/developers/architecture/lib/react-integration.html#django-react-integration>`__
"""

CSRF_COOKIE_SAMESITE = "lax"
"""
The value for the SameSite flag on the CSRF cookie. Default is 'Lax'. Smarters needs
this to be 'Lax' to support cross-site requests from smarter-chat React frontends.

See:

- https://docs.djangoproject.com/en/5.0/ref/settings/#csrf-cookie-samesite
- `Smarter Chat: <https://github.com/smarter-sh/smarter-chat/README.md>`__
- `React Integration <https://docs.smarter.sh/en/latest/developers/architecture/lib/react-integration.html#django-react-integration>`__
"""

CSRF_COOKIE_AGE = 60 * 60 * 24
"""
The age of the CSRF cookie, in seconds. Default is 60 * 60 * 24 (1 day). This is a placeholder
for Smarter-specific functionality in smarter.lib.django.middleware.csrf.SmarterCsrfViewMiddleware.
The default value should be sufficient for most use cases, unless your use case involves
e-commerce checkouts that need a shorter CSRF token lifetime.

See:

- https://docs.djangoproject.com/en/5.0/ref/settings/#csrf-cookie-age
- `Smarter Chat: <https://github.com/smarter-sh/smarter-chat/README.md>`__
- `React Integration <https://docs.smarter.sh/en/latest/developers/architecture/lib/react-integration.html#django-react-integration>`__
"""

CSRF_COOKIE_DOMAIN = smarter_settings.environment_platform_domain
"""
The domain to use for the CSRF cookie. This is set to the Smarter platform domain derived
from smarter_settings.

See:

- https://docs.djangoproject.com/en/5.0/ref/settings/#csrf-cookie-domain
- `Smarter Chat: <https://github.com/smarter-sh/smarter-chat/README.md>`__
- `React Integration <https://docs.smarter.sh/en/latest/developers/architecture/lib/react-integration.html#django-react-integration>`__
"""

CSRF_COOKIE_PATH = "/"
"""
The path to use for the CSRF cookie. Default is '/'.

See:

- https://docs.djangoproject.com/en/5.0/ref/settings/#csrf-cookie-path
- `Smarter Chat: <https://github.com/smarter-sh/smarter-chat/README.md>`__
- `React Integration <https://docs.smarter.sh/en/latest/developers/architecture/lib/react-integration.html#django-react-integration>`__
"""

CSRF_COOKIE_HTTPONLY = False
"""
A boolean that determines whether the CSRF cookie should be marked as "HttpOnly". Default is False
because the smarter-chat React frontend needs to read the CSRF cookie value via JavaScript to
include it in the 'X-CSRFToken' header of HTTP requests.

See:

- https://docs.djangoproject.com/en/5.0/ref/settings/#csrf-cookie-httponly
- `Smarter Chat: <https://github.com/smarter-sh/smarter-chat/README.md>`__
- `React Integration <https://docs.smarter.sh/en/latest/developers/architecture/lib/react-integration.html#django-react-integration>`__
"""

CSRF_HEADER_NAME = "HTTP_X_CSRFTOKEN"
"""
The name of the HTTP header that carries the CSRF token value. Default is 'HTTP_X_CSRFTOKEN',
which corresponds to the 'X-CSRFToken' header sent by smarter-chat React frontends.

See:

- https://docs.djangoproject.com/en/5.0/ref/settings/#csrf-header-name
- `Smarter Chat: <https://github.com/smarter-sh/smarter-chat/README.md>`__
- `React Integration <https://docs.smarter.sh/en/latest/developers/architecture/lib/react-integration.html#django-react-integration>`__
"""

CSRF_TRUSTED_ORIGINS = [
    smarter_settings.environment_platform_domain,
    smarter_settings.environment_api_domain,
]
"""
A list of trusted origins for cross-site request forgery protection. This is initialized
here with the Smarter platform and API domains derived from smarter_settings.

See:

- https://docs.djangoproject.com/en/5.0/ref/settings/#csrf-trusted-origins
- `Smarter Chat: <https://github.com/smarter-sh/smarter-chat/README.md>`__
- `React Integration <https://docs.smarter.sh/en/latest/developers/architecture/lib/react-integration.html#django-react-integration>`__
"""

CSRF_USE_SESSIONS = False
"""
A boolean that determines whether to store the CSRF token in the user session instead of
a cookie. Default is False because smarter-chat React frontends rely on the CSRF cookie.

See:

- https://docs.djangoproject.com/en/5.0/ref/settings/#csrf-use-sessions
- `Smarter Chat: <https://github.com/smarter-sh/smarter-chat/README.md>`__
- `React Integration <https://docs.smarter.sh/en/latest/developers/architecture/lib/react-integration.html#django-react-integration>`__
"""


# -------------------------------
# Django session settings
# -------------------------------
# Whether to set the flag restricting cookie leaks on cross-site requests.
# This can be 'Lax', 'Strict', 'None', or False to disable the flag.
SESSION_COOKIE_SAMESITE = "lax"
"""
The value for the SameSite flag on the session cookie. Default is 'Lax'. Smarters needs
this to be 'Lax' to support cross-site requests from smarter-chat React frontends.

See:

- https://docs.djangoproject.com/en/5.0/ref/settings/#session-cookie-samesite
- `Smarter Chat: <https://github.com/smarter-sh/smarter-chat/README.md>`__
- `React Integration <https://docs.smarter.sh/en/latest/developers/architecture/lib/react-integration.html#django-react-integration>`__
"""

SESSION_COOKIE_SECURE = False
"""
A boolean that determines whether the session cookie should be marked as "secure". This is set to
False in base settings but **should** be set to True in production environments. Note that
there are challenges with setting this to True if the Smarter platform is behind a load balancer or
reverse proxy that terminates SSL.

See:

- `Django reference: <https://docs.djangoproject.com/en/5.0/ref/settings/#session-cookie-secure>`__
- `Smarter Chat: <https://github.com/smarter-sh/smarter-chat/README.md>`__
- `React Integration <https://docs.smarter.sh/en/latest/developers/architecture/lib/react-integration.html#django-react-integration>`__
"""

SESSION_COOKIE_NAME = "sessionid"
"""
The name of the session cookie. Default is 'sessionid'. This is a placeholder for Smarter-specific
functionality in smarter.apps.prompt.views.ChatAppWorkbenchView.

See:

- https://docs.djangoproject.com/en/5.0/ref/settings/#session-cookie-name
- `Smarter Chat: <https://github.com/smarter-sh/smarter-chat/README.md>`__
- `React Integration <https://docs.smarter.sh/en/latest/developers/architecture/lib/react-integration.html#django-react-integration>`__
"""

SESSION_COOKIE_AGE = CSRF_COOKIE_AGE
"""
The age of the session cookie, in seconds. Default is 1209600 (2 weeks). Here it is set to match
the CSRF cookie age. This is a placeholder.
"""

SESSION_COOKIE_DOMAIN = smarter_settings.environment_platform_domain
"""
The domain to use for the session cookie. This is set to the Smarter platform domain derived
from smarter_settings.

See:

- https://docs.djangoproject.com/en/5.0/ref/settings/#session-cookie-domain
"""

SESSION_COOKIE_PATH = "/"
"""
The path to use for the session cookie. Default is '/'. This is a placeholder.

See:

- https://docs.djangoproject.com/en/5.0/ref/settings/#session-cookie-path
"""

SESSION_COOKIE_HTTPONLY = True
"""
A boolean that determines whether the session cookie should be marked as "HttpOnly". Default is True.

See:

- https://docs.djangoproject.com/en/5.0/ref/settings/#session-cookie-httponly
"""

SECURE_PROXY_SSL_HEADER = None
"""
A tuple representing a header/value combination that signifies a request is secure. This is set to None in base settings
and **should** be set appropriately in production environments if the Smarter platform is behind
a load balancer or reverse proxy that terminates SSL.

See: https://docs.djangoproject.com/en/5.0/ref/settings/#secure-proxy-ssl-header
"""

# Build paths inside the project like this: BASE_DIR / 'subdir'.
PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent


BASE_DIR = Path(os.path.join(PROJECT_ROOT, "smarter")).resolve()

# -------------------------------
# Django storages settings for AWS S3
# -------------------------------
# See https://django-storages.readthedocs.io/en/latest/backends/amazon
if smarter_settings.aws_is_configured:
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3.S3Storage",
            "OPTIONS": {
                "access_key": smarter_settings.aws_access_key_id.get_secret_value(),
                "secret_key": smarter_settings.aws_secret_access_key.get_secret_value(),
                "bucket_name": smarter_settings.aws_s3_bucket_name,
                "region_name": smarter_settings.aws_region,
                "default_acl": "public-read",
                "querystring_auth": False,
            },
        }
    }
else:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
            "OPTIONS": {
                "location": "/home/smarter_user/data/media",
            },
        }
    }
STORAGES["staticfiles"] = {
    "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    "OPTIONS": {},
}
"""
The Django storages configuration for Smarter. Uses AWS S3 if AWS is configured,
otherwise uses local filesystem storage.

See: https://docs.djangoproject.com/en/5.0/ref/settings/#std:setting-STORAGES
"""

DEFAULT_FILE_STORAGE = smarter_settings.django_default_file_storage
"""
The default file storage backend for Django. Uses AWS S3 if AWS is configured,
otherwise uses local filesystem storage. smarter_settings determines the appropriate
value based on whether or not it detects AWS authentication configuration in
the running environment.

See: https://docs.djangoproject.com/en/5.0/ref/settings/#default-file-storage
"""

AWS_ACCESS_KEY_ID = smarter_settings.aws_access_key_id.get_secret_value()
"""
Supplemental setting for configuring AWS support. The AWS access key ID
is retrieved and validated in smarter_settings.

For production deployments the chain of custody should be:

GitHub Secrets -> GitHub Actions -> environment variable -> smarter_settings -> Django AWS_ACCESS_KEY_ID.

"""

AWS_SECRET_ACCESS_KEY = smarter_settings.aws_secret_access_key.get_secret_value()
"""
Supplemental setting for configuring AWS support. The AWS secret access key
is retrieved and validated in smarter_settings.

For production deployments the chain of custody should be:

GitHub Secrets -> GitHub Actions -> environment variable -> smarter_settings -> Django AWS_SECRET_ACCESS_KEY.
"""

AWS_STORAGE_BUCKET_NAME = smarter_settings.aws_s3_bucket_name
"""
Supplemental setting for configuring AWS S3 storage support. The S3 bucket name
is derived in smarter_settings.
"""

AWS_S3_REGION_NAME = smarter_settings.aws_region
"""
Supplemental setting for configuring AWS support. The AWS region is
retrieved and validated in smarter_settings.
"""

AWS_QUERYSTRING_AUTH = False  # disable querystring auth for public files
"""
Supplemental setting for configuring AWS S3 storage support. Disables
querystring authentication for public files in favor of public-read ACL
that is configured in the Smarter Terraform scripts.

See:

- https://django-storages.readthedocs.io/en/latest/backends/amazon/#querystring-auth
- https://github.com/smarter-sh/smarter-infrastructure
"""

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

SECRET_KEY = smarter_settings.secret_key
"""
The secret key for this Django installation. This is retrieved and validated
from smarter_settings. If not set, a random key is generated and logged as a warning.

For production deployments the chain of custody should be:

GitHub Secrets -> GitHub Actions -> environment variable -> smarter_settings -> Django SECRET_KEY.

See: https://docs.djangoproject.com/en/5.0/ref/settings/#secret-key
"""

if not SECRET_KEY:
    random_string = secrets.token_urlsafe(64)
    random_bytes = random_string.encode("utf-8")
    hash_object = hashlib.sha256(random_bytes)
    SECRET_KEY = hash_object.hexdigest()
    logger.warning("SECRET_KEY not set. Using randomized value: %s", SECRET_KEY)

logger.debug("PROJECT_ROOT: %s", PROJECT_ROOT)
logger.debug("BASE_DIR: %s", BASE_DIR)
logger.debug("SECRET_KEY: %s", SECRET_KEY)


DEBUG = smarter_settings.debug_mode

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://:smarter@smarter-redis:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}
"""
The Django cache configuration for Smarter, using Redis as the cache backend.

See:

- https://docs.djangoproject.com/en/5.0/ref/settings/#caches
- https://github.com/smarter-sh/smarter/blob/main/docker-compose.yml
- https://artifacthub.io/packages/helm/project-smarter/smarter
"""

SESSION_ENGINE = "django.contrib.sessions.backends.cache"
"""
The Django session engine configuration for Smarter, using the cache backend
(Redis) for session storage. Storing sessions in Redis will preserve user sessions
across multiple web server instances in a load-balanced environment, and also
insulates from sessions being lost due to redeployments or restarts of web server.

See: https://docs.djangoproject.com/en/5.0/ref/settings/#session-engine
"""

# Default Celery Configuration
CELERY_BROKER_URL = "redis://:smarter@smarter-redis:6379/1"
"""
The Celery broker URL for Smarter, using Redis as the message broker.

See:

- https://docs.celeryq.dev/en/stable/getting-started/brokers/redis.html
- https://github.com/smarter-sh/smarter/blob/main/docker-compose.yml
- https://artifacthub.io/packages/helm/project-smarter/smarter
"""

CELERY_TASK_TIME_LIMIT = 30 * 60
"""
The maximum time limit (in seconds) for Celery tasks in Smarter. Default is 30 minutes.
Smarter sets this primarily due to indeterminate AWS Route53 DNS resolution and propagation
times when deploying ChatBots/Agents.

See: https://docs.celeryq.dev/en/stable/userguide/configuration.html#std:setting-task_time_limit
"""

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_hosts",
    "storages",
    # smarter apps
    # -------------------------------
    "smarter.lib.drf",
    "smarter.lib.journal",
    "smarter.apps.account",
    "smarter.apps.api",
    "smarter.apps.chatbot",
    "smarter.apps.prompt",
    "smarter.apps.cms",
    "smarter.apps.dashboard",
    "smarter.apps.docs",
    "smarter.apps.plugin",
    "smarter.apps.provider",
    # 3rd party apps
    # -------------------------------
    "rest_framework",
    "knox",
    "taggit",
    "corsheaders",
    "drf_yasg",
    "django_celery_beat",
    "django.contrib.admindocs",
    "social_django",
    "waffle",
    # Wagtail
    # -------------------------------
    # see https://docs.wagtail.org/en/stable/advanced_topics/add_to_django_project.html
    "wagtail.contrib.forms",
    "wagtail.contrib.redirects",
    "wagtail.embeds",
    "wagtail.sites",
    "wagtail.users",
    "wagtail.snippets",
    "wagtail.documents",
    "wagtail.images",
    "wagtail.search",
    "wagtail.admin",
    "wagtail",
    "wagtail_transfer",
    # Stripe
    # -------------------------------
    # "djstripe",
]

MIDDLEWARE = [
    "django_hosts.middleware.HostsRequestMiddleware",
    # this replaces corsheaders.middleware.CorsMiddleware"
    "smarter.lib.django.middleware.cors.SmarterCorsMiddleware",
    # this replaces django.middleware.security.SecurityMiddleware
    # simple middleware to block requests for common sensitive files
    # like .env, private key files, etc.
    # -------------------------------
    "smarter.lib.django.middleware.sensitive_files.SmarterBlockSensitiveFilesMiddleware",
    # to log and block excessive 404 errors, which is a growing problem
    # from botnets probing for vulnerabilities.
    # -------------------------------
    "smarter.lib.django.middleware.excessive_404.SmarterBlockExcessive404Middleware",
    #
    # -------------------------------
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "smarter.lib.drf.middleware.SmarterTokenAuthenticationMiddleware",
    "django.middleware.common.CommonMiddleware",
    # this replaces django.middleware.csrf.SmarterCsrfViewMiddleware
    # to add chatbot-specific CSRF handling
    # -------------------------------
    "smarter.lib.django.middleware.csrf.SmarterCsrfViewMiddleware",
    #
    # -------------------------------
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    # to manage ALLOWED_HOSTS
    # -------------------------------
    "smarter.apps.chatbot.middleware.security.SmarterSecurityMiddleware",
    #
    # -------------------------------
    # to ensure that all http responses are in json format
    # -------------------------------
    "smarter.lib.django.middleware.json.SmarterJsonErrorMiddleware",
    # -------------------------------
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "waffle.middleware.WaffleMiddleware",
    # wagtail middleware
    # -------------------------------
    "wagtail.contrib.redirects.middleware.RedirectMiddleware",
    "smarter.apps.cms.middleware.HTMLMinifyMiddleware",
    "django_hosts.middleware.HostsResponseMiddleware",
    #
]

ROOT_HOSTCONF = "smarter.hosts"
"""
The root host configuration module for django-hosts. Smarter hosts multiple subdomains
for platform, API, and chatbot apps. These are defined in smarter.hosts.

See: https://django-hosts.readthedocs.io/en/latest/
"""

ROOT_URLCONF = "smarter.urls.console"
"""
The root URL configuration module for Smarter. This points to smarter.urls.console,
which defines the URL patterns for the Smarter web platform console.

See: https://docs.djangoproject.com/en/5.0/ref/settings/#root-urlconf
"""

DEFAULT_HOST = SMARTER_PLATFORM_SUBDOMAIN
"""
The default host name for django-hosts. This is set to the Smarter platform subdomain.

See: https://django-hosts.readthedocs.io/en/latest/
"""

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "smarter.apps.account.context_processors.base",
                "smarter.apps.cms.context_processors.base",
                "smarter.apps.dashboard.context_processors.branding",
                "smarter.apps.dashboard.context_processors.base",
                "social_django.context_processors.backends",
                "social_django.context_processors.login_redirect",
                "wagtail.contrib.settings.context_processors.settings",
            ],
        },
    },
    {
        "NAME": "react",
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
        ],
        "APP_DIRS": False,
        "OPTIONS": {
            "loaders": [
                "django.template.loaders.filesystem.Loader",
            ],
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "smarter.apps.account.context_processors.base",
                "smarter.apps.dashboard.context_processors.base",
            ],
        },
    },
]

WSGI_APPLICATION = "smarter.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "smarter",
        "USER": "smarter",
        "PASSWORD": "smarter",
        "HOST": "smarter-mysql",  # Or an IP Address that your DB is hosted on
        "PORT": "3306",
    }
}
"""
The Django database configuration for Smarter, using MySQL as the database backend.
Smarter **should** be able to support other common Sql databases supported by Django
with minimal or no changes, but MySQL is the recommended and tested database backend.

This setting is environment specific and will typically be overridden in
smarter/smarter/settings/base_aws.py or other environment-specific settings files.

These credentials are created for you by the Smarter Terraform scripts when deploying
the Smarter platform.

For cloud deployments the chain of custody for database credentials should be:

Kubernetes Secret -> environment variable -> smarter_settings -> Django DATABASES.

See:

- https://docs.djangoproject.com/en/5.0/ref/settings/#databases
- https://github.com/smarter-sh/smarter-infrastructure
"""

# https://python-social-auth.readthedocs.io/en/latest/configuration/django.html
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTHENTICATION_BACKENDS = (
    "social_core.backends.google.GoogleOAuth2",
    "social_core.backends.github.GithubOAuth2",
    "smarter.lib.social_core.backends.linkedin.LinkedinOAuth2",
    "django.contrib.auth.backends.ModelBackend",
)
"""
The authentication backends for Smarter, including social authentication
backends for Google, GitHub, and LinkedIn, as well as the default Django
model backend.

Note that Smarter additionally implements its own custom key-based REST API
authentication backend.

See:

- https://docs.djangoproject.com/en/5.0/ref/settings/#authentication-backends
- https://docs.smarter.sh/en/latest/developers/architecture/lib/drf.html
"""

SOCIAL_AUTH_CREATE_USERS = False
"""
A boolean that determines whether to automatically create user accounts
when a user authenticates via a social authentication provider.

IMPORTANT: Smarter defaults this to False for security reasons to prevent
what is effectively random virtually-anonymous user account creation via
social authentication. User accounts should be created via the Smarter
platform console by an administrator, then linked to social authentication
providers as needed.

SETTING THIS TO TRUE IS A SECURITY AND A FINANCIAL RISK BECAUSE IT
WILL ALLOW ANY USERS (E.G. BOTNETS) TO CREATE ACCOUNTS AND ACCESS PAID
SERVICES WITHOUT RESTRICTION OR OVERSIGHT.
"""

SOCIAL_AUTH_PIPELINE = (
    # Get the information we can about the user and return it in a simple
    # format to create the user instance later. On some cases the details are
    # already part of the auth response from the provider, but sometimes this
    # could hit a provider API.
    "social_core.pipeline.social_auth.social_details",
    # Get the social uid from whichever service we're authing thru. The uid is
    # the unique identifier of the given user in the provider.
    "social_core.pipeline.social_auth.social_uid",
    # Verifies that the current auth process is valid within the current
    # project, this is where emails and domains whitelists are applied (if
    # defined).
    "social_core.pipeline.social_auth.auth_allowed",
    # Checks if the current social-account is already associated in the site.
    "social_core.pipeline.social_auth.social_user",
    # Make up a username for this person, appends a random string at the end if
    # there's any collision.
    "social_core.pipeline.user.get_username",
    # Send a validation email to the user to verify its email address.
    # 'social_core.pipeline.mail.mail_validation',
    # Associates the current social details with another user account with
    # a similar email address.
    "social_core.pipeline.social_auth.associate_by_email",
    # Create a user account if we haven't found one yet.
    "social_core.pipeline.user.create_user",
    # Create the record that associated the social account with this user.
    "social_core.pipeline.social_auth.associate_user",
    # Populate the extra_data field in the social record with the values
    # specified by settings (and the default ones like access_token, etc).
    "social_core.pipeline.social_auth.load_extra_data",
    # Update the user record with any changed info from the auth service.
    "social_core.pipeline.user.user_details",
)

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = smarter_settings.social_auth_google_oauth2_key.get_secret_value()
"""
Python Social Auth Google OAuth2 client ID for Smarter.

The chain of custody for this secret should be:

GitHub Secrets -> GitHub Actions -> environment variable -> smarter_settings -> Django SOCIAL_AUTH_GOOGLE_OAUTH2_KEY.

See: https://python-social-auth.readthedocs.io/en/latest/backends/google.html
"""

SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = smarter_settings.social_auth_google_oauth2_secret.get_secret_value()
"""
Python Social Auth Google OAuth2 client secret for Smarter.

The chain of custody for this secret should be:

GitHub Secrets -> GitHub Actions -> environment variable -> smarter_settings -> Django SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET.

See: https://python-social-auth.readthedocs.io/en/latest/backends/google.html
"""

SOCIAL_AUTH_GOOGLE_OAUTH2_REDIRECT_URI = urllib.parse.urljoin(
    smarter_settings.environment_url, "/social-auth/complete/google-oauth2/"
)
"""
The redirect URI for Google OAuth2 social authentication in Smarter.
Do not change this value unless you know what you are doing.

See: https://python-social-auth.readthedocs.io/en/latest/backends/google.html
"""

SOCIAL_AUTH_GITHUB_KEY = smarter_settings.social_auth_github_key.get_secret_value()
"""
Python Social Auth GitHub OAuth2 client ID for Smarter.

The chain of custody for this secret should be:

GitHub Secrets -> GitHub Actions -> environment variable -> smarter_settings -> Django SOCIAL_AUTH_GITHUB_KEY.

See: https://python-social-auth.readthedocs.io/en/latest/backends/github.html
"""

SOCIAL_AUTH_GITHUB_SECRET = smarter_settings.social_auth_github_secret.get_secret_value()
"""
Python Social Auth GitHub OAuth2 client secret for Smarter.

The chain of custody for this secret should be:

GitHub Secrets -> GitHub Actions -> environment variable -> smarter_settings -> Django SOCIAL_AUTH_GITHUB_SECRET.

See: https://python-social-auth.readthedocs.io/en/latest/backends/github.html
"""

SOCIAL_AUTH_LINKEDIN_OAUTH2_KEY = smarter_settings.social_auth_linkedin_oauth2_key.get_secret_value()
"""
Python Social Auth LinkedIn OAuth2 client ID for Smarter.

The chain of custody for this secret should be:

GitHub Secrets -> GitHub Actions -> environment variable -> smarter_settings -> Django SOCIAL_AUTH_LINKEDIN_OAUTH2_KEY.

See: https://python-social-auth.readthedocs.io/en/latest/backends/linkedin.html
"""
SOCIAL_AUTH_LINKEDIN_OAUTH2_SECRET = smarter_settings.social_auth_linkedin_oauth2_secret.get_secret_value()
"""
Python Social Auth LinkedIn OAuth2 client secret for Smarter.

NOTE: (Nov-2025) LinkedIn has deprecated OAuth2 client secrets for security reasons. The Smarter reference
cloud platform is no longer using LinkedIn OAuth2 for social authentication, but the configuration settings remain
here for backward compatibility with existing Smarter deployments that may still be using LinkedIn OAuth2.

The chain of custody for this secret should be:
GitHub Secrets -> GitHub Actions -> environment variable -> smarter_settings -> Django SOCIAL_AUTH_LINKEDIN_OAUTH2_SECRET.

See: https://python-social-auth.readthedocs.io/en/latest/backends/linkedin.html
"""

SOCIAL_AUTH_LINKEDIN_OAUTH2_SCOPE = ["openid", "profile", "email"]
"""
The OAuth2 scopes for LinkedIn social authentication in Smarter.

NOTE: (Nov-2025) LinkedIn has deprecated OAuth2 client secrets for security reasons. The Smarter reference
cloud platform is no longer using LinkedIn OAuth2 for social authentication, but the configuration settings remain
here for backward compatibility with existing Smarter deployments that may still be using LinkedIn OAuth2.

See: https://python-social-auth.readthedocs.io/en/latest/backends/linkedin.html
"""


SOCIAL_AUTH_LINKEDIN_OAUTH2_FIELD_SELECTORS = ["id", "first-name", "last-name", "email-address"]
"""
The OAuth2 field selectors for LinkedIn social authentication in Smarter.

NOTE: (Nov-2025) LinkedIn has deprecated OAuth2 client secrets for security reasons. The Smarter reference
cloud platform is no longer using LinkedIn OAuth2 for social authentication, but the configuration settings remain
here for backward compatibility with existing Smarter deployments that may still be using LinkedIn OAuth2.

See: https://python-social-auth.readthedocs.io/en/latest/backends/linkedin.html
"""

SOCIAL_AUTH_LINKEDIN_OAUTH2_REDIRECT_URI = urllib.parse.urljoin(
    smarter_settings.environment_url, "/social-auth/complete/linkedin-oauth2/"
)
"""
The redirect URI for LinkedIn OAuth2 social authentication in Smarter.

NOTE: (Nov-2025) LinkedIn has deprecated OAuth2 client secrets for security reasons. The Smarter reference
cloud platform is no longer using LinkedIn OAuth2 for social authentication, but the configuration settings remain
here for backward compatibility with existing Smarter deployments that may still be using LinkedIn OAuth2.

Do not change this value unless you know what you are doing.

See: https://python-social-auth.readthedocs.io/en/latest/backends/linkedin.html
"""

SOCIAL_AUTH_LINKEDIN_OAUTH2_EXTRA_DATA = [
    ("id", "id"),
    ("firstName", "first_name"),
    ("lastName", "last_name"),
    ("emailAddress", "email_address"),
]
"""
The extra data fields to retrieve from LinkedIn during social authentication in Smarter.

NOTE: (Nov-2025) LinkedIn has deprecated OAuth2 client secrets for security reasons. The Smarter reference
cloud platform is no longer using LinkedIn OAuth2 for social authentication, but the configuration settings remain
here for backward compatibility with existing Smarter deployments that may still be using LinkedIn OAuth2.

See: https://python-social-auth.readthedocs.io/en/latest/backends/linkedin.html
"""

SOCIAL_AUTH_ADMIN_USER_SEARCH_FIELDS = ["username", "first_name", "email"]
"""
The user fields that can be searched in the Django admin interface for social authentication users.

See: https://python-social-auth.readthedocs.io/en/latest/configuration/django.html#admin-integration
"""

LOGIN_URL = "/login/"
"""
The URL to redirect users to for login. Default is '/login/'. Do not change this
value unless you know what you are doing.

See: https://docs.djangoproject.com/en/5.0/ref/settings/#login-url
"""

LOGIN_REDIRECT_URL = "/"
"""
The URL to redirect users to after successful login. Default is '/'.
Do not change this value unless you know what you are doing.

See: https://docs.djangoproject.com/en/5.0/ref/settings/#login-redirect-url
"""

LOGOUT_REDIRECT_URL = "/"
"""
The URL to redirect users to after logout. Default is '/'.
Do not change this value unless you know what you are doing.

See: https://docs.djangoproject.com/en/5.0/ref/settings/#logout-redirect-url
"""


AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]
"""
The password validation settings for Smarter, using Django's built-in
password validators. These validators help ensure that user passwords
meet minimum security requirements. These rules should be sufficient
for most use cases, but can be customized as needed.

See: https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators
"""

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/
LANGUAGE_CODE = "en-us"
"""
The default language code for Smarter. Default is 'en-us'.

See: https://docs.djangoproject.com/en/5.0/ref/settings/#language-code
"""

TIME_ZONE = "UTC"
"""
The default time zone for Smarter. Default is 'UTC'.

See: https://docs.djangoproject.com/en/5.0/ref/settings/#time-zone
"""

USE_I18N = True
"""
A boolean that specifies whether Django's internationalization system
should be enabled. Default is True. I18N support is important for
Smarter to support multiple languages and locales.

See: https://docs.djangoproject.com/en/5.0/ref/settings/#use-i18n
"""

USE_TZ = True
"""
A boolean that specifies whether Django should use timezone-aware datetimes.
Default is True. Timezone support is important for Smarter to handle
date and time data correctly across different time zones.

timezone-aware datetimes help ensure that timestamps are accurate
and consistent regardless of the user's location. These were
released in Django 1.4 and are now standard practice for web applications.

See: https://docs.djangoproject.com/en/5.0/ref/settings/#use-tz
"""


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/
STATIC_URL = "/static/"
"""
The URL prefix for static files in Smarter. Default is '/static/'. This values needs to
be consistent with the STATICFILES_DIRS and STATIC_ROOT settings, and also
needs to consider how the Dockerfile file system is structured for serving static files.

Do not change this value unless you know what you are doing.

See:

- https://docs.djangoproject.com/en/5.0/ref/settings/#static-url
- https://github.com/smarter-sh/smarter/blob/main/Dockerfile
"""

STATIC_ROOT = PROJECT_ROOT / "staticfiles"
"""
The absolute file system path to the directory where static files will be collected.
This is set to the 'staticfiles' directory in the project root. This directory
is used by the 'collectstatic' management command to gather all static files
from the various Django apps and store them in a single location for serving.

See: https://docs.djangoproject.com/en/5.0/ref/settings/#static-root
"""

STATICFILES_DIRS = [BASE_DIR / "static"]
"""
A list of directories where Django will also look for static files, in addition
to each app's 'static' subdirectory. This is set to the 'static' directory
in the BASE_DIR. This allows for global static files that are not tied to
a specific app.

See: https://docs.djangoproject.com/en/5.0/ref/settings/#staticfiles-dirs
"""

STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"
"""
The static files storage backend for Smarter. This is set to use WhiteNoise's
CompressedStaticFilesStorage, which provides efficient static file serving
with compression and caching support.

This is the recommended static files storage backend for production deployments
of Django applications.
"""

# ReactJS integration with Django. Add all reactapp/dist directories in Django apps
django_apps_dir = BASE_DIR / "apps"
reactapp_dirs = [Path(p) for p in glob.glob(os.path.join(django_apps_dir, "*", "reactapp", "dist"))]
STATICFILES_DIRS.extend(reactapp_dirs)

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
"""
The default primary key field type for Django models in Smarter. This is set to 'BigAutoField', which
is a 64-bit integer that automatically increments. This is suitable for most use cases and provides
a large range of values for primary keys.

See: https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field
"""

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "smarter.lib.drf.token_authentication.SmarterTokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticated"],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
        "smarter.lib.drf.parsers.YAMLParser",
        "rest_framework.parsers.FormParser",
        "rest_framework.parsers.MultiPartParser",
    ],
}
"""
The Django REST Framework configuration for Smarter, including default authentication classes,
permission classes, and parser classes.

Do not change these values unless you know what you are doing. Even then, it's probably a bad idea.

See: https://www.django-rest-framework.org/api-guide/settings/
"""

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "timestamped": {
            "format": "%(asctime)s - %(levelname)s - %(message)s",
            "datefmt": "[%Y-%m-%d %H:%M:%S %z]",
        },
    },
    "handlers": {
        "default": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "timestamped",
        },
    },
    "root": {
        "handlers": ["default"],
        "level": "INFO",
    },
    "loggers": {
        "django.security.DisallowedHost": {
            "handlers": ["default"],
            "level": "ERROR",
            "propagate": False,
        },
    },
}
logging.config.dictConfig(LOGGING)

# https://dj-stripe.dev/dj-stripe/2.7/installation/
STRIPE_LIVE_SECRET_KEY = smarter_settings.stripe_live_secret_key
STRIPE_TEST_SECRET_KEY = smarter_settings.stripe_test_secret_key
STRIPE_LIVE_MODE = False  # Change to True in production
DJSTRIPE_WEBHOOK_SECRET = (
    "whsec_xxx"  # Get it from the section in the Stripe dashboard where you added the webhook endpoint
)
DJSTRIPE_USE_NATIVE_JSONFIELD = True  # We recommend setting to True for new installations
DJSTRIPE_FOREIGN_KEY_TO_FIELD = "id"

SMTP_SENDER = smarter_settings.smtp_sender
"""
The default sender email address for outgoing emails from Smarter.
This is derived from smarter_settings.

See: https://docs.djangoproject.com/en/5.0/topics/email/
"""

SMTP_FROM_EMAIL = smarter_settings.smtp_from_email
"""
The default "from" email address for outgoing emails from Smarter.
This is derived from smarter_settings.

See: https://docs.djangoproject.com/en/5.0/topics/email/
"""

SMTP_HOST = smarter_settings.smtp_host
"""
The SMTP host for outgoing emails from Smarter. This is derived from smarter_settings.

See: https://docs.djangoproject.com/en/5.0/topics/email/
"""

SMTP_PASSWORD = smarter_settings.smtp_password
"""
The SMTP password for outgoing emails from Smarter. This is derived from smarter_settings.
When using AWS SES as the SMTP service, this is the SMTP password generated from the AWS SES console.
Note that this is NOT the AWS secret access key, nor is it the AWS IAM user password.

This credential is created for you when using the Smarter Terraform scripts to deploy
the Smarter cloud platform with AWS SES as the SMTP service.

For production deployments the chain of custody should be:

Kubernetes Secret -> environment variable -> smarter_settings -> Django SMTP_PASSWORD.

See:

- https://docs.djangoproject.com/en/5.0/topics/email/
- https://github.com/smarter-sh/smarter-infrastructure
"""

SMTP_PORT = smarter_settings.smtp_port
"""
The SMTP port for outgoing emails from Smarter. This is derived from smarter_settings.

See: https://docs.djangoproject.com/en/5.0/topics/email/
"""

SMTP_USE_SSL = smarter_settings.smtp_use_ssl
"""
A boolean that specifies whether to use SSL for SMTP connections in Smarter. This is derived from smarter_settings.

See: https://docs.djangoproject.com/en/5.0/topics/email/
"""

SMTP_USE_TLS = smarter_settings.smtp_use_tls
"""
A boolean that specifies whether to use TLS for SMTP connections in Smarter. This is derived from smarter_settings.

See: https://docs.djangoproject.com/en/5.0/topics/email/
"""

SMTP_USERNAME = smarter_settings.smtp_username
"""
The SMTP username for outgoing emails from Smarter. This is derived from smarter_settings.
When using AWS SES as the SMTP service, this is the SMTP password generated from the AWS SES console.
Note that this is NOT the AWS secret access key, nor is it the AWS IAM user password.

This credential is created for you when using the Smarter Terraform scripts to deploy
the Smarter cloud platform with AWS SES as the SMTP service.

For production deployments the chain of custody should be:

Kubernetes Secret -> environment variable -> smarter_settings -> Django SMTP_PASSWORD.

See:

- https://docs.djangoproject.com/en/5.0/topics/email/
- https://github.com/smarter-sh/smarter-infrastructure
"""

# Wagtail settings
# This is the human-readable name of your Wagtail install
# which welcomes users upon login to the Wagtail admin.
WAGTAIL_SITE_NAME = "Smarter"
"""
The human-readable name of the Wagtail installation for Smarter. This name is displayed in the Wagtail admin interface
and is used to identify the Wagtail site.

Smarter uses Wagtail for web console CMS functionality including for example, dynamic help documentation pages
for Smarter Manifests and Json Schemas.

Do not change any Wagtail settings value unless you know what you are doing.

See: https://docs.wagtail.org/en/stable/reference/settings.html#wagtail-site-name
"""

# Replace the search backend
# WAGTAILSEARCH_BACKENDS = {
#  'default': {
#    'BACKEND': 'wagtail.search.backends.elasticsearch8',
#    'INDEX': 'myapp'
#  }
# }

# Wagtail email notifications from address
WAGTAILADMIN_NOTIFICATION_FROM_EMAIL = SMTP_FROM_EMAIL

# Wagtail email notification format
WAGTAILADMIN_NOTIFICATION_USE_HTML = True

# Allowed file extensions for documents in the document library.
# This can be omitted to allow all files, but note that this may present a security risk
# if untrusted users are allowed to upload files -
# see https://docs.wagtail.org/en/stable/advanced_topics/deploying.html#user-uploaded-files
WAGTAILDOCS_EXTENSIONS = ["csv", "docx", "key", "odt", "pdf", "pptx", "rtf", "txt", "xlsx", "zip"]

# Reverse the default case-sensitive handling of tags
TAGGIT_CASE_INSENSITIVE = True

WAGTAILADMIN_BASE_URL = "/cms/admin/"

WAGTAILTRANSFER_SOURCES = {
    "localhost": {
        "BASE_URL": "http://localhost:8000/wagtail-transfer/",
        "SECRET_KEY": "qr4hlujl144ye5hwn0k3f0no462ms81z",
    },
    "alpha": {
        "BASE_URL": "https://alpha.platform.smarter.sh/wagtail-transfer/",
        "SECRET_KEY": "1tv70boz9norbi2puxirls697j6v4x75",
    },
    "beta": {
        "BASE_URL": "https://beta.platform.smarter.sh/wagtail-transfer/",
        "SECRET_KEY": "rle5zr18w3igmsauc3pvu4uu9eo54egg",
    },
    "next": {
        "BASE_URL": "https://next.platform.smarter.sh/wagtail-transfer/",
        "SECRET_KEY": "3uy59hvdewlihhmee4duc5ytw277f34b",
    },
    "production": {
        "BASE_URL": "https://platform.smarter.sh/wagtail-transfer/",
        "SECRET_KEY": "q6ea0u8vt1u8eoprtxq5d9p5wae83fje",
    },
}

WAGTAILTRANSFER_SECRET_KEY = "8egf3jj8ib64j00gomz270wgzqwrfyed"
WAGTAILTRANSFER_CHOOSER_API_PROXY_TIMEOUT = 30

###############################################################################
# System information logging for all environments
###############################################################################
if SMARTER_SETTINGS_OUTPUT or "manage.py" not in sys.argv[0]:
    logger.info("=" * 80)

    try:
        with open("/proc/uptime", encoding="utf-8") as f:
            uptime_seconds = float(f.readline().split()[0])
            uptime_str = time.strftime("%H:%M:%S", time.gmtime(uptime_seconds))
            logger.info("Container uptime: %s", uptime_str)
    except FileNotFoundError:
        logger.warning("Container uptime not available")
    except OSError as e:
        logger.error("Error reading container uptime: %s", e)

    try:
        # CPU limit (cgroup v2)
        cpu_limit = None
        cpu_max_path = "/sys/fs/cgroup/cpu.max"
        if os.path.exists(cpu_max_path):
            with open(cpu_max_path, encoding="utf-8") as f:
                quota, period = f.read().strip().split()
                if quota != "max":
                    cpu_limit = math.ceil(int(quota) / int(period))
                else:
                    cpu_limit = int(subprocess.check_output("nproc", shell=True).decode().strip())
        else:
            cpu_limit = int(subprocess.check_output("nproc", shell=True).decode().strip())

        # Memory limit (cgroup v2)
        mem_limit = None
        mem_max_path = "/sys/fs/cgroup/memory.max"
        if os.path.exists(mem_max_path):
            with open(mem_max_path, encoding="utf-8") as f:
                mem_bytes = int(f.read().strip())
                if mem_bytes < 1 << 60:  # If not unlimited
                    mem_gib = mem_bytes / 1024 / 1024 / 1024
                    mem_limit = mem_gib
                else:
                    # Fallback to /proc/meminfo
                    mem_total_line = subprocess.check_output("grep MemTotal /proc/meminfo", shell=True).decode().strip()
                    mem_kib = int(mem_total_line.split()[1])
                    mem_limit = mem_kib / 1024 / 1024
        else:
            mem_total_line = subprocess.check_output("grep MemTotal /proc/meminfo", shell=True).decode().strip()
            mem_kib = int(mem_total_line.split()[1])
            mem_limit = mem_kib / 1024 / 1024

        logger.info("CPU limit: %s cores", cpu_limit)
        if cpu_limit < 2:
            logger.warning("Recommended minimum CPU limit is 2. Detected: %s cores", cpu_limit)
        logger.info("Memory limit: %.2f GiB", mem_limit)
        if mem_limit < 4.0:
            logger.warning("Recommended minimum memory limit is 4 GiB. Detected: %.2f GiB", mem_limit)
    except (OSError, subprocess.CalledProcessError) as e:
        logger.warning("Resource limits not available: %s", e)
    except (ValueError, IndexError) as e:
        logger.error("Error parsing resource limits: %s", e)

    try:
        debian_version = "not found"
        with open("/etc/debian_version", encoding="utf-8") as f:
            debian_version = f.read().strip()
        logger.info("Debian v%s %s", debian_version, os.uname().version)
    except FileNotFoundError:
        logger.error("Debian version file not found")
    except OSError as e:
        logger.error("Error reading Debian version: %s", e)

    logger.info("Python v%s", sys.version)
    logger.info("Django v%s", get_version())
    logger.info("Smarter v%s", smarter_version)
    logger.info("Default file storage: %s", DEFAULT_FILE_STORAGE)
    logger.info("Storages backend: %s", STORAGES["default"]["BACKEND"])

    logger.info("Cache backend: %s", CACHES["default"]["BACKEND"])

    try:
        cache.set("test_key", "test_value", timeout=5)
        value = cache.get("test_key")
        if value == "test_value":
            logger.info("Redis is up and reachable.")
        else:
            logger.error("Redis is not working as expected.")
    # pylint: disable=broad-except
    except Exception as e:
        logger.error("Redis is NOT reachable: %s", e)

    if smarter_settings.smtp_is_configured:
        logger.info("SMTP server configured: %s:%s (SSL=%s, TLS=%s)", SMTP_HOST, SMTP_PORT, SMTP_USE_SSL, SMTP_USE_TLS)
    else:
        logger.warning("SMTP server not configured")
    if smarter_settings.aws_is_configured:
        logger.info("AWS credentials detected")
    else:
        logger.warning("AWS credentials not found.")
    logger.info("=" * 80)
