# pylint: disable=missing-module-docstring,missing-function-docstring,missing-class-docstring
# Generated by Django 5.0.6 on 2024-05-21 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chat", "0001_initial"),
        ("plugin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatpluginusage",
            name="plugin",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="plugin.pluginmeta"),
        ),
        migrations.AddField(
            model_name="chattoolcall",
            name="chat",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="chat.chat"),
        ),
        migrations.AddField(
            model_name="chattoolcall",
            name="plugin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="plugin.pluginmeta",
            ),
        ),
    ]
