# pylint: disable=all
# Generated by Django 6.0.4 on 2026-04-23 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
        ("prompt", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="user_profile",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="account.userprofile"),
        ),
    ]
