# pylint: disable=all
# Generated by Django 5.2.10 on 2026-03-14 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompt", "0002_alter_chat_annotations_alter_chat_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="version",
            field=models.CharField(
                blank=True,
                default="1.0.0",
                help_text="Semantic version in the format MAJOR.MINOR.PATCH, e.g., '1.0.0'.",
                max_length=255,
                null=True,
            ),
        ),
    ]
