# pylint: disable=missing-module-docstring,missing-function-docstring,missing-class-docstring
# Generated by Django 5.2.7 on 2026-01-09 07:34

from django.db import migrations, models

import smarter.lib.json


class Migration(migrations.Migration):

    dependencies = [
        ("prompt", "0003_alter_chat_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="annotations",
            field=models.JSONField(
                blank=True,
                default=list,
                encoder=smarter.lib.json.SmarterJSONEncoder,
                help_text="Key-value pairs for annotating this resource.",
            ),
        ),
        migrations.AlterField(
            model_name="chathistory",
            name="messages",
            field=models.JSONField(blank=True, encoder=smarter.lib.json.SmarterJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name="chathistory",
            name="request",
            field=models.JSONField(blank=True, encoder=smarter.lib.json.SmarterJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name="chathistory",
            name="response",
            field=models.JSONField(blank=True, encoder=smarter.lib.json.SmarterJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name="chattoolcall",
            name="request",
            field=models.JSONField(blank=True, encoder=smarter.lib.json.SmarterJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name="chattoolcall",
            name="response",
            field=models.JSONField(blank=True, encoder=smarter.lib.json.SmarterJSONEncoder, null=True),
        ),
    ]
