# Generated by Django 5.1.3 on 2025-01-09 17:42
# pylint: disable=missing-module-docstring,missing-function-docstring,missing-class-docstring
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_chat_account_chat_chatbot"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="chat",
            unique_together={("session_key", "url")},
        ),
    ]
