# Generated by Django 5.1.3 on 2025-01-20 21:49
# pylint: disable=missing-module-docstring,missing-function-docstring,missing-class-docstring

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_alter_chat_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="chathistory",
            name="messages",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
