# pylint: disable=missing-module-docstring,missing-function-docstring,missing-class-docstring
# Generated by Django 5.0.4 on 2024-04-22 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatBotRequests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("request", models.JSONField(blank=True, null=True)),
                (
                    "is_aggregation",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ChatBot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("deployed", models.BooleanField(blank=True, default=False, null=True)),
                (
                    "default_model",
                    models.CharField(blank=True, default="gpt-3.5-turbo", max_length=255, null=True),
                ),
                (
                    "default_temperature",
                    models.FloatField(blank=True, default=0.5, null=True),
                ),
                (
                    "default_max_tokens",
                    models.IntegerField(blank=True, default=256, null=True),
                ),
                (
                    "app_name",
                    models.CharField(blank=True, default="chatbot", max_length=255, null=True),
                ),
                (
                    "app_assistant",
                    models.CharField(blank=True, default="Smarter", max_length=255, null=True),
                ),
                (
                    "app_welcome_message",
                    models.CharField(
                        blank=True,
                        default="Welcome to the chatbot!",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "app_example_prompts",
                    models.JSONField(blank=True, default="[]", null=True),
                ),
                (
                    "app_placeholder",
                    models.CharField(
                        blank=True,
                        default="Type something here...",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "app_info_url",
                    models.URLField(blank=True, default="https://smarter.sh", null=True),
                ),
                ("app_background_image_url", models.URLField(blank=True, null=True)),
                ("app_logo_url", models.URLField(blank=True, null=True)),
                (
                    "app_file_attachment",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.account",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ChatBotAPIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "api_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.smarterauthtoken",
                    ),
                ),
                (
                    "chatbot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chatbot.chatbot",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ChatBotCustomDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("aws_hosted_zone_id", models.CharField(max_length=255)),
                ("domain_name", models.CharField(max_length=255)),
                (
                    "is_verified",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.account",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="chatbot",
            name="custom_domain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="chatbot.chatbotcustomdomain",
            ),
        ),
        migrations.CreateModel(
            name="ChatBotCustomDomainDNS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("record_name", models.CharField(max_length=255)),
                ("record_type", models.CharField(max_length=255)),
                ("record_value", models.CharField(max_length=255)),
                ("record_ttl", models.IntegerField(blank=True, default=600, null=True)),
                (
                    "custom_domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chatbot.chatbotcustomdomain",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="chatbot",
            name="subdomain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="chatbot.chatbotcustomdomaindns",
            ),
        ),
        migrations.CreateModel(
            name="ChatBotFunctions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("weather", "weather"),
                            ("news", "news"),
                            ("prices", "prices"),
                            ("math", "math"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "chatbot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chatbot.chatbot",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ChatBotPlugin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "chatbot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chatbot.chatbot",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
