# pylint: disable=missing-docstring,missing-module-docstring,missing-class-docstring,missing-function-docstring
# Generated by Django 5.0.4 on 2024-05-15 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chatbot", "0001_initial"),
        ("plugin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatbotplugin",
            name="plugin_meta",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="plugin.pluginmeta"),
        ),
        migrations.AddField(
            model_name="chatbotrequests",
            name="chatbot",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="chatbot.chatbot"),
        ),
    ]
