# pylint: disable=all
# Generated by Django 5.2.7 on 2026-01-25 15:29

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0001_initial"),
        ("chatbot", "0001_initial"),
        ("drf", "0001_initial"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="chatbotapikey",
            name="api_key",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="drf.smarterauthtoken"),
        ),
        migrations.AddField(
            model_name="chatbotapikey",
            name="chatbot",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="chatbot.chatbot"),
        ),
        migrations.AddField(
            model_name="chatbotcustomdomain",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="Tags for categorizing and organizing this resource.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="chatbotcustomdomain",
            name="user_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="account.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="chatbot",
            name="custom_domain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="chatbot.chatbotcustomdomain",
            ),
        ),
        migrations.AddField(
            model_name="chatbotcustomdomaindns",
            name="custom_domain",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="chatbot.chatbotcustomdomain",
            ),
        ),
        migrations.AddField(
            model_name="chatbot",
            name="subdomain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="chatbot.chatbotcustomdomaindns",
            ),
        ),
        migrations.AddField(
            model_name="chatbotfunctions",
            name="chatbot",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="chatbot.chatbot"),
        ),
        migrations.AddField(
            model_name="chatbotplugin",
            name="chatbot",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="chatbot.chatbot"),
        ),
    ]
