# pylint: disable=missing-module-docstring, missing-function-docstring, missing-class-docstring
# Generated by Django 5.0.4 on 2024-04-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatbot",
            name="app_assistant",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="chatbot",
            name="app_background_image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatbot",
            name="app_example_prompts",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatbot",
            name="app_file_attachment",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="chatbot",
            name="app_info_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatbot",
            name="app_logo_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatbot",
            name="app_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="chatbot",
            name="app_placeholder",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="chatbot",
            name="app_welcome_message",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
