# pylint: disable=all
# Generated by Django 5.2.7 on 2026-01-25 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chatbot", "0002_initial"),
        ("plugin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatbotplugin",
            name="plugin_meta",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="plugin.pluginmeta"),
        ),
        migrations.AddField(
            model_name="chatbotrequests",
            name="chatbot",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="chatbot.chatbot"),
        ),
        migrations.AlterUniqueTogether(
            name="chatbot",
            unique_together={("user_profile", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="chatbotplugin",
            unique_together={("chatbot", "plugin_meta")},
        ),
    ]
