# pylint: disable=all
# Generated by Django 5.2.10 on 2026-03-14 22:57

from django.db import migrations, models

import smarter.lib.json


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatbot",
            name="annotations",
            field=models.JSONField(
                blank=True,
                default=list,
                encoder=smarter.lib.json.SmarterJSONEncoder,
                help_text="Key-value pairs for annotating this resource.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="chatbot",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="A brief description of this resource. Be verbose, but not too verbose.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="chatbotcustomdomain",
            name="annotations",
            field=models.JSONField(
                blank=True,
                default=list,
                encoder=smarter.lib.json.SmarterJSONEncoder,
                help_text="Key-value pairs for annotating this resource.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="chatbotcustomdomain",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="A brief description of this resource. Be verbose, but not too verbose.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="chatbotfunctions",
            name="name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("get_current_weather", "get_current_weather"),
                    ("date_calculator", "date_calculator"),
                    ("calculator", "calculator"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
