# Generated by Django 5.1.3 on 2024-12-30 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0003_chatbot_default_system_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatbot",
            name="provider",
            field=models.CharField(blank=True, default="openai", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="chatbot",
            name="default_model",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
