# Generated by Django 5.1.3 on 2025-01-09 17:42
# pylint: disable=missing-module-docstring,missing-function-docstring,missing-class-docstring

from django.db import migrations, models

import smarter.apps.chatbot.models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0004_chatbot_provider_alter_chatbot_default_model"),
        ("plugin", "0002_pluginprompt_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatbotrequests",
            name="session_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="chatbot",
            name="provider",
            field=models.CharField(
                blank=True,
                default="openai",
                max_length=255,
                null=True,
                validators=[smarter.apps.chatbot.models.validate_provider],
            ),
        ),
        migrations.AlterUniqueTogether(
            name="chatbotplugin",
            unique_together={("chatbot", "plugin_meta")},
        ),
    ]
