# Generated by Django 5.1.3 on 2025-01-09 18:52
# pylint: disable=missing-module-docstring,missing-function-docstring,missing-class-docstring

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0005_chatbotrequests_session_key_alter_chatbot_provider_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatbotrequests",
            options={"verbose_name_plural": "ChatBot Requests History"},
        ),
    ]
