# Generated by Django 5.1.3 on 2025-02-10 17:49
# pylint: disable=missing-module-docstring,missing-function-docstring,missing-class-docstring

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0006_alter_chatbotrequests_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatbot",
            name="default_max_tokens",
            field=models.IntegerField(blank=True, default=2048, null=True),
        ),
    ]
