# Generated by Django 5.1.3 on 2025-02-19 17:04
# pylint: disable=missing-module-docstring,missing-function-docstring,missing-class-docstring

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0007_alter_chatbot_default_max_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatbot",
            name="tls_certificate_issuance_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("No Certificate", "No Certificate"),
                    ("Requested", "Requested"),
                    ("Issued", "Issued"),
                    ("Failed", "Failed"),
                ],
                default="No Certificate",
                max_length=255,
                null=True,
            ),
        ),
    ]
