# Generated by Django 5.1.7 on 2025-05-20 16:38
# pylint: disable=missing-module-docstring,missing-function-docstring,missing-class-docstring

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0009_alter_account_created_at_alter_account_updated_at_and_more"),
        ("chatbot", "0009_alter_chatbot_created_at_alter_chatbot_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="chatbot",
            unique_together={("account", "name")},
        ),
    ]
