# Generated by Django 5.2.5 on 2025-09-05 17:28
# pylint: disable=missing-module-docstring,missing-function-docstring,missing-class-docstring

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0010_alter_chatbot_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatbot",
            old_name="default_max_tokens",
            new_name="default_max_completion_tokens",
        ),
    ]
