# Generated by Django 5.2.6 on 2025-09-19 17:40
# pylint: disable=missing-module-docstring,missing-function-docstring,missing-class-docstring

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "chatbot",
            "0011_rename_default_max_tokens_chatbot_default_max_completion_tokens",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatbot",
            old_name="default_max_completion_tokens",
            new_name="default_max_tokens",
        ),
    ]
