# pylint: disable=missing-module-docstring,missing-function-docstring,missing-class-docstring
# Generated by Django 5.2.7 on 2025-12-27 13:54

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models

import smarter.lib.django.model_helpers
import smarter.lib.django.validators


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0013_userprofile_annotations_userprofile_description_and_more"),
        ("chatbot", "0013_chatbot_annotations_chatbot_tags_and_more"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="chatbotcustomdomain",
            name="annotations",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Key-value pairs for annotating this resource.",
            ),
        ),
        migrations.AddField(
            model_name="chatbotcustomdomain",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="A brief description of this resource. Be verbose, but not too verbose.",
            ),
        ),
        migrations.AddField(
            model_name="chatbotcustomdomain",
            name="name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Name in camelCase, e.g., 'apiKey', no special characters.",
                max_length=255,
                validators=[
                    smarter.lib.django.validators.SmarterValidator.validate_snake_case,
                    smarter.lib.django.model_helpers.validate_no_spaces,
                ],
            ),
        ),
        migrations.AddField(
            model_name="chatbotcustomdomain",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="Tags for categorizing and organizing this resource.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="chatbotcustomdomain",
            name="version",
            field=models.CharField(default="1.0.0", max_length=255),
        ),
        migrations.AlterField(
            model_name="chatbot",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="account.account",
            ),
        ),
        migrations.AlterField(
            model_name="chatbotcustomdomain",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="account.account",
            ),
        ),
    ]
