# pylint: disable=missing-module-docstring,missing-function-docstring,missing-class-docstring
# Generated by Django 5.2.7 on 2026-01-09 07:34

from django.db import migrations, models

import smarter.lib.json


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0015_alter_chatbot_name_alter_chatbotcustomdomain_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatbot",
            name="annotations",
            field=models.JSONField(
                blank=True,
                default=list,
                encoder=smarter.lib.json.SmarterJSONEncoder,
                help_text="Key-value pairs for annotating this resource.",
            ),
        ),
        migrations.AlterField(
            model_name="chatbot",
            name="app_example_prompts",
            field=models.JSONField(
                blank=True,
                default=list,
                encoder=smarter.lib.json.SmarterJSONEncoder,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="chatbotcustomdomain",
            name="annotations",
            field=models.JSONField(
                blank=True,
                default=list,
                encoder=smarter.lib.json.SmarterJSONEncoder,
                help_text="Key-value pairs for annotating this resource.",
            ),
        ),
        migrations.AlterField(
            model_name="chatbotrequests",
            name="request",
            field=models.JSONField(blank=True, encoder=smarter.lib.json.SmarterJSONEncoder, null=True),
        ),
    ]
