# pylint: disable=all
# Generated by Django 6.0.5 on 2026-06-08 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("llmclient", "0001_initial"),
        ("plugin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmclientplugin",
            name="plugin_meta",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="plugin.pluginmeta"),
        ),
        migrations.AddField(
            model_name="llmclientrequests",
            name="llmclient",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="llmclient.llmclient"),
        ),
        migrations.AlterUniqueTogether(
            name="llmclient",
            unique_together={("user_profile", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="llmclientplugin",
            unique_together={("llmclient", "plugin_meta")},
        ),
    ]
