# pylint: disable=all
# Generated by Django 6.0.5 on 2026-07-12 23:55

import django.db.models.deletion
from django.db import migrations, models

import smarter.common.mixins.helper_mixin


class Migration(migrations.Migration):

    dependencies = [
        ("guardrail", "0001_initial"),
        ("llmclient", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMClientGuardrails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "guardrail",
                    models.ForeignKey(
                        help_text="The Guardrail.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guardrail",
                        to="guardrail.guardrail",
                    ),
                ),
                (
                    "llmclient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="llmclient.llmclient",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "LLMClient Guardrails",
            },
            bases=(models.Model, smarter.common.mixins.helper_mixin.SmarterHelperMixin),
        ),
    ]
