# Generated by Django 6.0.5 on 2026-09-30 11:32

import django.db.models.deletion
from django.db import migrations, models

import smarter.common.mixins.helper_mixin


class Migration(migrations.Migration):

    dependencies = [
        ("llmclient", "0003_llmclientguardrails"),
        ("mcpclient", "0002_connection_fields_and_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMClientMCPClients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "llmclient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="llmclient.llmclient",
                    ),
                ),
                (
                    "mcpclient",
                    models.ForeignKey(
                        help_text="The MCPClient.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llmclient_mcpclients",
                        to="mcpclient.mcpclient",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "LLMClient MCPClients",
                "unique_together": {("llmclient", "mcpclient")},
            },
            bases=(models.Model, smarter.common.mixins.helper_mixin.SmarterHelperMixin),
        ),
    ]
