# pylint: disable=all
# Generated by Django 6.0.5 on 2026-09-30 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guardrail", "0001_initial"),
        ("llmclient", "0004_llmclientmcpclients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmclientguardrails",
            name="guardrail",
            field=models.ForeignKey(
                help_text="The Guardrail.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="llmclient_guardrails",
                to="guardrail.guardrail",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="llmclientguardrails",
            unique_together={("llmclient", "guardrail")},
        ),
    ]
