# pylint: disable=W0613
"""
Views for the React chat component used in the Smarter web application.
"""

import logging
import traceback
from http import HTTPStatus
from typing import Any, Optional, Union

from django.conf import settings
from django.db import models
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.shortcuts import redirect, render
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt

from smarter.apps.account.utils import get_cached_smarter_admin_user_profile
from smarter.apps.chatbot.models import (
    ChatBot,
    ChatBotHelper,
    ChatBotPlugin,
    ChatBotRequests,
    ChatBotRequestsSerializer,
    get_cached_chatbot_by_request,
)
from smarter.apps.chatbot.serializers import (
    ChatBotConfigSerializer,
    ChatBotPluginSerializer,
)
from smarter.apps.chatbot.utils import get_cached_chatbots_for_user_profile
from smarter.apps.plugin.models import (
    PluginSelectorHistory,
    PluginSelectorHistorySerializer,
)
from smarter.apps.prompt.models import Chat, ChatHelper
from smarter.common.conf import smarter_settings
from smarter.common.const import SMARTER_CHAT_SESSION_KEY_NAME
from smarter.common.exceptions import (
    SmarterException,
)
from smarter.common.helpers.console_helpers import formatted_json
from smarter.common.helpers.url_helpers import clean_url
from smarter.common.mixins import SmarterHelperMixin
from smarter.common.utils import is_authenticated_request, rfc1034_compliant_to_snake
from smarter.lib.django import waffle
from smarter.lib.django.http.shortcuts import (
    SmarterHttpResponseForbidden,
    SmarterHttpResponseNotFound,
    SmarterHttpResponseServerError,
)
from smarter.lib.django.view_helpers import (
    SmarterAuthenticatedNeverCachedWebView,
    SmarterNeverCachedWebView,
)
from smarter.lib.django.waffle import SmarterWaffleSwitches
from smarter.lib.drf.view_helpers import UnauthenticatedPermissionClass
from smarter.lib.journal.enum import SmarterJournalCliCommands, SmarterJournalThings
from smarter.lib.journal.http import (
    SmarterJournaledJsonErrorResponse,
    SmarterJournaledJsonResponse,
)
from smarter.lib.logging import WaffleSwitchedLoggerWrapper

from .signals import chat_config_invoked, chat_session_invoked

MAX_RETURNED_PLUGINS = 10


def should_log(level):
    """Check if logging should be done based on the waffle switch."""
    return waffle.switch_is_active(SmarterWaffleSwitches.PROMPT_LOGGING)


base_logger = logging.getLogger(__name__)
logger = WaffleSwitchedLoggerWrapper(base_logger, should_log)


class SmarterChatappViewError(SmarterException):
    """Base class for all SmarterChatapp errors."""

    @property
    def get_formatted_err_message(self):
        return "Smarter Chatapp error"


class SmarterChatSession(SmarterHelperMixin):
    """
    Helper class that provides methods for creating a session key and client key.
    """

    _chat: Optional[Chat] = None
    _chat_helper: Optional[ChatHelper] = None
    _chatbot: Optional[ChatBot] = None
    request: Optional[HttpRequest] = None
    _session_key: str

    def __init__(self, request: HttpRequest, session_key: str, *args, chatbot: Optional[ChatBot] = None, **kwargs):
        super().__init__()
        logger.debug("SmarterChatSession().__init__() called with session_key=%s, chatbot=%s", session_key, chatbot)
        self.request = request
        if not isinstance(session_key, str):
            logger.error("%s - session_key is not a string: %s", self.formatted_class_name, type(session_key))
        self._session_key = session_key

        if chatbot:
            self._chatbot = chatbot
            self.user_profile = chatbot.user_profile

        # leaving this in place as a reminder that we need one or the other
        if not self.session_key and not self.chatbot:
            logger.error("%s - either session_key or chatbot must be provided", self.formatted_class_name)

        self._chat_helper = ChatHelper(request, *args, session_key=self.session_key, chatbot=self.chatbot, **kwargs)
        self._chat = self._chat_helper.chat

        logger.debug("%s - session established: %s", self.formatted_class_name, self.session_key)

        chat_session_invoked.send(sender=self.__class__, instance=self, request=request)

    def __str__(self):
        return f"{self.__class__.__name__}(chatbot={self.chatbot}, session_key={self.session_key})"

    def __repr__(self):
        return self.__str__()

    def __eq__(self, value: object) -> bool:
        return isinstance(value, SmarterChatSession) and self.session_key == value.session_key

    @property
    def session_key(self) -> str:
        """
        The session key for this chat session. This is used to identify the chat session
        and is generated by the /config/ endpoint.
        """
        if self._session_key is None:
            logger.error(
                "%s - session_key is None. This should not happen. Please report this issue to the Smarter team.",
                self.formatted_class_name,
            )
        return self._session_key

    @property
    def chatbot(self):
        return self._chatbot

    @property
    def chat(self):
        return self._chat

    @property
    def chat_helper(self):
        return self._chat_helper

    def clean_url(self, url: str) -> str:
        """
        Clean the url of any query strings and trailing '/config/' strings.
        """
        retval = clean_url(url)
        if retval.endswith("/config/"):
            retval = retval[:-8]
        return retval


# pylint: disable=R0902
@method_decorator(csrf_exempt, name="dispatch")
class ChatConfigView(SmarterNeverCachedWebView):
    """
    Chat configuration view for the Smarter web application.

    This view is responsible for providing all configuration information required by the ReactJS chat UI component.
    It is designed to be performant and efficient, as it is invoked on every user-facing browser load and refresh.
    The endpoint is session-based, with sessions uniquely defined by the `SmarterChatSession` class, which uses a combination
    of IP address and device-identifying information to distinguish individual chat sessions.

    **Key Features:**

    - **Django Template-Based:**
      This view uses Django's template system for rendering and does not rely on Django REST Framework (DRF) serializers for its main response.
      The configuration data is returned as a JSON response, but the view itself is structured as a Django class-based view.

    - **CSRF Exempt:**
      The view is decorated with `@csrf_exempt` because it is read-only and does not modify server-side data. This exemption is safe in this context
      and avoids unnecessary CSRF validation for GET and POST requests that only retrieve configuration data.

    - **ReactJS UI Integration:**
      The endpoint provides all necessary configuration and context information for the ReactJS chat component. This includes chatbot metadata,
      plugin information, session keys, and historical data relevant to the chat session. The React app consumes this configuration to initialize
      and render the chat UI in the user's browser.

    - **Session-Based Architecture:**
      Each chat session is uniquely identified and managed by the `SmarterChatSession` helper class. Sessions are tied to both the user's IP address
      and device-specific information, ensuring that each device and browser instance receives a unique session key. This session key is critical for
      tracking chat history, plugin usage, and other session-specific data.

    - **Performance Considerations:**
      Since this endpoint is called on every browser load and refresh, performance is a primary concern. The view is optimized to minimize database
      queries and serialization overhead. Only a limited number of plugins (as defined by `MAX_RETURNED_PLUGINS`) are returned to avoid excessive payload sizes.
      Caching and efficient queryset usage are employed where possible to ensure fast response times for end users.

    **Example Usage:**

        https://smarter.3141-5926-5359.alpha.api.example.com/config/

    **Returns:**
        JSON response containing:
            - `session_key`: Unique identifier for the chat session.
            - `sandbox_mode`: Boolean indicating if the chatbot is running in sandbox mode.
            - `debug_mode`: Boolean indicating if debug mode is enabled.
            - `chatbot`: Serialized chatbot configuration.
            - `history`: Chat and plugin selector history for the session.
            - `meta_data`: Additional metadata for the chatbot.
            - `plugins`: Plugin metadata and a limited list of plugins.

    **Security:**
        - The view is protected and requires the user to be authenticated, unless the chatbot is configured to allow unauthenticated access.
        - If authentication is required and the user is not authenticated, a 403 Forbidden response is returned.

    **See Also:**
        - `SmarterChatSession`: Helper class for managing chat sessions.
        - `ChatBotConfigSerializer`, `ChatBotPluginSerializer`: Serializers for chatbot and plugin data.
        - `ChatBotHelper`: Helper for chatbot-related operations.
    """

    authentication_classes = None
    permission_classes = (UnauthenticatedPermissionClass,)

    thing: Optional[SmarterJournalThings] = None
    command: Optional[SmarterJournalCliCommands] = None
    session: Optional[SmarterChatSession] = None
    chatbot_name: Optional[str] = None
    _chatbot_helper: Optional[ChatBotHelper] = None
    _chatbot: Optional[ChatBot] = None

    @property
    def chatbot(self) -> Optional[ChatBot]:
        return self._chatbot

    @property
    def chatbot_helper(self) -> Optional[ChatBotHelper]:
        if self._chatbot_helper:
            return self._chatbot_helper
        if self.chatbot:
            # throw everything but the kitchen sink at the ChatBotHelper
            self._chatbot_helper = ChatBotHelper(
                request=self.smarter_request,
                session_key=self.session.session_key if self.session else None,
                name=self._chatbot.name if self._chatbot else self.chatbot_name,
                chatbot_id=self._chatbot.id if self._chatbot else None,  # type: ignore[union-attr]
                account=self.account,
                user=self.user,
                user_profile=self.user_profile,
            )
        else:
            self._chatbot_helper = ChatBotHelper(
                request=self.smarter_request,
                name=self.chatbot_name or self.smarter_request_chatbot_name,
                session_key=self.session.session_key if self.session else None,
                account=self.account,
                user=self.user,
                user_profile=self.user_profile,
            )
        return self._chatbot_helper

    @chatbot_helper.setter
    def chatbot_helper(self, value: Optional[ChatBotHelper]):
        self._chatbot_helper = value
        if self._chatbot_helper and self._chatbot_helper.chatbot:
            self._chatbot = self._chatbot_helper.chatbot
            self.account = self._chatbot_helper.account
            self.user = self._chatbot_helper.user
            self.user_profile = self._chatbot_helper.user_profile
            logger.debug("%s - chatbot_helper() setter chatbot=%s", self.formatted_class_name, self.chatbot)
        else:
            self._chatbot = None
            logger.debug("%s - chatbot_helper() setter chatbot is unset", self.formatted_class_name)

    def clean_url(self, url: str) -> str:
        """
        Clean the url of any query strings and trailing '/config/' strings.
        """
        retval = clean_url(url)
        if retval.endswith("/config/"):
            retval = retval[:-8]
        return retval

    def config(self) -> dict[str, Any]:
        """
        Assemble and return the configuration dictionary required by the ReactJS chat UI component.

        This method gathers all relevant context and configuration data for the chat session and chatbot,
        and returns it as a dictionary suitable for JSON serialization. This configuration is consumed by
        the ReactJS frontend to initialize and render the chat interface.

        **Key Features:**

        - **Django Template-Based:**
          This logic is part of a Django class-based view and does not use Django REST Framework (DRF) serializers
          for the main response, though serializers are used for some nested data.

        - **CSRF Exempt:**
          The parent view is CSRF exempt because this endpoint is strictly read-only and does not modify server-side data.

        - **ReactJS UI Integration:**
          The returned dictionary provides all configuration and context information needed by the ReactJS chat component,
          including chatbot metadata, plugin information, session keys, and chat history.

        - **Session-Based:**
          The configuration is tied to a unique chat session, as defined by the :class:`SmarterChatSession` helper,
          which uses a combination of the user's IP address and device-identifying information to uniquely identify
          each session.

        - **Performance:**
          Since this endpoint is called on every browser load and refresh, the logic is optimized to minimize database
          queries and serialization overhead. Only a limited number of plugins (see ``MAX_RETURNED_PLUGINS``) are returned
          to keep payloads small and response times fast.

        Returns
        -------
        dict
            A dictionary containing all configuration data required by the ReactJS chat UI component. The structure includes:

            - ``session_key``: Unique identifier for the chat session.
            - ``sandbox_mode``: Boolean indicating if the chatbot is running in sandbox mode.
            - ``debug_mode``: Boolean indicating if debug mode is enabled.
            - ``chatbot``: Serialized chatbot configuration.
            - ``history``: Chat and plugin selector history for the session.
            - ``meta_data``: Additional metadata for the chatbot.
            - ``plugins``: Plugin metadata and a limited list of plugins.

        Raises
        ------
        SmarterValueError
            If the session or chatbot helper is not set.

        See Also
        --------
        SmarterChatSession : Helper class for managing chat sessions.
        ChatBotConfigSerializer, ChatBotPluginSerializer : Serializers for chatbot and plugin data.
        ChatBotHelper : Helper for chatbot-related operations.
        """
        # add chatbot_request_history and plugin_selector_history to history
        # these have to be added here due to circular import issues.
        if self.session is None:
            logger.error(
                "%s.config() - session is None. Cannot retrieve chatbot request history.", self.formatted_class_name
            )
            return {}
        if self.chatbot_helper is None:
            logger.error(
                "%s.config() - ChatBotHelper is None. Cannot retrieve chatbot request history.",
                self.formatted_class_name,
            )
            return {}

        chatbot_serializer = (
            ChatBotConfigSerializer(self.chatbot, context={"request": self.smarter_request}) if self.chatbot else None
        )

        # plugins context. the main thing we need here is to constrain the number of plugins
        # returned to some reasonable number, since we'll probaably have cases where
        # the chatbot has a lot of plugins (hundreds, thousands...).
        chatbot_plugins_count = ChatBotPlugin.objects.filter(chatbot=self.chatbot).count()
        chatbot_plugins = ChatBotPlugin.objects.filter(chatbot=self.chatbot).order_by("-pk")[:MAX_RETURNED_PLUGINS]
        chatbot_plugin_serializer = ChatBotPluginSerializer(chatbot_plugins, many=True)
        history = self.session.chat_helper.history if self.session.chat_helper else {}

        chatbot_requests_queryset = ChatBotRequests.objects.filter(session_key=self.session.session_key).order_by("-id")
        chatbot_requests_serializer = ChatBotRequestsSerializer(chatbot_requests_queryset, many=True)
        history["chatbot_request_history"] = chatbot_requests_serializer.data

        plugin_selector_history_queryset = PluginSelectorHistory.objects.filter(session_key=self.session.session_key)
        plugin_selector_history_serializer = PluginSelectorHistorySerializer(
            plugin_selector_history_queryset, many=True
        )
        history["plugin_selector_history"] = plugin_selector_history_serializer.data

        retval = {
            "data": {
                SMARTER_CHAT_SESSION_KEY_NAME: self.session.session_key,
                "sandbox_mode": self.chatbot_helper.is_chatbot_sandbox_url,
                "debug_mode": waffle.switch_is_active(SmarterWaffleSwitches.REACTAPP_DEBUG_MODE),
                "chatbot": chatbot_serializer.data if chatbot_serializer else None,
                "history": history,
                "meta_data": self.chatbot_helper.to_json(),
                "plugins": {
                    "meta_data": {
                        "total_plugins": chatbot_plugins_count,
                        "plugins_returned": len(chatbot_plugins),
                    },
                    "plugins": chatbot_plugin_serializer.data,
                },
            },
        }
        chat_config_invoked.send(sender=self.__class__, instance=self, request=self.smarter_request, data=retval)
        return retval

    def dispatch(
        self, request: HttpRequest, *args, chatbot_id: Optional[int] = None, **kwargs
    ) -> Union[JsonResponse, HttpResponse, SmarterJournaledJsonErrorResponse]:
        """
        Handles incoming HTTP requests for the chat configuration endpoint.

        This method is responsible for orchestrating the retrieval and assembly of all configuration data
        required by the ReactJS chat UI component. It is invoked on every user-facing browser load and refresh,
        making performance a critical concern.

        **Key Details:**

        - **Django Template-Based:**
          This view uses Django's class-based view and template system, not Django REST Framework (DRF).
          The response is a JSON object, but the view logic is not DRF-based.

        - **CSRF Exempt:**
          The view is decorated with ``@csrf_exempt`` because it is strictly read-only and does not modify server-side data.
          This avoids unnecessary CSRF validation for GET and POST requests that only retrieve configuration data.

        - **ReactJS UI Integration:**
          The endpoint provides all configuration and context information needed by the ReactJS chat component,
          including chatbot metadata, plugin information, session keys, and chat history.

        - **Session-Based:**
          Sessions are managed by the :class:`SmarterChatSession` helper, which uniquely defines a chat session
          using a combination of the user's IP address and device-identifying information. This ensures each device/browser
          instance receives a unique session key, which is used to track chat history and plugin usage.

        - **Performance:**
          Since this endpoint is called on every browser load and refresh, it is optimized to minimize database queries
          and serialization overhead. Only a limited number of plugins are returned (see ``MAX_RETURNED_PLUGINS``)
          to keep payloads small and response times fast.

        Parameters
        ----------
        request : HttpRequest
            The incoming HTTP request object.
        chatbot_id : Optional[int], default=None
            The ID of the chatbot to retrieve configuration for, if specified.
        *args
            Additional positional arguments.
        **kwargs
            Additional keyword arguments.

        Returns
        -------
        Union[JsonResponse, HttpResponse, SmarterJournaledJsonErrorResponse]
            A JSON response containing all configuration data required by the ReactJS chat UI component,
            or an error response if the request is invalid or unauthorized.

        See Also
        --------
        SmarterChatSession : Helper class for managing chat sessions.
        ChatBotConfigSerializer, ChatBotPluginSerializer : Serializers for chatbot and plugin data.
        ChatBotHelper : Helper for chatbot-related operations.
        """
        logger.debug(
            "%s.dispatch() called with request=%s, chatbot_id=%s, session_key=%s chatbot_name=%s user_profile=%s",
            self.formatted_class_name,
            request.build_absolute_uri(),
            chatbot_id,
            self.session_key,
            self.chatbot_name,
            self.user_profile,
        )

        if self.user_profile is None:
            logger.warning(
                "%s.dispatch() - %s user_profile is None. This may cause issues with the chat config view.",
                self.formatted_class_name,
                request.build_absolute_uri(),
            )

        if chatbot_id is not None:
            try:
                self._chatbot = ChatBot.objects.get(id=chatbot_id)
                self.chatbot_name = self._chatbot.name
                logger.debug(
                    "%s.dispatch() - set chatbot=%s from chatbot_id=%s",
                    self.formatted_class_name,
                    self._chatbot,
                    chatbot_id,
                )
            except ChatBot.DoesNotExist:
                logger.error(
                    "%s.dispatch() - ChatBot with id=%s does not exist. Returning 404.",
                    self.formatted_class_name,
                    chatbot_id,
                )
                return JsonResponse({"error": "Not found"}, status=HTTPStatus.NOT_FOUND.value)
        else:
            self.chatbot_name = kwargs.get("name")
            try:
                self._chatbot = get_cached_chatbot_by_request(request=request)
                if not self._chatbot:
                    logger.debug(
                        "%s.dispatch() - get_cached_chatbot_by_request() returned None. Attempting to instantiate ChatBotHelper with additional info",
                        self.formatted_class_name,
                    )
                    self.chatbot_helper = ChatBotHelper(
                        request=self.smarter_request,
                        session_key=self.session_key,
                        chatbot_id=chatbot_id,
                        name=self.chatbot_name,
                        account=self.account,
                        user=self.user,
                        user_profile=self.user_profile,
                    )
            except ChatBot.DoesNotExist:
                return JsonResponse({"error": "Not found"}, status=HTTPStatus.NOT_FOUND.value)

        # Initialize the chat session for this request. session_key is generated
        # and managed by the /config/ endpoint for the chatbot
        #
        # examples:
        # - https://customer-support.3141-5926-5359.api.example.com/workbench/config/?session_key=123456
        # - http://localhost:9357/api/v1/chatbots/1556/chat/config/?session_key=0733c7b3a33e7eb733c95f6d7fc88d671b6c957e6857a04d05b3f5905167116f
        #
        # The React app calls this endpoint at app initialization to get a
        # json dict that includes, among other pertinent info, this session_key
        # which uniquely identifies the device and the individual chatbot session
        # for the device.
        self.session = SmarterChatSession(request, session_key=self.session_key, chatbot=self.chatbot)

        logger.warning("%s authentication is disabled for this view.", self.formatted_class_name)

        if (
            self.chatbot_helper
            and self.chatbot_helper.is_authentication_required
            and not is_authenticated_request(request)
        ):
            return SmarterHttpResponseForbidden(
                request,
                "Authentication failed. Are you logged in? Smarter sessions automatically expire after 24 hours.",
            )

        logger.debug(
            "%s - chatbot=%s - chatbot_helper=%s", self.formatted_class_name, self.chatbot, self.chatbot_helper
        )

        if not self.chatbot:
            return JsonResponse({"error": "Not found"}, status=HTTPStatus.NOT_FOUND.value)

        self.thing = SmarterJournalThings(SmarterJournalThings.CHAT_CONFIG)
        self.command = SmarterJournalCliCommands(SmarterJournalCliCommands.CHAT_CONFIG)

        logger.debug(
            "%s.dispatch() completed with chatbot=%s, session_key=%s",
            self.formatted_class_name,
            self.chatbot,
            self.session.session_key if self.session else "(Missing session)",
        )
        return super().dispatch(request, *args, **kwargs)  # type: ignore[return-value]

    def __str__(self):
        return str(self.chatbot) if self.chatbot else "ChatConfigView"

    # pylint: disable=unused-argument
    def post(self, request: HttpRequest, *args, **kwargs) -> SmarterJournaledJsonResponse:
        """
        Get the chatbot configuration.
        """
        logger.debug("%s - post()", self.formatted_class_name)
        data = self.config()
        return SmarterJournaledJsonResponse(request=request, data=data, thing=self.thing, command=self.command)

    # pylint: disable=unused-argument
    def get(self, request: HttpRequest, *args, **kwargs) -> SmarterJournaledJsonResponse:
        """
        Get the chatbot configuration.
        """
        logger.debug("%s - get()", self.formatted_class_name)
        data = self.config()
        return SmarterJournaledJsonResponse(request=request, data=data, thing=self.thing, command=self.command)


@method_decorator(csrf_exempt, name="dispatch")
class ChatAppWorkbenchView(SmarterAuthenticatedNeverCachedWebView):
    """
    Chat app view for the Smarter web application.

    This view is responsible for serving the main chat application page within the Smarter dashboard web app.
    It integrates the ReactJS chat UI with the Django template system by injecting a React build artifact snippet
    (served from an AWS Cloudfront CDN) into the Django-rendered HTML template. The React app then takes over the UI
    from there.

    **Key Features:**

    - **Django Template Integration:**
      The view uses Django's template system to render the main chat page. It injects the React app's loader script
      and root div into the template, allowing seamless integration between Django and React.

    - **ReactJS UI Bootstrapping:**
      The React build (JavaScript and CSS) is loaded from a CDN and injected into the DOM. The React app is responsible
      for rendering the interactive chat UI after the initial page load.

    - **Flexible URL Patterns:**
      The view supports both sandbox and production URL formats, allowing it to work with deployed and not-yet-deployed ChatBots.

    - **Authentication Protected:**
      This view requires the user to be authenticated. If the user is not authenticated, access is denied.

    - **Cache Control:**
      The view uses Django's `never_cache` decorator to ensure that the browser does not cache the chat page itself.
      This prevents issues where a user logs out and then logs back in without a full page refresh.

    **Example Usage:**

        Sandbox mode:
            - http://smarter.sh/workbench/hr/
            - http://127.0.0.1:9357/workbench/<str:name>/

        Production mode:
            - https://hr.3141-5926-5359.alpha.api.example.com/workbench/

    **Returns:**
        Renders the Django template for the chat app, injecting the React loader and configuration context.

    **See Also:**
        - `ChatConfigView` — for the endpoint that provides configuration data to the React app.
    """

    template_path = "prompt/workbench.html"

    # The React app originates from
    #  - https://github.com/smarter-sh/smarter-chat and
    #  - https://github.com/smarter-sh/web-integration-example
    # and is built-deployed to AWS Cloudfront. The React app is loaded from
    # a url like: https://cdn.alpha.platform.smarter.sh/ui-chat/index.html
    reactjs_cdn_path = smarter_settings.smarter_reactjs_app_loader_path
    reactjs_loader_url = smarter_settings.smarter_reactjs_app_loader_url

    chatbot: Optional[ChatBot] = None
    chatbot_helper: Optional[ChatBotHelper] = None

    def dispatch(self, request: HttpRequest, *args, **kwargs):
        """
        Dispatch method to handle the request for the main chat application page.

        This method is responsible for preparing and serving the Django template that bootstraps the ReactJS chat UI
        within the Smarter dashboard web app. It injects the React loader script and configuration context into the
        template, enabling seamless integration between Django and React.

        **Key Features:**

        - **Django Template Integration:**
          Uses Django's template system to render the main chat page, injecting the React app's loader script and root div.

        - **ReactJS UI Bootstrapping:**
          Loads the React build (JavaScript and CSS) from a CDN and injects it into the DOM. The React app then takes over
          rendering the interactive chat UI after the initial page load.

        - **Flexible URL Patterns:**
          Supports both sandbox and production URL formats, allowing the view to work with both deployed and not-yet-deployed ChatBots.

        - **Authentication Protected:**
          Requires the user to be authenticated. If the user is not authenticated, access is denied.

        - **Cache Control:**
          Uses Django's `never_cache` decorator to prevent the browser from caching the chat page, ensuring session security.

        Parameters
        ----------
        request : HttpRequest
            The incoming HTTP request object.
        *args
            Additional positional arguments.
        **kwargs
            Additional keyword arguments.

        Returns
        -------
        HttpResponse
            Renders the Django template for the chat app, injecting the React loader and configuration context.

        See Also
        --------
        ChatConfigView : The endpoint that provides configuration data to the React app.
        """
        if (
            not hasattr(request, "user")
            or not hasattr(request.user, "is_authenticated")
            or not request.user.is_authenticated
        ):
            return redirect("/login/")

        retval = super().dispatch(request, *args, **kwargs)
        if retval.status_code >= HTTPStatus.BAD_REQUEST:
            return retval

        name = kwargs.pop("name", None)
        name = rfc1034_compliant_to_snake(name) if name else None
        session_key = kwargs.pop(SMARTER_CHAT_SESSION_KEY_NAME, None)
        if session_key is not None:
            self._session_key = session_key
            logger.debug(
                "%s.dispatch() - setting session_key=%s from kwargs, name=%s from kwargs",
                self.formatted_class_name,
                self.session_key,
                name,
            )

        try:
            logger.debug(
                "%s.dispatch() - url=%s, account=%s, user=%s, name=%s",
                self.formatted_class_name,
                self.url,
                self.account,
                self.user_profile.user,
                name,
            )
            self.chatbot = get_cached_chatbot_by_request(request=self.smarter_request)
            if not self.chatbot:
                self.chatbot_helper = ChatBotHelper(
                    request=self.smarter_request,
                    session_key=self.session_key,
                    name=name,
                    account=self.account,
                    user=self.user,
                    user_profile=self.user_profile,
                )
                self.chatbot = self.chatbot_helper.chatbot if self.chatbot_helper.chatbot else None
            if self.chatbot:
                logger.debug(
                    "%s.dispatch() - set chatbot=%s from self.chatbot_helper",
                    self.formatted_class_name,
                    self.chatbot,
                )
            else:
                return SmarterHttpResponseNotFound(request=request, error_message="ChatBot not found")
        except ChatBot.DoesNotExist:
            return SmarterHttpResponseNotFound(request=request, error_message="ChatBot not found")
        # pylint: disable=broad-except
        except Exception as e:
            logger.error(
                "%s.dispatch() - Exception occurred while getting chatbot: %s. "
                "Request URL: %s, Session Key: %s, Name: %s\nStack trace: %s",
                self.formatted_class_name,
                str(e),
                request.build_absolute_uri(),
                self.session_key,
                name,
                traceback.format_exc(),
            )
            return SmarterHttpResponseServerError(request=request, error_message=str(e))

        if not self.chatbot:
            return SmarterHttpResponseNotFound(request=request, error_message="ChatBot not found")

        # the basic idea is to pass the names of the necessary cookies to the React app, and then
        # it is supposed to find and read the cookies to get the chat session key, csrf token, etc.
        context = {
            "chatapp_workbench": {
                "div_id": smarter_settings.smarter_reactjs_root_div_id,
                "app_loader_url": self.reactjs_loader_url,
                "chatbot_api_url": self.chatbot.url,
                "toggle_metadata": True,
                "csrf_cookie_name": settings.CSRF_COOKIE_NAME,
                "smarter_session_cookie_name": SMARTER_CHAT_SESSION_KEY_NAME,  # this is the Smarter chat session, not the Django session.
                "django_session_cookie_name": settings.SESSION_COOKIE_NAME,  # this is the Django session.
                "cookie_domain": settings.SESSION_COOKIE_DOMAIN,
                "debug_mode": waffle.switch_is_active(SmarterWaffleSwitches.REACTAPP_DEBUG_MODE),
            }
        }
        logger.debug(
            "%s.dispatch() - rendering template %s with context: %s",
            self.formatted_class_name,
            self.template_path,
            formatted_json(context),
        )
        return render(request=request, template_name=self.template_path, context=context)


class PromptListView(SmarterAuthenticatedNeverCachedWebView):
    """
    list view for smarter workbench web console. This view is protected and
    requires the user to be authenticated. It generates cards for each
    ChatBots.
    """

    template_path = "prompt/listview.html"
    chatbots: Optional[models.QuerySet[ChatBot]] = None
    chatbot_helpers: list[ChatBotHelper] = []

    def dispatch(self, request: HttpRequest, *args, **kwargs):

        logger.debug(
            "%s.dispatch() called for %s with args %s, kwargs %s", self.formatted_class_name, request, args, kwargs
        )
        response = super().dispatch(request, *args, **kwargs)
        if response.status_code >= 300:
            return response

        self.chatbot_helpers = get_cached_chatbots_for_user_profile(self.user_profile.id)
        smarter_admin = get_cached_smarter_admin_user_profile()
        context = {"prompt_list": {"smarter_admin": smarter_admin, "chatbot_helpers": self.chatbot_helpers}}
        logger.debug(
            "%s.dispatch() rendering template %s with context: %s",
            self.formatted_class_name,
            self.template_path,
            formatted_json(context),
        )
        return render(request, template_name=self.template_path, context=context)
