# pylint: disable=all
# Generated by Django 6.0.5 on 2026-07-07 14:02

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models

import smarter.common.mixins.helper_mixin
import smarter.lib.django.validators
import smarter.lib.json


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0003_alter_aggregatedcharges_options"),
        ("secret", "0001_initial"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="MCPClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name in camelCase, e.g., 'apiKey', no special characters.",
                        max_length=255,
                        validators=[
                            smarter.lib.django.validators.SmarterValidator.validate_snake_case,
                            smarter.lib.django.validators.SmarterValidator.validate_no_spaces,
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="A brief description of this resource. Be verbose, but not too verbose.",
                        null=True,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        default="1.0.0",
                        help_text="Semantic version in the format MAJOR.MINOR.PATCH, e.g., '1.0.0'.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "annotations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        encoder=smarter.lib.json.SmarterJSONEncoder,
                        help_text="Key-value pairs for annotating this resource.",
                        null=True,
                    ),
                ),
                (
                    "transport",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("stdio", "Stdio (local subprocess)"),
                            ("sse", "Server-Sent Events"),
                            ("http", "Streamable HTTP"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "endpoint_url",
                    models.URLField(
                        blank=True,
                        help_text="Required for sse/http transports; omitted for stdio.",
                        null=True,
                    ),
                ),
                (
                    "command",
                    models.CharField(
                        blank=True,
                        help_text="Executable + args for stdio transport, e.g. 'npx @scope/server'.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Transport-specific params: headers, env vars, timeout_s, retry_policy, etc.",
                        null=True,
                    ),
                ),
                (
                    "auth_type",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("api_key", "API Key"),
                            ("oauth2", "OAuth 2.0"),
                            ("bearer_token", "Bearer Token"),
                        ],
                        default="none",
                        max_length=16,
                    ),
                ),
                (
                    "allowed_tools",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tool name allowlist exposed to the harness; empty = all tools the server advertises.",
                        null=True,
                    ),
                ),
                (
                    "allowed_resources",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Resource URI patterns this client may access; empty = all.",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unconfigured", "Unconfigured"),
                            ("connected", "Connected"),
                            ("disconnected", "Disconnected"),
                            ("error", "Error"),
                        ],
                        default="unconfigured",
                        max_length=16,
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=100,
                        help_text="Resolution order when multiple MCPClients could serve a request; lower runs first.",
                    ),
                ),
                (
                    "protocol_version",
                    models.CharField(
                        blank=True,
                        help_text="Negotiated MCP protocol version from the last successful handshake.",
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "credentials",
                    models.ForeignKey(
                        blank=True,
                        help_text="auth credential",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="secret.secret",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="Tags for categorizing and organizing this resource.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "MCPClients",
                "unique_together": {("user_profile", "name")},
            },
            bases=(models.Model, smarter.common.mixins.helper_mixin.SmarterHelperMixin),
        ),
    ]
