# pylint: disable=all
# Generated by Django 6.0.5 on 2026-09-30 11:31

import django.db.models.deletion
from django.db import migrations, models


def copy_config(apps, schema_editor):
    """Copy the headers and timeout of the former config field into their new fields."""
    MCPClient = apps.get_model("mcpclient", "MCPClient")
    for mcpclient in MCPClient.objects.exclude(config=None):
        config = mcpclient.config if isinstance(mcpclient.config, dict) else {}
        headers = config.get("headers")
        timeout = config.get("timeout_s") or config.get("timeout")
        if isinstance(headers, dict):
            mcpclient.headers = {str(k): str(v) for k, v in headers.items()}
        if isinstance(timeout, int) and 1 <= timeout <= 120:
            mcpclient.timeout = timeout
        mcpclient.save(update_fields=["headers", "timeout"])


class Migration(migrations.Migration):

    dependencies = [
        ("mcpclient", "0001_initial"),
        ("secret", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mcpclient",
            name="api_key_header",
            field=models.CharField(
                default="X-API-Key",
                help_text="The HTTP header that carries an api_key credential.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="mcpclient",
            name="cache_ttl",
            field=models.PositiveIntegerField(
                default=300,
                help_text="Seconds to cache the MCP server's tools, instructions and capabilities. 0 disables caching.",
            ),
        ),
        migrations.AddField(
            model_name="mcpclient",
            name="headers",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Non-secret HTTP headers to send to the MCP server.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="mcpclient",
            name="include_instructions",
            field=models.BooleanField(
                default=True,
                help_text="Add the MCP server's instructions to the system prompt.",
            ),
        ),
        migrations.AddField(
            model_name="mcpclient",
            name="last_connected_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When Smarter last connected to the MCP server.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="mcpclient",
            name="last_error",
            field=models.TextField(
                blank=True,
                help_text="The error of the last failed connection, if any.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="mcpclient",
            name="server_name",
            field=models.CharField(
                blank=True,
                help_text="The name that the MCP server reported.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="mcpclient",
            name="server_version",
            field=models.CharField(
                blank=True,
                help_text="The version that the MCP server reported.",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="mcpclient",
            name="timeout",
            field=models.PositiveSmallIntegerField(
                default=30,
                help_text="Seconds to wait for the MCP server to connect and respond.",
            ),
        ),
        migrations.AddField(
            model_name="mcpclient",
            name="tools",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="The names of the tools offered to the LLM, as of the last successful connection.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mcpclient",
            name="allowed_resources",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Glob patterns of the resource URIs that the LLM may read; empty = none.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mcpclient",
            name="allowed_tools",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Glob patterns of the tool names to offer the LLM; empty = all tools the server advertises.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mcpclient",
            name="command",
            field=models.CharField(
                blank=True,
                help_text="Reserved for the stdio transport, which is not supported.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mcpclient",
            name="credentials",
            field=models.ForeignKey(
                blank=True,
                help_text="The Secret containing the credential. Required unless auth_type is none.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="secret.secret",
            ),
        ),
        migrations.AlterField(
            model_name="mcpclient",
            name="endpoint_url",
            field=models.URLField(
                blank=True,
                help_text="The https URL of the MCP server's endpoint.",
                max_length=2048,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mcpclient",
            name="priority",
            field=models.PositiveSmallIntegerField(
                default=100,
                help_text="The order in which an LLMClient's MCPClients are offered to the LLM; lower runs first.",
            ),
        ),
        migrations.AlterField(
            model_name="mcpclient",
            name="transport",
            field=models.CharField(
                blank=True,
                choices=[
                    ("stdio", "Stdio (local subprocess)"),
                    ("sse", "Server-Sent Events"),
                    ("http", "Streamable HTTP"),
                ],
                default="http",
                max_length=16,
                null=True,
            ),
        ),
        migrations.RunPython(copy_config, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="mcpclient",
            name="config",
        ),
    ]
