# pylint: disable=wrong-import-position
"""Test STMPT Email Helper."""


# our stuff
from smarter.lib.unittest.base_classes import SmarterTestBase

from ..helpers.email_helpers import email_helper


class TestSMTPEmail(SmarterTestBase):
    """Test STMPT Email Helper."""

    def test_email_send(self):
        """test that we can send an email."""

        body = (
            "This is a plain text email test generated by Python unit tests in "
            "https://github.com/smarter-sh/smarter. These tests run within "
            "CI/(CD) pipelines that are automatically invoked for various reasons. "
            "If you received this email, it means that the email helper is working as expected. "
            "If you have any questions, please contact us at support@smarter.sh."
        )
        email_helper.send_email(
            subject="CI/CD unit test: email helper", body=body, to="querium.co@gmail.com", html=False, from_email=None
        )
