# pylint: disable=wrong-import-position
"""Test STMPT Email Helper."""

from smarter.common.const import SMARTER_CUSTOMER_SUPPORT_EMAIL
from smarter.common.helpers.email_helpers import email_helper

# our stuff
from smarter.lib.unittest.base_classes import SmarterTestBase


class TestSMTPEmail(SmarterTestBase):
    """Test STMPT Email Helper."""

    def test_email_send(self):
        """test that we can send an email."""

        body = (
            "This is a plain text email test generated by Python unit tests in "
            "https://github.com/smarter-sh/smarter. These tests run within "
            "CI/(CD) pipelines that are automatically invoked for various reasons. "
            "If you received this email, it means that the email helper is working as expected. "
            f"If you have any questions, please contact us at {SMARTER_CUSTOMER_SUPPORT_EMAIL}."
        )
        email_helper.send_email(
            subject="CI/CD unit test: email helper", body=body, to="lpm0073@gmail.com", html=False, from_email=None
        )
