# pylint: disable=all
# Generated by Django 5.2.7 on 2026-01-25 15:29

import django.core.validators
import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models

import smarter.lib.django.model_helpers
import smarter.lib.django.validators
import smarter.lib.json


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name in camelCase, e.g., 'apiKey', no special characters.",
                        max_length=255,
                        validators=[
                            smarter.lib.django.validators.SmarterValidator.validate_snake_case,
                            smarter.lib.django.model_helpers.validate_no_spaces,
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="A brief description of this resource. Be verbose, but not too verbose.",
                    ),
                ),
                ("version", models.CharField(default="1.0.0", max_length=255)),
                (
                    "annotations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        encoder=smarter.lib.json.SmarterJSONEncoder,
                        help_text="Key-value pairs for annotating this resource.",
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        blank=True,
                        default="9999-9999-9999",
                        max_length=255,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Account number must be entered in the format: '9999-9999-9999'.",
                                regex="^\\d{4}-\\d{4}-\\d{4}$",
                            )
                        ],
                    ),
                ),
                (
                    "is_default_account",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if this is the default account for the organization. Only one account should be marked as default.",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("address1", models.CharField(blank=True, max_length=255, null=True)),
                ("address2", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                ("state", models.CharField(blank=True, max_length=255, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        default="USA",
                        help_text="ISO 3166 country code.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        default="EN",
                        help_text="BCP 47 language tag, e.g., 'en-US'.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        blank=True,
                        help_text=" IANA timezone name, e.g., 'America/New_York'.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        default="USD",
                        help_text="ISO 4217 currency code.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates whether the account is active. Inactive accounts cannot be used for billing or resource management, nor hosting Provider apis.",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="Tags for categorizing and organizing this resource.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "verbose_name": "Account",
                "verbose_name_plural": "Accounts",
            },
        ),
        migrations.CreateModel(
            name="Charge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "session_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("metaai", "Meta AI"),
                            ("googleai", "Google AI"),
                        ],
                        default="openai",
                        max_length=255,
                    ),
                ),
                (
                    "charge_type",
                    models.CharField(
                        choices=[
                            ("completion", "Prompt Completion"),
                            ("plugin", "Plugin"),
                            ("tool", "Tool"),
                        ],
                        default="completion",
                        max_length=20,
                    ),
                ),
                ("prompt_tokens", models.IntegerField()),
                ("completion_tokens", models.IntegerField()),
                ("total_tokens", models.IntegerField()),
                ("model", models.CharField(max_length=255)),
                ("reference", models.CharField(max_length=255)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charge",
                        to="account.account",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charge",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LLMPrices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("charge_type", models.CharField(max_length=20)),
                ("provider", models.CharField(max_length=255)),
                ("model", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=6, max_digits=10)),
            ],
            options={
                "unique_together": {("charge_type", "provider", "model")},
            },
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("stripe_id", models.CharField(max_length=255)),
                ("card_type", models.CharField(max_length=255)),
                ("card_last_4", models.CharField(max_length=4)),
                ("card_exp_month", models.CharField(max_length=2)),
                ("card_exp_year", models.CharField(max_length=4)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods",
                        to="account.account",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name in camelCase, e.g., 'apiKey', no special characters.",
                        max_length=255,
                        validators=[
                            smarter.lib.django.validators.SmarterValidator.validate_snake_case,
                            smarter.lib.django.model_helpers.validate_no_spaces,
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="A brief description of this resource. Be verbose, but not too verbose.",
                    ),
                ),
                ("version", models.CharField(default="1.0.0", max_length=255)),
                (
                    "annotations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        encoder=smarter.lib.json.SmarterJSONEncoder,
                        help_text="Key-value pairs for annotating this resource.",
                    ),
                ),
                (
                    "is_test",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if this profile is used for unit testing purposes.",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_profiles",
                        to="account.account",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="Tags for categorizing and organizing this resource.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "account")},
            },
        ),
        migrations.CreateModel(
            name="AccountContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if this contact is the primary contact for the account. Only one contact can be primary per account.",
                    ),
                ),
                (
                    "is_test",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if this contact is used for unit testing purposes.",
                    ),
                ),
                (
                    "welcomed",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if a welcome email has been sent to this contact.",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="account.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Account Contact",
                "verbose_name_plural": "Account Contacts",
                "unique_together": {("account", "email")},
            },
        ),
        migrations.CreateModel(
            name="DailyBillingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("metaai", "Meta AI"),
                            ("googleai", "Google AI"),
                        ],
                        max_length=255,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "charge_type",
                    models.CharField(
                        choices=[
                            ("completion", "Prompt Completion"),
                            ("plugin", "Plugin"),
                            ("tool", "Tool"),
                        ],
                        max_length=20,
                    ),
                ),
                ("prompt_tokens", models.IntegerField()),
                ("completion_tokens", models.IntegerField()),
                ("total_tokens", models.IntegerField()),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_billing_records",
                        to="account.account",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_billing_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("account", "user", "provider", "date")},
            },
        ),
        migrations.CreateModel(
            name="Secret",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name in camelCase, e.g., 'apiKey', no special characters.",
                        max_length=255,
                        validators=[
                            smarter.lib.django.validators.SmarterValidator.validate_snake_case,
                            smarter.lib.django.model_helpers.validate_no_spaces,
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="A brief description of this resource. Be verbose, but not too verbose.",
                    ),
                ),
                ("version", models.CharField(default="1.0.0", max_length=255)),
                (
                    "annotations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        encoder=smarter.lib.json.SmarterJSONEncoder,
                        help_text="Key-value pairs for annotating this resource.",
                    ),
                ),
                (
                    "last_accessed",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Timestamp of the last time the secret was accessed.",
                        null=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp indicating when the secret expires. If null, the secret does not expire.",
                        null=True,
                    ),
                ),
                (
                    "encrypted_value",
                    models.BinaryField(help_text="Read-only encrypted representation of the secret's value."),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="Tags for categorizing and organizing this resource.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        help_text="Reference to the UserProfile associated with this secret.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secrets",
                        to="account.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Secret",
                "verbose_name_plural": "Secrets",
                "unique_together": {("user_profile", "name")},
            },
        ),
    ]
