# -*- coding: utf-8 -*-
# pylint: disable=C0114,C0115
# Generated by Django 5.0.2 on 2024-02-18 20:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account_number",
                    models.CharField(
                        default="default_value",
                        max_length=255,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Account number must be entered in the format: '9999-9999-9999'.",
                                regex="^\\d{4}-\\d{4}-\\d{4}",
                            )
                        ],
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Smarter Account",
                "verbose_name_plural": "Smarter Account",
            },
        ),
        migrations.CreateModel(
            name="PaymentMethodModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("stripe_id", models.CharField(max_length=255)),
                ("card_type", models.CharField(max_length=255)),
                ("card_last_4", models.CharField(max_length=4)),
                ("card_exp_month", models.CharField(max_length=2)),
                ("card_exp_year", models.CharField(max_length=4)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods",
                        to="account.account",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="users", to="account.account"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "account")},
            },
        ),
    ]
