# Generated by Django 5.2.10 on 2026-01-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profile_image_url",
            field=models.URLField(
                blank=True,
                help_text="URL to the user's profile image, provided via oauth.",
                null=True,
            ),
        ),
    ]
