# Generated by Django 5.1.3 on 2025-01-17 17:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="charge",
            name="provider",
            field=models.CharField(
                choices=[
                    ("openai", "OpenAI"),
                    ("metaai", "Meta AI"),
                    ("googleai", "Google AI"),
                ],
                default="openai",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="account_number",
            field=models.CharField(
                blank=True,
                default="9999-9999-9999",
                max_length=255,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Account number must be entered in the format: '9999-9999-9999'.",
                        regex="^\\d{4}-\\d{4}-\\d{4}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="address1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="address2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="country",
            field=models.CharField(blank=True, default="USA", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="currency",
            field=models.CharField(blank=True, default="USD", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="language",
            field=models.CharField(blank=True, default="EN", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="phone_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="state",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="timezone",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="LLMPrices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("charge_type", models.CharField(max_length=20)),
                ("provider", models.CharField(max_length=255)),
                ("model", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=6, max_digits=10)),
            ],
            options={
                "unique_together": {("charge_type", "provider", "model")},
            },
        ),
        migrations.CreateModel(
            name="DailyBillingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("metaai", "Meta AI"),
                            ("googleai", "Google AI"),
                        ],
                        max_length=255,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "charge_type",
                    models.CharField(
                        choices=[
                            ("completion", "Prompt Completion"),
                            ("plugin", "Plugin"),
                            ("tool", "Tool"),
                        ],
                        max_length=20,
                    ),
                ),
                ("prompt_tokens", models.IntegerField()),
                ("completion_tokens", models.IntegerField()),
                ("total_tokens", models.IntegerField()),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_billing_records",
                        to="account.account",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_billing_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("account", "user", "provider", "date")},
            },
        ),
    ]
