# pylint: disable=all
# Generated by Django 6.0.5 on 2026-06-24 14:04

from decimal import Decimal

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models

import smarter.common.mixins.helper_mixin
import smarter.lib.django.validators
import smarter.lib.json


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AggregatedCharges",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("year", models.SmallIntegerField()),
                ("month", models.SmallIntegerField()),
                ("day", models.SmallIntegerField()),
                ("hour", models.SmallIntegerField()),
                (
                    "resource_locator",
                    models.CharField(
                        db_index=True,
                        help_text="The TimestampedModel.resource_locator of the resource that this charge is associated with.",
                        max_length=255,
                    ),
                ),
                (
                    "charge_type",
                    models.CharField(
                        choices=[
                            ("completion", "Prompt Completion"),
                            ("plugin", "Plugin"),
                            ("tool", "Tool"),
                        ],
                        default="completion",
                        max_length=20,
                    ),
                ),
                ("records", models.IntegerField()),
                ("prompt_tokens", models.IntegerField()),
                ("completion_tokens", models.IntegerField()),
                ("total_tokens", models.IntegerField()),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=5, default=Decimal("0"), max_digits=10),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, smarter.common.mixins.helper_mixin.SmarterHelperMixin),
        ),
        migrations.CreateModel(
            name="ResourceConstraint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "resource_locator",
                    models.CharField(
                        db_index=True,
                        help_text="The TimestampedModel.resource_locator of the resource that this constraint is associated with.",
                        max_length=255,
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="The duration of the budget in billing periods. 0 means no limit.",
                    ),
                ),
                (
                    "periodic_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="The maximum cost that can be incurred in this budget in a billing period.",
                        max_digits=10,
                    ),
                ),
                (
                    "absolute_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="The maximum cost that can be incurred in this budget in total.",
                        max_digits=10,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, smarter.common.mixins.helper_mixin.SmarterHelperMixin),
        ),
        migrations.AddField(
            model_name="charge",
            name="resource_locator",
            field=models.CharField(
                db_index=True,
                default="abc123",
                help_text="The TimestampedModel.resource_locator of the resource that this charge is associated with.",
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="charge",
            name="total_cost",
            field=models.DecimalField(decimal_places=8, default=Decimal("0"), max_digits=10),
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name in camelCase, e.g., 'apiKey', no special characters.",
                        max_length=255,
                        validators=[
                            smarter.lib.django.validators.SmarterValidator.validate_snake_case,
                            smarter.lib.django.validators.SmarterValidator.validate_no_spaces,
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="A brief description of this resource. Be verbose, but not too verbose.",
                        null=True,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        default="1.0.0",
                        help_text="Semantic version in the format MAJOR.MINOR.PATCH, e.g., '1.0.0'.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "annotations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        encoder=smarter.lib.json.SmarterJSONEncoder,
                        help_text="Key-value pairs for annotating this resource.",
                        null=True,
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="The duration of the budget in billing periods. 0 means no limit.",
                    ),
                ),
                (
                    "periodic_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="The maximum cost that can be incurred in this budget in a billing period.",
                        max_digits=10,
                    ),
                ),
                (
                    "absolute_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="The maximum cost that can be incurred in this budget in total.",
                        max_digits=10,
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="Tags for categorizing and organizing this resource.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, smarter.common.mixins.helper_mixin.SmarterHelperMixin),
        ),
        migrations.CreateModel(
            name="ResourceLock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "resource_locator",
                    models.CharField(
                        db_index=True,
                        help_text="The TimestampedModel.resource_locator of the resource that this lock is associated with.",
                        max_length=255,
                    ),
                ),
                (
                    "expiration_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="The date and time when this lock will expire. If null, the lock will not expire until it is manually removed.",
                        null=True,
                    ),
                ),
                (
                    "resource_constraint",
                    models.ForeignKey(
                        help_text="The resource constraint that this lock is associated with.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locks",
                        to="account.resourceconstraint",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, smarter.common.mixins.helper_mixin.SmarterHelperMixin),
        ),
        migrations.DeleteModel(
            name="DailyBillingRecord",
        ),
    ]
