# pylint: disable=all
# Generated by Django 6.0.5 on 2026-06-27 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_resourceconstraint_remove_charge_model_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aggregatedcharges",
            options={
                "verbose_name": "Aggregated Charges",
                "verbose_name_plural": "Aggregated Charges",
            },
        ),
    ]
