# Generated by Django 5.1.3 on 2025-01-20 02:15
# pylint: disable=missing-module-docstring,missing-function-docstring,missing-class-docstring

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_charge_provider_alter_account_account_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="charge",
            name="session_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
