# Generated by Django 6.0.8 on 2026-10-02 02:22

from decimal import Decimal

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_aggregatedcharges_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="action",
            field=models.CharField(
                choices=[("block", "Block further charges"), ("warn", "Warn only")],
                default="block",
                help_text="What happens when a limit is reached: block further charges, or only send the budget_exceeded signal.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="message",
            field=models.TextField(
                blank=True,
                default="",
                help_text="What people are told when this budget blocks their request, e.g. in the chat window. Empty means a description of the limit that was reached.",
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="period",
            field=models.CharField(
                choices=[
                    ("hour", "Hour"),
                    ("day", "Day"),
                    ("week", "Week"),
                    ("month", "Month"),
                ],
                default="month",
                help_text="The billing period of the periodic limit, and of the duration.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="unit",
            field=models.CharField(
                choices=[("cost", "Cost (USD)"), ("tokens", "Tokens")],
                default="cost",
                help_text="What the limits measure: cost in USD, or total tokens.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="warning_threshold",
            field=models.PositiveSmallIntegerField(
                default=80,
                help_text="The percentage of a limit at which the budget_warning signal is sent, once per billing period. 0 means never.",
            ),
        ),
        migrations.AddField(
            model_name="resourceconstraint",
            name="budget",
            field=models.ForeignKey(
                help_text="The budget that is enforced on the resource.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="constraints",
                to="account.budget",
            ),
        ),
        migrations.AddField(
            model_name="resourceconstraint",
            name="exceeded_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the budget_exceeded signal was last sent for this resource.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="resourceconstraint",
            name="is_active",
            field=models.BooleanField(default=True, help_text="Whether the budget is enforced."),
        ),
        migrations.AddField(
            model_name="resourceconstraint",
            name="start_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="When the budget began to apply to the resource. The duration and the absolute limit count from here.",
            ),
        ),
        migrations.AddField(
            model_name="resourceconstraint",
            name="warned_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the budget_warning signal was last sent for this resource.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="resourcelock",
            name="reason",
            field=models.TextField(blank=True, default="", help_text="Which limit was reached."),
        ),
        migrations.AlterField(
            model_name="aggregatedcharges",
            name="charge_type",
            field=models.CharField(
                choices=[
                    ("completion", "Prompt Completion"),
                    ("plugin", "Plugin"),
                    ("tool", "Tool"),
                    ("compute", "Compute"),
                ],
                default="completion",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="aggregatedcharges",
            name="total_cost",
            field=models.DecimalField(decimal_places=5, default=Decimal("0"), max_digits=18),
        ),
        migrations.AlterField(
            model_name="budget",
            name="absolute_limit",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="The maximum cost or tokens that can be incurred in total, from when it is attached. 0 means no limit.",
                max_digits=14,
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="duration",
            field=models.PositiveIntegerField(
                default=0,
                help_text="The duration of the budget in billing periods, from when it is attached. Afterwards, the resource is locked. 0 means no limit.",
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="periodic_limit",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="The maximum cost or tokens that can be incurred in a billing period. 0 means no limit.",
                max_digits=14,
            ),
        ),
        migrations.AlterField(
            model_name="charge",
            name="charge_type",
            field=models.CharField(
                choices=[
                    ("completion", "Prompt Completion"),
                    ("plugin", "Plugin"),
                    ("tool", "Tool"),
                    ("compute", "Compute"),
                ],
                default="completion",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="charge",
            name="total_cost",
            field=models.DecimalField(decimal_places=8, default=Decimal("0"), max_digits=18),
        ),
        migrations.RemoveField(
            model_name="resourceconstraint",
            name="absolute_limit",
        ),
        migrations.RemoveField(
            model_name="resourceconstraint",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="resourceconstraint",
            name="periodic_limit",
        ),
        migrations.AlterUniqueTogether(
            name="resourceconstraint",
            unique_together={("budget", "resource_locator")},
        ),
    ]
