# Generated by Django 5.1.3 on 2025-01-28 19:49
# pylint: disable=missing-module-docstring,missing-function-docstring,missing-class-docstring

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_charge_session_key"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="accountcontact",
            unique_together={("account", "email")},
        ),
    ]
