# Generated by Django 5.1.3 on 2025-02-14 13:45
# pylint: disable=missing-module-docstring,missing-function-docstring,missing-class-docstring

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_alter_accountcontact_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_default_account",
            field=models.BooleanField(default=False),
        ),
    ]
