# Generated by Django 6.0.8 on 2026-10-02 02:42

from django.db import migrations, models

import smarter.lib.django.validators


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_budget_enforcement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="duration",
            field=models.PositiveIntegerField(
                default=0,
                help_text="The duration of the budget in billing periods, from when it is attached. Afterwards, the budget no longer applies. 0 means no limit.",
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="name",
            field=models.CharField(
                help_text="The budget's name, in snake_case. Unique: manifests refer to budgets by name.",
                max_length=255,
                unique=True,
                validators=[
                    smarter.lib.django.validators.SmarterValidator.validate_snake_case,
                    smarter.lib.django.validators.SmarterValidator.validate_no_spaces,
                ],
            ),
        ),
    ]
