# Generated by Django 5.1.7 on 2025-04-23 15:39
# pylint: disable=missing-module-docstring,missing-function-docstring,missing-class-docstring

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_alter_userprofile_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Secret",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "last_accessed",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of the last time the secret was accessed.",
                        null=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp indicating when the secret expires. If null, the secret does not expire.",
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the secret, used for identification purposes.",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of the secret.",
                        null=True,
                    ),
                ),
                (
                    "encrypted_value",
                    models.BinaryField(help_text="Read-only encrypted representation of the secret's value."),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        help_text="Reference to the UserProfile associated with this secret.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secrets",
                        to="account.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Secret",
                "verbose_name_plural": "Secret",
                "unique_together": {("user_profile", "name")},
            },
        ),
    ]
