# Generated by Django 5.1.7 on 2025-04-27 14:11
# pylint: disable=missing-module-docstring,missing-function-docstring,missing-class-docstring

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_secrets"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="secret",
            options={"verbose_name": "Secret", "verbose_name_plural": "Secrets"},
        ),
        migrations.AlterField(
            model_name="secret",
            name="last_accessed",
            field=models.DateTimeField(
                blank=True, editable=False, help_text="Timestamp of the last time the secret was accessed.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="secret",
            name="name",
            field=models.CharField(
                help_text="Name of the secret in camelCase, e.g., 'apiKey', no special characters.", max_length=255
            ),
        ),
    ]
