# Generated by Django 5.2.7 on 2025-12-12 13:46
# pylint: disable=missing-module-docstring,missing-function-docstring,missing-class-docstring

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0010_account_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="is_default_account",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if this is the default account for the organization. Only one account should be marked as default.",
            ),
        ),
        migrations.AlterField(
            model_name="accountcontact",
            name="is_primary",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if this contact is the primary contact for the account. Only one contact can be primary per account.",
            ),
        ),
        migrations.AlterField(
            model_name="accountcontact",
            name="is_test",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if this contact is used for unit testing purposes.",
            ),
        ),
        migrations.AlterField(
            model_name="accountcontact",
            name="welcomed",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if a welcome email has been sent to this contact.",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="is_test",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if this profile is used for unit testing purposes.",
            ),
        ),
    ]
