# pylint: disable=missing-module-docstring,missing-function-docstring,missing-class-docstring
# Generated by Django 5.2.7 on 2025-12-27 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0013_userprofile_annotations_userprofile_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="secret",
            name="account",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="account.account",
            ),
            preserve_default=False,
        ),
    ]
