# pylint: disable=missing-module-docstring,missing-function-docstring,missing-class-docstring
# Generated by Django 5.2.7 on 2025-12-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0016_alter_account_name_alter_secret_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="country",
            field=models.CharField(
                blank=True,
                default="USA",
                help_text="ISO 3166 country code.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="currency",
            field=models.CharField(
                blank=True,
                default="USD",
                help_text="ISO 4217 currency code.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="language",
            field=models.CharField(
                blank=True,
                default="EN",
                help_text="BCP 47 language tag, e.g., 'en-US'.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="timezone",
            field=models.CharField(
                blank=True,
                help_text=" IANA timezone name, e.g., 'America/New_York'.",
                max_length=255,
                null=True,
            ),
        ),
    ]
