# pylint: disable=all
# Generated by Django 6.0.5 on 2026-07-07 19:37

import django.core.validators
import django.db.models.deletion
import taggit.managers
from django.db import migrations, models

import smarter.common.mixins.helper_mixin
import smarter.lib.django.validators
import smarter.lib.json


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0003_alter_aggregatedcharges_options"),
        ("llm_client", "0002_initial"),
        ("prompt", "0001_initial"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Orchestrator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name in camelCase, e.g., 'apiKey', no special characters.",
                        max_length=255,
                        validators=[
                            smarter.lib.django.validators.SmarterValidator.validate_snake_case,
                            smarter.lib.django.validators.SmarterValidator.validate_no_spaces,
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="A brief description of this resource. Be verbose, but not too verbose.",
                        null=True,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        default="1.0.0",
                        help_text="Semantic version in the format MAJOR.MINOR.PATCH, e.g., '1.0.0'.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "annotations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        encoder=smarter.lib.json.SmarterJSONEncoder,
                        help_text="Key-value pairs for annotating this resource.",
                        null=True,
                    ),
                ),
                (
                    "strategy",
                    models.CharField(
                        choices=[
                            ("sequential", "Sequential"),
                            ("parallel", "Parallel"),
                            ("supervisor", "Supervisor / Worker"),
                            ("router", "Router"),
                            ("voting", "Voting / Consensus"),
                            ("debate", "Debate"),
                        ],
                        default="sequential",
                        help_text="Coordination pattern used to sequence/parallelize member LLMClients.",
                        max_length=32,
                    ),
                ),
                (
                    "max_iterations",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Upper bound on orchestration loop iterations; a runaway guard.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="Tags for categorizing and organizing this resource.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Orchestrators",
            },
            bases=(models.Model, smarter.common.mixins.helper_mixin.SmarterHelperMixin),
        ),
        migrations.CreateModel(
            name="OrchestrationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "objective",
                    models.TextField(help_text="Natural-language statement of the agentic objective for this run."),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("max_iterations_exceeded", "Max Iterations Exceeded"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                (
                    "result",
                    models.JSONField(
                        blank=True,
                        help_text="Final output/artifact produced by the run, if any.",
                        null=True,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("iteration_count", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "orchestrator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="orchestrator.orchestrator",
                    ),
                ),
            ],
            options={
                "verbose_name": "Orchestration Run",
                "verbose_name_plural": "Orchestration Runs",
                "ordering": ["-created_at"],
            },
            bases=(models.Model, smarter.common.mixins.helper_mixin.SmarterHelperMixin),
        ),
        migrations.CreateModel(
            name="OrchestratorHarness",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("planner", "Planner"),
                            ("executor", "Executor"),
                            ("critic", "Critic"),
                            ("router", "Router"),
                            ("summarizer", "Summarizer"),
                            ("tool_caller", "Tool Caller"),
                        ],
                        default="executor",
                        max_length=32,
                    ),
                ),
                (
                    "execution_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Relative ordering for sequential/supervisor strategies. Ignored for parallel/voting.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Per-membership overrides (e.g. temperature, system prompt fragment, tool allowlist).",
                    ),
                ),
                (
                    "llm_client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orchestrator_memberships",
                        to="llm_client.llmclient",
                    ),
                ),
                (
                    "orchestrator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="harnesses",
                        to="orchestrator.orchestrator",
                    ),
                ),
            ],
            options={
                "verbose_name": "Orchestrator Harness",
                "verbose_name_plural": "Orchestrator Harnesses",
                "ordering": ["execution_order"],
            },
            bases=(models.Model, smarter.common.mixins.helper_mixin.SmarterHelperMixin),
        ),
        migrations.AddField(
            model_name="orchestrator",
            name="llm_clients",
            field=models.ManyToManyField(
                help_text="LLMClients (Harnesses) available to this Orchestrator.",
                related_name="orchestrators",
                through="orchestrator.OrchestratorHarness",
                to="llm_client.llmclient",
            ),
        ),
        migrations.CreateModel(
            name="OrchestrationStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(help_text="Ordinal position of this step within the run."),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="succeeded",
                        max_length=16,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Orchestration-level failure reason (e.g. bad handoff), distinct from any error on the execution record itself.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "prompt",
                    models.ForeignKey(
                        help_text="The underlying LLMClient execution record (input/output, tokens, latency). OrchestrationStep only adds the run/sequence context on top of it.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orchestration_steps",
                        to="prompt.prompt",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="orchestrator.orchestrationrun",
                    ),
                ),
                (
                    "harness",
                    models.ForeignKey(
                        help_text="Which Orchestrator/LLMClient membership executed this step.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="orchestrator.orchestratorharness",
                    ),
                ),
            ],
            options={
                "verbose_name": "Orchestration Step",
                "verbose_name_plural": "Orchestration Steps",
                "ordering": ["run", "sequence"],
            },
            bases=(models.Model, smarter.common.mixins.helper_mixin.SmarterHelperMixin),
        ),
        migrations.AddIndex(
            model_name="orchestrationrun",
            index=models.Index(fields=["orchestrator", "status"], name="orchestrato_orchest_79d21a_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="orchestratorharness",
            unique_together={("orchestrator", "llm_client")},
        ),
        migrations.AlterUniqueTogether(
            name="orchestrator",
            unique_together={("user_profile", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="orchestrationstep",
            unique_together={("run", "sequence")},
        ),
    ]
