apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Values.app.name }}-bastion"
  namespace: "{{ .Values.namespace }}"
spec:
  containers:
  - name: "{{ .Values.app.name }}-bastion"
    image: ubuntu:latest
    command: ["/bin/bash", "-c", "while true; do sleep 3600; done"]
    resources:
      requests:
        cpu: 10m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 256Mi
