# -----------------------------------------------------------------------------------
# ConfigMap Manifest for MySQL Backup Script
#
# This file defines a ConfigMap containing the backup-to-s3.sh script for MySQL backups.
#
# - Maintainer: <your team/contact>
# - Purpose: Provides a shell script to back up the MySQL database and upload it to S3.
# - Usage: Mounted into backup Jobs or Pods; values are set in values.yaml.
# - Notes: Update the script or S3 path as needed for your environment.
#
# Note:
# The app.kubernetes.io/application-group label is used to identify pods to Calico
# and kubernetes_network_policy_v1 resources in order to allow pod-level communication
# between backing services. If the label is missing then the network policies are
# assured to PREVENT communication between this ConfigMap and other resources.
# -----------------------------------------------------------------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: "{{ .Values.global.appName }}"
    meta.helm.sh/release-namespace: "{{ .Values.namespace }}"
    meta.helm.sh/application-version: "{{ .Chart.Version }}"
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/name: "{{ .Values.global.appName }}"
    app.kubernetes.io/application-group: "{{ .Values.global.appName }}"
  namespace: "{{ .Values.namespace }}"
  name: mysql-backup-script
data:
  backup-to-s3.sh: |
    #!/bin/bash
    ################################################################################
    # The Smarter Project - https://smarter.sh
    # backup-to-s3.sh
    #
    # This script performs a backup of the MySQL database and uploads it to S3.
    ################################################################################
    set -e

    BACKUP_FILENAME="${SMARTER_MYSQL_DATABASE}-$(date +%Y%m%dT%H%M%S)"

    echo "Starting MySQL backup for database: $SMARTER_MYSQL_DATABASE"
    mysqldump -h "$SMARTER_MYSQL_HOST" -u "$SMARTER_MYSQL_ROOT_USERNAME" -p"$SMARTER_MYSQL_ROOT_PASSWORD" --databases  "$SMARTER_MYSQL_DATABASE" --add-drop-database --add-drop-table --routines --events --triggers --single-transaction --quick --lock-tables=false > ${BACKUP_FILENAME}.sql

    echo "Compressing backup file: ${BACKUP_FILENAME}.sql"
    tar -czvf ${BACKUP_FILENAME}.tar.gz ${BACKUP_FILENAME}.sql

    echo "Uploading backup file to S3: ${BACKUP_FILENAME}.tar.gz"
    aws s3 cp ${BACKUP_FILENAME}.tar.gz s3://ubc.smarter.sh/backups/sql/${BACKUP_FILENAME}.tar.gz
    rm ${BACKUP_FILENAME}.sql
    rm ${BACKUP_FILENAME}.tar.gz

    echo "MySQL backup completed and uploaded to S3: ${BACKUP_FILENAME}.tar.gz"
