apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.app.name }}-bastion"
  namespace: "{{ .Values.namespace }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Values.app.name }}-bastion"
  template:
    metadata:
      labels:
        app: "{{ .Values.app.name }}-bastion"
    spec:
      containers:
      - name: "{{ .Values.app.name }}-bastion"
        image: debian:bullseye-slim
        command: ["/bin/bash", "-c", "apt-get update && apt-get install -y mariadb-client && while true; do sleep 3600; done"]
        resources:
          requests:
            cpu: 5m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 256Mi
