###############################################################################
# Bastion Pod Deployment
#
# This deployment creates a single pod that serves as a bastion shell
# for users to perform administrative tasks and to connect to the MySQL database
# which is only accessible from within the cluster. The pod is based on a
# lightweight Debian image with minimal tools installed, including the
# MariaDB MySQL client.
#
# setup:
# -------------------------------------
# - installs the MariaDB MySQL client
# - creates a welcome message with usage instructions and environment variable
#   information
# - configures the welcome message to be displayed whenever a user connects to
#   the pod
# - keeps the pod running indefinitely to allow users to connect and use the shell
###############################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.app.name }}-bastion"
  namespace: "{{ .Values.namespace }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Values.app.name }}-bastion"
  template:
    metadata:
      labels:
        app: "{{ .Values.app.name }}-bastion"
    spec:
      affinity:
        {{- toYaml .Values.global.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.global.tolerations | nindent 8 }}
      volumes:
        - name: debian-setup-script
          configMap:
            name: debian-setup-script
        - name: debian-welcome-banner
          configMap:
            name: debian-welcome-banner
        - name: mysql-backup-script
          configMap:
            name: mysql-backup-script
      containers:
        - name: "{{ .Values.app.name }}-bastion"
          image: debian:bullseye-slim
          command:
            - /bin/bash
            - -c
            - |
                set -e

                chmod +x /setup/install.sh && /setup/install.sh
                chmod +x /welcome/install.sh && /welcome/install.sh
                chmod +x /backup/backup-to-s3.sh

                echo "The Smarter Bastion Server is ready to use!"

                while true; do sleep 3600; done
          imagePullPolicy: {{ .Values.global.image.pullPolicy | default "IfNotPresent" }}
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 512Mi
            volumeMounts:
              - name: debian-setup-script
                mountPath: /setup
              - name: debian-welcome-banner
                mountPath: /welcome
              - name: mysql-backup-script
                mountPath: /backup

          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- range $env := .Values.app.env }}
            - name: {{ $env.name }}
              value: {{ $env.value | quote }}
            {{- end }}
