apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.app.name }}-bastion"
  namespace: "{{ .Values.namespace }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Values.app.name }}-bastion"
  template:
    metadata:
      labels:
        app: "{{ .Values.app.name }}-bastion"
    spec:
      affinity:
        {{- toYaml .Values.global.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.global.tolerations | nindent 8 }}
      containers:
        - name: "{{ .Values.app.name }}-bastion"
          image: debian:bullseye-slim
          command:
            - /bin/bash
            - -c
            - |
              apt-get update && apt-get install -y mariadb-client && \
              cat << 'EOF' > /etc/profile.d/welcome.sh
              echo ''
              echo '********************************************************************************'
              echo '*   Welcome to Smarter Bastion Shell!                                          *'
              echo '*   Pleases note the following:                                                *'
              echo '*   - mariadb mysql client is pre-installed.                                   *'
              echo '*   - all smarter pod environment variables are available.                     *'
              echo '*     see https://artifacthub.io/packages/helm/project-smarter/smarter         *'
              echo '*                                                                              *'
              echo '*   example usage:                                                             *'
              echo '*   $ mysql -h "$SMARTER_MYSQL_HOST" -u "$SMARTER_MYSQL_ROOT_USERNAME" -p"$SMARTER_MYSQL_ROOT_PASSWORD" "$SMARTER_MYSQL_DATABASE"'
              echo '********************************************************************************'
              echo ''
              EOF
              chmod +x /etc/profile.d/welcome.sh && while true; do sleep 3600; done
          imagePullPolicy: {{ .Values.global.image.pullPolicy | default "IfNotPresent" }}
          resources:
            requests:
              cpu: 5m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 256Mi
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- range $env := .Values.app.env }}
            - name: {{ $env.name }}
              value: {{ $env.value | quote }}
            {{- end }}
