apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "{{ .Values.app.name }}-worker"
  namespace: {{ .Values.namespace }}
  annotations:
    meta.helm.sh/release-name: {{ .Values.app.name }}
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
    meta.helm.sh/application-version: {{ .Chart.Version }}
  labels:
    App: {{ .Values.app.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "{{ .Values.app.name }}-worker"
  minReplicas: 1
  maxReplicas: {{ .Values.hpa.maxReplicas | default 25 }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.targetCPUUtilizationPercentage | default 75 }}
