apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-smarter-redis-wait"
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": hook-succeeded
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/name: "{{ .Release.Name }}-smarter-redis-wait"
spec:
  template:
    spec:
      containers:
        - name: wait-for-redis
          image: bitnami/kubectl:1.32.0
          command:
            - /bin/sh
            - -c
            - |
              until nc -zv smarter-redis-master 6379; do
                echo "Waiting for Redis to be ready..."
                sleep 5
              done
      restartPolicy: Never
