apiVersion: batch/v1
kind: CronJob
metadata:
  name: mysql-backup
spec:
  schedule: "0 2 * * *" # Every day at 2am UTC
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 86400  # Keeps the pod for 1 day (86400 seconds)
      template:
        spec:
          containers:
          - name: mysql-backup
            image: ubuntu:latest
            command:
              - /bin/bash
              - -c
              - |
                set -e
                apt-get update && \
                DEBIAN_FRONTEND=noninteractive apt-get install -y mariadb-client curl unzip && \
                ARCH=$(uname -m) && \
                if [ "$ARCH" = "aarch64" ]; then \
                  curl "https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip" -o "awscliv2.zip"; \
                else \
                  curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"; \
                fi && \
                unzip awscliv2.zip && \
                ./aws/install && \
                rm -rf awscliv2.zip aws && \
                chmod +x /backup/backup-to-s3.sh && \
                /backup/backup-to-s3.sh
            env:
{{- range $key, $value := .Values.env }}
              - name: {{ $key }}
                value: {{ $value | quote }}
{{- end }}
            volumeMounts:
              - name: backup-script
                mountPath: /backup
          restartPolicy: OnFailure
          volumes:
            - name: backup-script
              configMap:
                name: mysql-backup-script
