apiVersion: batch/v1
kind: CronJob
metadata:
  name: mysql-backup
spec:
  schedule: "0 2 * * *" # Every day at 2am UTC
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 86400  # Keeps the pod for 1 day (86400 seconds)
      template:
        spec:
          containers:
          - name: mysql-backup
            image: ubuntu:latest
            command:
              - /bin/bash
              - -c
              - |
                set -e

                chmod +x /setup/install.sh && /setup/install.sh
                chmod +x /backup/backup-to-s3.sh && /backup/backup-to-s3.sh
            env:
{{- range $key, $value := .Values.env }}
              - name: {{ $key }}
                value: {{ $value | quote }}
{{- end }}
            volumeMounts:
              - name: debian-setup-script
                mountPath: /setup
              - name: mysql-backup-script
                mountPath: /backup
          restartPolicy: OnFailure
          volumes:
            - name: debian-setup-script
              configMap:
                name: debian-setup-script
            - name: mysql-backup-script
              configMap:
                name: mysql-backup-script
