apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.redis.master.persistence.existingClaim }}
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-group
              operator: In
              values:
                - {{ .Values.appName }}
