apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.redis.master.persistence.existingClaim }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: {{ .Values.redis.master.persistence.existingClaim }}
  storageClassName: ""
