# -----------------------------------------------------------------------------------
# Purpose: Kubernetes Service Manifest for Smarter Application
#
# Note:
# The app.kubernetes.io/application-group label is used to identify pods to Calico
# and kubernetes_network_policy_v1 resources in order to allow pod-level communication
# between backing services. If the label is missing then the network policies are
# assured to PREVENT communication.
# -----------------------------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.global.appName }}"
  namespace: "{{ .Values.env.NAMESPACE }}"
  annotations:
    meta.helm.sh/release-name: "{{ .Values.global.appName }}"
    meta.helm.sh/release-namespace: "{{ .Values.namespace }}"
    meta.helm.sh/application-version: "{{ .Chart.Version }}"
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/name: "{{ .Values.global.appName }}-worker"
    app.kubernetes.io/application-group: "{{ .Values.global.appName }}"
spec:
  selector:
    app.kubernetes.io/name: "{{ .Values.global.appName }}"
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.targetPort }}
  sessionAffinity: None
  type: ClusterIP
