apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.app.name }}"
  namespace: "{{ .Values.env.NAMESPACE }}"
  annotations:
    meta.helm.sh/release-name: {{ .Values.app.name }}
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
    meta.helm.sh/application-version: {{ .Chart.Version }}
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/name: "{{ .Values.app.name }}-worker"
    app.kubernetes.io/application-group: {{ .Values.app.name }}
spec:
  selector:
    app.kubernetes.io/name: "{{ .Values.app.name }}"
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.targetPort }}
  sessionAffinity: None
  type: ClusterIP
