# pylint: disable=all
# Generated by Django 6.0.5 on 2026-07-07 19:37

import django.core.validators
import django.db.models.deletion
import taggit.managers
from django.db import migrations, models

import smarter.common.mixins.helper_mixin
import smarter.lib.django.validators
import smarter.lib.json


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0003_alter_aggregatedcharges_options"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMHost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name in camelCase, e.g., 'apiKey', no special characters.",
                        max_length=255,
                        validators=[
                            smarter.lib.django.validators.SmarterValidator.validate_snake_case,
                            smarter.lib.django.validators.SmarterValidator.validate_no_spaces,
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="A brief description of this resource. Be verbose, but not too verbose.",
                        null=True,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        default="1.0.0",
                        help_text="Semantic version in the format MAJOR.MINOR.PATCH, e.g., '1.0.0'.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "annotations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        encoder=smarter.lib.json.SmarterJSONEncoder,
                        help_text="Key-value pairs for annotating this resource.",
                        null=True,
                    ),
                ),
                (
                    "huggingface_repo_id",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'meta-llama/Meta-Llama-3-8B-Instruct'",
                        max_length=255,
                    ),
                ),
                (
                    "huggingface_revision",
                    models.CharField(
                        blank=True,
                        help_text="Commit SHA or tag pinned for reproducible deploys.",
                        max_length=64,
                    ),
                ),
                ("license", models.CharField(blank=True, max_length=100)),
                (
                    "model_architecture",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'llama', 'mistral', 'mixtral', 'qwen2'",
                        max_length=100,
                    ),
                ),
                (
                    "parameter_count",
                    models.BigIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("context_window", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "quantization",
                    models.CharField(
                        choices=[
                            ("none", "None (full precision)"),
                            ("fp16", "FP16"),
                            ("bf16", "BF16"),
                            ("int8", "INT8"),
                            ("int4", "INT4"),
                            ("gguf", "GGUF"),
                            ("awq", "AWQ"),
                            ("gptq", "GPTQ"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "embedding_dimensions",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Set only for embedding models.",
                        null=True,
                    ),
                ),
                ("supports_streaming", models.BooleanField(default=True)),
                ("supports_function_calling", models.BooleanField(default=False)),
                ("supports_vision", models.BooleanField(default=False)),
                (
                    "inference_engine",
                    models.CharField(
                        choices=[
                            ("vllm", "vLLM"),
                            ("tgi", "Text Generation Inference"),
                            ("ollama", "Ollama"),
                            ("llama_cpp", "llama.cpp"),
                            ("sglang", "SGLang"),
                            ("transformers", "Transformers (raw)"),
                            ("triton", "Triton Inference Server"),
                            ("custom", "Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "api_format",
                    models.CharField(
                        choices=[
                            ("openai_compatible", "OpenAI-compatible"),
                            ("huggingface", "Hugging Face Inference API"),
                            ("ollama_native", "Ollama native"),
                            ("custom", "Custom"),
                        ],
                        default="openai_compatible",
                        max_length=20,
                    ),
                ),
                (
                    "endpoint_url",
                    models.URLField(help_text="Base URL of the inference server."),
                ),
                ("api_key", models.CharField(blank=True, max_length=255)),
                (
                    "deployment_type",
                    models.CharField(
                        choices=[
                            ("docker", "Docker"),
                            ("kubernetes", "Kubernetes"),
                            ("bare_metal", "Bare metal"),
                            ("cloud_instance", "Cloud instance"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "cloud_provider",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("aws", "AWS"),
                            ("gcp", "GCP"),
                            ("azure", "Azure"),
                            ("on_prem", "On-prem"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("region", models.CharField(blank=True, max_length=50)),
                (
                    "instance_type",
                    models.CharField(blank=True, help_text="e.g. 'g5.2xlarge'", max_length=50),
                ),
                (
                    "gpu_type",
                    models.CharField(blank=True, help_text="e.g. 'A100-80GB'", max_length=50),
                ),
                ("gpu_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "vram_required_gb",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("downloading", "Downloading weights"),
                            ("deploying", "Deploying"),
                            ("active", "Active"),
                            ("degraded", "Degraded"),
                            ("inactive", "Inactive"),
                            ("error", "Error"),
                            ("deprecated", "Deprecated"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("health_check_url", models.URLField(blank=True)),
                ("last_health_check_at", models.DateTimeField(blank=True, null=True)),
                ("last_health_ok", models.BooleanField(blank=True, null=True)),
                (
                    "cost_per_hour",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
                ),
                (
                    "engine_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Engine-specific launch args, sampling defaults, etc.",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="Tags for categorizing and organizing this resource.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "LLMHosts",
                "unique_together": {("user_profile", "name")},
            },
            bases=(models.Model, smarter.common.mixins.helper_mixin.SmarterHelperMixin),
        ),
    ]
