# pylint: disable=all
# Generated by Django 6.0.5 on 2026-10-01 16:47
#
# Edited: LLMHostCompute and LLMHost.compute are folded in from a generated 0003.
# Edited: huggingface_repo_id and huggingface_revision are renamed, not dropped,
# to model_repository and model_revision, which keep any existing values.

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models

import smarter.common.mixins.helper_mixin
import smarter.lib.django.validators
import smarter.lib.json


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_aggregatedcharges_options"),
        ("llmhost", "0001_initial"),
        ("secret", "0001_initial"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="llmhost",
            name="api_key",
        ),
        migrations.RemoveField(
            model_name="llmhost",
            name="cloud_provider",
        ),
        migrations.RemoveField(
            model_name="llmhost",
            name="deployment_type",
        ),
        migrations.RemoveField(
            model_name="llmhost",
            name="engine_config",
        ),
        migrations.RenameField(
            model_name="llmhost",
            old_name="huggingface_repo_id",
            new_name="model_repository",
        ),
        migrations.RenameField(
            model_name="llmhost",
            old_name="huggingface_revision",
            new_name="model_revision",
        ),
        migrations.RemoveField(
            model_name="llmhost",
            name="region",
        ),
        migrations.RemoveField(
            model_name="llmhost",
            name="instance_type",
        ),
        migrations.AddField(
            model_name="llmhost",
            name="api_key_secret",
            field=models.ForeignKey(
                blank=True,
                help_text="The Smarter Secret with the API key that clients send as a Bearer token.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="llmhosts",
                to="secret.secret",
            ),
        ),
        migrations.AddField(
            model_name="llmhost",
            name="deployed_at",
            field=models.DateTimeField(blank=True, help_text="When the LLMHost was last launched.", null=True),
        ),
        migrations.AlterField(
            model_name="llmhost",
            name="model_repository",
            field=models.CharField(
                blank=True,
                help_text="e.g. 'meta-llama/Llama-3.1-8B-Instruct', 'llama3.1:8b' or 's3://bucket/prefix'",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="llmhost",
            name="model_revision",
            field=models.CharField(
                blank=True,
                help_text="Commit SHA, branch or tag pinned for reproducible deploys.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="llmhost",
            name="model_source",
            field=models.CharField(
                choices=[
                    ("huggingface", "huggingface"),
                    ("ollama", "ollama"),
                    ("s3", "s3"),
                    ("url", "url"),
                    ("pvc", "pvc"),
                ],
                default="huggingface",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="llmhost",
            name="model_task",
            field=models.CharField(
                choices=[
                    ("text-generation", "text-generation"),
                    ("embedding", "embedding"),
                ],
                default="text-generation",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="llmhost",
            name="public_url",
            field=models.URLField(blank=True, help_text="The base URL of the Ingress, if any."),
        ),
        migrations.AddField(
            model_name="llmhost",
            name="ready_replicas",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="llmhost",
            name="replicas",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="llmhost",
            name="served_model_name",
            field=models.CharField(
                blank=True,
                help_text="The model name that clients send in their requests.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="llmhost",
            name="spec",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="The manifest's spec, in camelCase. The source of truth for launching the LLMHost.",
            ),
        ),
        migrations.AddField(
            model_name="llmhost",
            name="status_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="llmhost",
            name="supports_reasoning",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="llmhost",
            name="api_format",
            field=models.CharField(
                choices=[
                    ("openai_compatible", "openai_compatible"),
                    ("huggingface", "huggingface"),
                    ("ollama_native", "ollama_native"),
                    ("custom", "custom"),
                ],
                default="openai_compatible",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="llmhost",
            name="endpoint_url",
            field=models.URLField(blank=True, help_text="The base URL inside the cluster."),
        ),
        migrations.AlterField(
            model_name="llmhost",
            name="gpu_count",
            field=models.PositiveSmallIntegerField(default=0, help_text="GPUs per replica."),
        ),
        migrations.AlterField(
            model_name="llmhost",
            name="gpu_type",
            field=models.CharField(blank=True, help_text="e.g. 'A10G'", max_length=50),
        ),
        migrations.AlterField(
            model_name="llmhost",
            name="inference_engine",
            field=models.CharField(
                choices=[
                    ("vllm", "vllm"),
                    ("tgi", "tgi"),
                    ("sglang", "sglang"),
                    ("llama_cpp", "llama_cpp"),
                    ("ollama", "ollama"),
                    ("tei", "tei"),
                    ("custom", "custom"),
                ],
                default="vllm",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="llmhost",
            name="model_architecture",
            field=models.CharField(blank=True, help_text="e.g. 'llama', 'mistral', 'qwen3'", max_length=100),
        ),
        migrations.AlterField(
            model_name="llmhost",
            name="quantization",
            field=models.CharField(
                choices=[
                    ("none", "none"),
                    ("fp32", "fp32"),
                    ("fp16", "fp16"),
                    ("bf16", "bf16"),
                    ("fp8", "fp8"),
                    ("mxfp4", "mxfp4"),
                    ("int8", "int8"),
                    ("int4", "int4"),
                    ("gguf", "gguf"),
                    ("awq", "awq"),
                    ("gptq", "gptq"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="llmhost",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("downloading", "downloading"),
                    ("deploying", "deploying"),
                    ("active", "active"),
                    ("degraded", "degraded"),
                    ("inactive", "inactive"),
                    ("error", "error"),
                ],
                db_index=True,
                default="inactive",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="LLMHostEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "llmhost_name",
                    models.CharField(
                        help_text="The LLMHost's name, in case it is deleted.",
                        max_length=255,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("launched", "launched"),
                            ("status_changed", "status_changed"),
                            ("destroyed", "destroyed"),
                            ("error", "error"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("downloading", "downloading"),
                            ("deploying", "deploying"),
                            ("active", "active"),
                            ("degraded", "degraded"),
                            ("inactive", "inactive"),
                            ("error", "error"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True, default="")),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "llmhost",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="llmhost.llmhost",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "LLMHost Events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["llmhost", "event_type"],
                        name="llmhost_llm_llmhost_8af935_idx",
                    )
                ],
            },
            bases=(models.Model, smarter.common.mixins.helper_mixin.SmarterHelperMixin),
        ),
        migrations.AlterField(
            model_name="llmhost",
            name="cost_per_hour",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="The cost per hour of one replica: its share of its compute's node.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="llmhost",
            name="status",
            field=models.CharField(
                choices=[
                    ("provisioning", "provisioning"),
                    ("pending", "pending"),
                    ("downloading", "downloading"),
                    ("deploying", "deploying"),
                    ("active", "active"),
                    ("degraded", "degraded"),
                    ("inactive", "inactive"),
                    ("error", "error"),
                ],
                db_index=True,
                default="inactive",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="llmhostevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("launched", "launched"),
                    ("status_changed", "status_changed"),
                    ("destroyed", "destroyed"),
                    ("nodes_scaled", "nodes_scaled"),
                    ("error", "error"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="llmhostevent",
            name="status",
            field=models.CharField(
                choices=[
                    ("provisioning", "provisioning"),
                    ("pending", "pending"),
                    ("downloading", "downloading"),
                    ("deploying", "deploying"),
                    ("active", "active"),
                    ("degraded", "degraded"),
                    ("inactive", "inactive"),
                    ("error", "error"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="LLMHostCompute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name in camelCase, e.g., 'apiKey', no special characters.",
                        max_length=255,
                        validators=[
                            smarter.lib.django.validators.SmarterValidator.validate_snake_case,
                            smarter.lib.django.validators.SmarterValidator.validate_no_spaces,
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="A brief description of this resource. Be verbose, but not too verbose.",
                        null=True,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        default="1.0.0",
                        help_text="Semantic version in the format MAJOR.MINOR.PATCH, e.g., '1.0.0'.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "annotations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        encoder=smarter.lib.json.SmarterJSONEncoder,
                        help_text="Key-value pairs for annotating this resource.",
                        null=True,
                    ),
                ),
                (
                    "spec",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="The manifest's spec, in camelCase. The source of truth for the node group.",
                    ),
                ),
                (
                    "instance_type",
                    models.CharField(help_text="e.g. 'g6.2xlarge'.", max_length=50),
                ),
                ("cpu", models.PositiveIntegerField(default=1, help_text="vCPUs.")),
                ("memory_gb", models.PositiveIntegerField(default=1, help_text="GiB.")),
                (
                    "gpu_type",
                    models.CharField(blank=True, default="", help_text="e.g. 'L4'.", max_length=50),
                ),
                ("gpu_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "gpu_memory_gb",
                    models.PositiveIntegerField(default=0, help_text="Per GPU."),
                ),
                (
                    "max_nodes",
                    models.PositiveSmallIntegerField(default=4, help_text="The most nodes that Smarter adds."),
                ),
                (
                    "price_per_hour",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Of one node, e.g. its on-demand price.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("nodegroup_status", models.CharField(default="absent", max_length=20)),
                ("desired_nodes", models.PositiveSmallIntegerField(default=0)),
                ("ready_nodes", models.PositiveSmallIntegerField(default=0)),
                ("status_message", models.TextField(blank=True, default="")),
                ("last_reconciled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="Tags for categorizing and organizing this resource.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "LLMHost Compute",
                "verbose_name_plural": "LLMHost Compute",
                "unique_together": {("user_profile", "name")},
            },
            bases=(models.Model, smarter.common.mixins.helper_mixin.SmarterHelperMixin),
        ),
        migrations.AddField(
            model_name="llmhost",
            name="compute",
            field=models.ForeignKey(
                blank=True,
                help_text="The kind of node, and node group, that the LLMHost runs on: spec.compute.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="llmhosts",
                to="llmhost.llmhostcompute",
            ),
        ),
    ]
