# Generated by Django 6.0.8 on 2026-10-02 12:48

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models

import smarter.common.mixins.helper_mixin
import smarter.lib.django.validators
import smarter.lib.json


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0005_budget_unique_name"),
        ("connection", "0002_initial"),
        ("provider", "0002_initial"),
        ("secret", "0001_initial"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="VectorstoreMeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name in camelCase, e.g., 'apiKey', no special characters.",
                        max_length=255,
                        validators=[
                            smarter.lib.django.validators.SmarterValidator.validate_snake_case,
                            smarter.lib.django.validators.SmarterValidator.validate_no_spaces,
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="A brief description of this resource. Be verbose, but not too verbose.",
                        null=True,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        default="1.0.0",
                        help_text="Semantic version in the format MAJOR.MINOR.PATCH, e.g., '1.0.0'.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "annotations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        encoder=smarter.lib.json.SmarterJSONEncoder,
                        help_text="Key-value pairs for annotating this resource.",
                        null=True,
                    ),
                ),
                (
                    "spec",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="The manifest's spec, as it was applied.",
                    ),
                ),
                (
                    "backend",
                    models.CharField(
                        choices=[("qdrant", "Qdrant"), ("pinecone", "Pinecone")],
                        help_text="The vector database product.",
                        max_length=50,
                    ),
                ),
                (
                    "hosting",
                    models.CharField(
                        choices=[
                            ("self_hosted", "Self-hosted on Kubernetes"),
                            ("managed", "Managed service"),
                        ],
                        default="managed",
                        help_text="self_hosted: Smarter runs it on Kubernetes. managed: a service such as Pinecone or Qdrant Cloud.",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the vector database may be used.",
                    ),
                ),
                (
                    "dimension",
                    models.PositiveIntegerField(
                        default=1536,
                        help_text="The number of dimensions of its vectors.",
                    ),
                ),
                (
                    "metric",
                    models.CharField(
                        choices=[
                            ("cosine", "Cosine"),
                            ("euclidean", "Euclidean"),
                            ("dotproduct", "Dot product"),
                        ],
                        default="cosine",
                        max_length=20,
                    ),
                ),
                (
                    "deletion_protection",
                    models.BooleanField(
                        default=False,
                        help_text="Refuse to destroy the database while it is enabled.",
                    ),
                ),
                (
                    "embeddings_model",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g. text-embedding-3-small",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("provisioning", "Provisioning"),
                            ("ready", "Ready"),
                            ("stopped", "Stopped"),
                            ("failed", "Failed"),
                            ("deleting", "Deleting"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("status_message", models.TextField(blank=True, default="")),
                (
                    "index_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The Pinecone index, or Qdrant collection, of the database.",
                        max_length=255,
                    ),
                ),
                (
                    "endpoint_url",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Where the database is reached.",
                        max_length=255,
                    ),
                ),
                (
                    "vector_count",
                    models.BigIntegerField(
                        default=0,
                        help_text="The number of vectors, as of last_checked_at.",
                    ),
                ),
                (
                    "stats",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="The database's own statistics.",
                    ),
                ),
                ("deployed_at", models.DateTimeField(blank=True, null=True)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("last_snapshot_at", models.DateTimeField(blank=True, null=True)),
                ("last_maintenance_at", models.DateTimeField(blank=True, null=True)),
                (
                    "api_key_secret",
                    models.ForeignKey(
                        blank=True,
                        help_text="The API key of a self-hosted database, generated by Smarter.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vectorstores",
                        to="secret.secret",
                    ),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        blank=True,
                        help_text="The ApiConnection of a managed database: its URL, and its API key Secret.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vector_databases",
                        to="connection.apiconnection",
                    ),
                ),
                (
                    "embeddings_provider",
                    models.ForeignKey(
                        blank=True,
                        help_text="The Provider whose embeddings model turns text into vectors.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vector_databases",
                        to="provider.provider",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="Tags for categorizing and organizing this resource.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vectorstore",
                "verbose_name_plural": "Vectorstores",
                "unique_together": {("user_profile", "name")},
            },
            bases=(models.Model, smarter.common.mixins.helper_mixin.SmarterHelperMixin),
        ),
        migrations.CreateModel(
            name="VectorstoreSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The snapshot's name, or the backup's id, in the backend.",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("creating", "Creating"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="creating",
                        max_length=10,
                    ),
                ),
                ("status_message", models.TextField(blank=True, default="")),
                ("size_bytes", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "vector_count",
                    models.BigIntegerField(blank=True, help_text="At the time of the snapshot.", null=True),
                ),
                (
                    "scheduled",
                    models.BooleanField(
                        default=True,
                        help_text="Taken by Celery Beat, rather than on request.",
                    ),
                ),
                (
                    "vectorstore",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="vectorstore.vectorstoremeta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vectorstore Snapshot",
                "verbose_name_plural": "Vectorstore Snapshots",
                "ordering": ["-created_at"],
            },
            bases=(models.Model, smarter.common.mixins.helper_mixin.SmarterHelperMixin),
        ),
        migrations.CreateModel(
            name="VectorstoreDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "name",
                    models.CharField(help_text="e.g. a file name, or a URL.", max_length=255),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("upload", "Upload"),
                            ("url", "URL"),
                            ("text", "Text"),
                            ("file", "File"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "content",
                    models.TextField(help_text="The extracted text. Pages are separated by form feeds."),
                ),
                (
                    "sha256",
                    models.CharField(
                        help_text="Of the content, so that a document is not loaded twice.",
                        max_length=64,
                    ),
                ),
                (
                    "size_bytes",
                    models.PositiveBigIntegerField(default=0, help_text="Of the original file."),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stored with each chunk, for filtered search.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("loading", "Loading"),
                            ("loaded", "Loaded"),
                            ("failed", "Failed"),
                            ("deleting", "Deleting"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("status_message", models.TextField(blank=True, default="")),
                (
                    "chunk_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="The number of chunks in the vector database.",
                    ),
                ),
                ("loaded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "vectorstore",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="vectorstore.vectorstoremeta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vectorstore Document",
                "verbose_name_plural": "Vectorstore Documents",
                "unique_together": {("vectorstore", "sha256")},
            },
            bases=(models.Model, smarter.common.mixins.helper_mixin.SmarterHelperMixin),
        ),
    ]
