# pylint: disable=all
# Generated by Django 5.2.10 on 2026-04-10 00:30

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models

import smarter.common.mixins
import smarter.lib.django.models
import smarter.lib.django.validators
import smarter.lib.json


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0004_alter_account_version_alter_secret_version_and_more"),
        ("provider", "0003_alter_provider_version"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="VectorDatabase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name in camelCase, e.g., 'apiKey', no special characters.",
                        max_length=255,
                        validators=[
                            smarter.lib.django.validators.SmarterValidator.validate_snake_case,
                            smarter.lib.django.models.validate_no_spaces,
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="A brief description of this resource. Be verbose, but not too verbose.",
                        null=True,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        default="1.0.0",
                        help_text="Semantic version in the format MAJOR.MINOR.PATCH, e.g., '1.0.0'.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "annotations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        encoder=smarter.lib.json.SmarterJSONEncoder,
                        help_text="Key-value pairs for annotating this resource.",
                        null=True,
                    ),
                ),
                (
                    "backend",
                    models.CharField(
                        choices=[
                            ("qdrant", "qdrant"),
                            ("weaviate", "weaviate"),
                            ("pinecone", "pinecone"),
                        ],
                        help_text="The backend type for the vector database (e.g., qdrant, weaviate, pinecone).",
                        max_length=50,
                    ),
                ),
                (
                    "host",
                    models.CharField(
                        help_text="The host address of the vector database.",
                        max_length=255,
                    ),
                ),
                (
                    "port",
                    models.IntegerField(help_text="The port number for the vector database."),
                ),
                (
                    "auth_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="The authentication configuration for the vector database.",
                        null=True,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="The configuration settings for the vector database.",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True,
                        default=True,
                        help_text="Indicates whether the vector database is active.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("provisioning", "Provisioning"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                            ("deleting", "Deleting"),
                        ],
                        default="provisioning",
                        help_text="The current status of the vector database (e.g., provisioning, ready, failed, deleting).",
                        max_length=50,
                    ),
                ),
                (
                    "password",
                    models.ForeignKey(
                        blank=True,
                        help_text="The Smarter Secret object containing the password or API key for the vector database.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vector_databases",
                        to="account.secret",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        help_text="The provider associated with this vector database.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vector_databases",
                        to="provider.provider",
                    ),
                ),
                (
                    "provider_model",
                    models.ForeignKey(
                        blank=True,
                        help_text="The provider model associated with this vector database.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vector_databases",
                        to="provider.providermodel",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="Tags for categorizing and organizing this resource.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="account.userprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("user_profile", "name")},
            },
            bases=(models.Model, smarter.common.mixins.SmarterHelperMixin),
        ),
    ]
