# pylint: disable=all
# Generated by Django 6.0.4 on 2026-04-14 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vectorstore", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vectordatabase",
            options={
                "verbose_name": "Vectorstore Metadata",
                "verbose_name_plural": "Vectorstore Metadata",
            },
        ),
        migrations.AlterUniqueTogether(
            name="vectordatabase",
            unique_together=set(),
        ),
    ]
