# pylint: disable=all
# Generated by Django 6.0.8 on 2026-10-01 22:57

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models

import smarter.common.mixins.helper_mixin
import smarter.lib.django.validators
import smarter.lib.json


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0003_alter_aggregatedcharges_options"),
        ("provider", "0002_initial"),
        ("secret", "0001_initial"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Proxy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name in camelCase, e.g., 'apiKey', no special characters.",
                        max_length=255,
                        validators=[
                            smarter.lib.django.validators.SmarterValidator.validate_snake_case,
                            smarter.lib.django.validators.SmarterValidator.validate_no_spaces,
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="A brief description of this resource. Be verbose, but not too verbose.",
                        null=True,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        default="1.0.0",
                        help_text="Semantic version in the format MAJOR.MINOR.PATCH, e.g., '1.0.0'.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "annotations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        encoder=smarter.lib.json.SmarterJSONEncoder,
                        help_text="Key-value pairs for annotating this resource.",
                        null=True,
                    ),
                ),
                (
                    "base_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="The base URL of the provider's API, e.g. https://api.openai.com/v1/. If empty, the provider's base URL is used.",
                        max_length=255,
                    ),
                ),
                (
                    "auth_header",
                    models.CharField(
                        default="Authorization",
                        help_text="The HTTP header in which the provider expects its API key, e.g. 'Authorization' or 'x-api-key'.",
                        max_length=64,
                    ),
                ),
                (
                    "auth_scheme",
                    models.CharField(
                        blank=True,
                        default="Bearer",
                        help_text="The prefix of the API key in the auth header, e.g. 'Bearer'. Empty for none.",
                        max_length=32,
                    ),
                ),
                (
                    "headers",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Other HTTP headers that are added to every request, e.g. {'anthropic-version': '2023-06-01'}.",
                    ),
                ),
                (
                    "allowed_paths",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Glob patterns of the paths, relative to the base URL, that callers may use. Empty allows every path.",
                    ),
                ),
                (
                    "timeout",
                    models.PositiveIntegerField(
                        default=120,
                        help_text="The most seconds to wait for the provider's response.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Inactive proxies refuse every request."),
                ),
                (
                    "api_key_secret",
                    models.ForeignKey(
                        blank=True,
                        help_text="The secret containing the provider's API key. If empty, the provider's own API key is used.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proxies",
                        to="secret.secret",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        help_text="The provider whose API this proxy forwards requests to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proxies",
                        to="provider.provider",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="Tags for categorizing and organizing this resource.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proxy",
                "verbose_name_plural": "Proxies",
                "unique_together": {("user_profile", "name")},
            },
            bases=(models.Model, smarter.common.mixins.helper_mixin.SmarterHelperMixin),
        ),
    ]
