# pylint: disable=all
# Generated by Django 6.0.5 on 2026-06-23 14:23

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models

import smarter.common.mixins.helper_mixin
import smarter.lib.django.validators
import smarter.lib.json


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0001_initial"),
        ("provider", "0002_initial"),
        ("secret", "0001_initial"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Proxy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name in camelCase, e.g., 'apiKey', no special characters.",
                        max_length=255,
                        validators=[
                            smarter.lib.django.validators.SmarterValidator.validate_snake_case,
                            smarter.lib.django.validators.SmarterValidator.validate_no_spaces,
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="A brief description of this resource. Be verbose, but not too verbose.",
                        null=True,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        default="1.0.0",
                        help_text="Semantic version in the format MAJOR.MINOR.PATCH, e.g., '1.0.0'.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "annotations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        encoder=smarter.lib.json.SmarterJSONEncoder,
                        help_text="Key-value pairs for annotating this resource.",
                        null=True,
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        help_text="The native API path for this proxy.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "api_key_secret",
                    models.ForeignKey(
                        help_text="The secret containing the API key for this proxy.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proxies",
                        to="secret.secret",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        help_text="The provider this proxy is associated with.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proxies",
                        to="provider.provider",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="Tags for categorizing and organizing this resource.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.userprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("user_profile", "name")},
            },
            bases=(models.Model, smarter.common.mixins.helper_mixin.SmarterHelperMixin),
        ),
    ]
