# pylint: disable=all
# Generated by Django 6.0.4 on 2026-04-17 15:58

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0001_initial"),
        ("connection", "0001_initial"),
        ("secret", "0001_initial"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="apiconnection",
            name="api_key",
            field=models.ForeignKey(
                blank=True,
                help_text="The API key for authentication, if required.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_connections_api_key",
                to="secret.secret",
            ),
        ),
        migrations.AddField(
            model_name="apiconnection",
            name="proxy_password",
            field=models.ForeignKey(
                blank=True,
                help_text="The proxy password for authentication, if required.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_connections_proxy_password",
                to="secret.secret",
            ),
        ),
        migrations.AddField(
            model_name="apiconnection",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="Tags for categorizing and organizing this resource.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="apiconnection",
            name="user_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="account.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="sqlconnection",
            name="password",
            field=models.ForeignKey(
                blank=True,
                help_text="The password for authentication, if required.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sql_connections_password",
                to="secret.secret",
            ),
        ),
        migrations.AddField(
            model_name="sqlconnection",
            name="proxy_password",
            field=models.ForeignKey(
                blank=True,
                help_text="The API key for authentication, if required.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sql_connections_proxy_password",
                to="secret.secret",
            ),
        ),
        migrations.AddField(
            model_name="sqlconnection",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="Tags for categorizing and organizing this resource.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="sqlconnection",
            name="user_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="account.userprofile",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="apiconnection",
            unique_together={("user_profile", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="sqlconnection",
            unique_together={("user_profile", "name")},
        ),
    ]
