# pylint: disable=W0613,C0302
"""
PromptConfigView is a Django class-based view responsible for providing.

configuration data to the ReactJS prompt UI component in the Smarter
web application.
"""

from http import HTTPStatus
from typing import Any, Optional, Union

from django.http import (
    HttpRequest,
    HttpResponse,
    HttpResponseNotAllowed,
    JsonResponse,
)

from smarter.apps.llmclient.models import (
    LLMClient,
    LLMClientFunctions,
    LLMClientHelper,
    LLMClientPlugin,
    LLMClientRequests,
    get_cached_llmclient_by_request,
)
from smarter.apps.llmclient.serializers import (
    LLMClientConfigSerializer,
    LLMClientFunctionsSerializer,
    LLMClientPluginSerializer,
    LLMClientRequestsSerializer,
)
from smarter.apps.plugin.models import (
    PluginSelectorHistory,
    PluginSelectorHistorySerializer,
)
from smarter.apps.prompt.signals import prompt_config_invoked
from smarter.apps.prompt.views.detailviews.prompt_workbench_view import (
    SmarterPromptSession,
)
from smarter.common.conf import smarter_settings
from smarter.common.const import (
    SMARTER_CHAT_SESSION_KEY_NAME,
    SmarterHttpMethods,
)
from smarter.common.helpers.url_helpers import clean_url
from smarter.common.utils import is_authenticated_request, search_replace
from smarter.lib import logging
from smarter.lib.django import waffle
from smarter.lib.django.http.shortcuts import (
    SmarterHttpResponseForbidden,
)
from smarter.lib.django.views import (
    SmarterAuthenticatedNeverCachedWebView,
)
from smarter.lib.django.waffle import SmarterWaffleSwitches
from smarter.lib.drf.views.helpers import UnauthenticatedPermissionClass
from smarter.lib.journal.enum import SmarterJournalCliCommands, SmarterJournalThings
from smarter.lib.journal.http import (
    SmarterJournaledJsonErrorResponse,
    SmarterJournaledJsonResponse,
)
from smarter.lib.logging import WaffleSwitchedLoggerWrapper

MAX_RETURNED_PLUGINS = 10


def should_log(level):
    """Check if logging should be done based on the waffle switch."""
    return waffle.switch_is_active(SmarterWaffleSwitches.PROMPT_LOGGING)


base_logger = logging.getLogger(__name__)
logger = WaffleSwitchedLoggerWrapper(base_logger, should_log)


def should_log_verbose(level):
    """Check if logging should be done based on the waffle switch."""
    return smarter_settings.verbose_logging


verbose_logger = WaffleSwitchedLoggerWrapper(base_logger, should_log_verbose)


class PromptConfigView(SmarterAuthenticatedNeverCachedWebView):
    """
    Prompt configuration view for the Smarter web application.

    This view is responsible for providing all configuration information required by the ReactJS prompt UI component.
    It is designed to be performant and efficient, as it is invoked on every user-facing browser load and refresh.

    **Key Features:**

    - **Django Template-Based:**
      This view uses Django's template system for rendering and does not rely on Django REST Framework (DRF) serializers for its main response.
      The configuration data is returned as a JSON response, but the view itself is structured as a Django class-based view.

    - **CSRF Exempt:**
      The view is decorated with `@csrf_exempt` because it is read-only and does not modify server-side data. This exemption is safe in this context
      and avoids unnecessary CSRF validation for GET and POST requests that only retrieve configuration data.

    - **ReactJS UI Integration:**
      The endpoint provides all necessary configuration and context information for the ReactJS prompt component. This includes llmclient metadata,
      plugin information, session keys, and historical data relevant to the prompt session. The React app consumes this configuration to initialize
      and render the prompt UI in the user's browser.

    - **Session-Based Architecture:**
      Each prompt session is uniquely identified and managed by a globally unique 64-character session key. The session key is generated by
      RequestHelper.generate_session_key() and is persisted by the browser in a domain and path-specific cookie, meaning that this design supports
      an unlimited number of concurrent sessions per user, one per device per llmclient.

    - **Performance Considerations:**
      Since this endpoint is called on every browser load and refresh, performance is a primary concern. The view is optimized to minimize database
      queries and serialization overhead. Only a limited number of plugins (as defined by `MAX_RETURNED_PLUGINS`) are returned to avoid excessive payload sizes.
      Caching and efficient queryset usage are employed where possible to ensure fast response times for end users.

    **Example Usage:**

        https://smarter.3141-5926-5359.alpha.api.example.com/config/

    **Returns:**
        JSON response containing:
            - `session_key`: Unique identifier for the prompt session.
            - `sandbox_mode`: Boolean indicating if the llmclient is running in sandbox mode.
            - `debug_mode`: Boolean indicating if debug mode is enabled.
            - `llmclient`: Serialized llmclient configuration.
            - `history`: Prompt and plugin selector history for the session.
            - `meta_data`: Additional metadata for the llmclient.
            - `plugins`: Plugin metadata and a limited list of plugins.

    **Security:**
        - The view is protected and requires the user to be authenticated, unless the llmclient is configured to allow unauthenticated access.
        - If authentication is required and the user is not authenticated, a 403 Forbidden response is returned.

    **See Also:**
        - `SmarterPromptSession`: Helper class for managing prompt sessions.
        - `LLMClientConfigSerializer`, `LLMClientPluginSerializer`: Serializers for llmclient and plugin data.
        - `LLMClientHelper`: Helper for llmclient-related operations.
    """

    authentication_classes = None
    permission_classes = (UnauthenticatedPermissionClass,)

    thing: Optional[SmarterJournalThings] = None
    command: Optional[SmarterJournalCliCommands] = None
    session: Optional[SmarterPromptSession] = None
    llmclient_name: Optional[str] = None
    _llmclient_helper: Optional[LLMClientHelper] = None
    _llmclient: Optional[LLMClient] = None

    @property
    def formatted_class_name(self) -> str:
        """Returns a formatted string of the class name for logging purposes."""
        class_name = f"{__name__}.{PromptConfigView.__name__}[{id(self)}]"
        return self.formatted_text(class_name)

    @property
    def llmclient(self) -> Optional[LLMClient]:
        return self._llmclient

    @property
    def llmclient_helper(self) -> Optional[LLMClientHelper]:
        if self._llmclient_helper:
            return self._llmclient_helper
        if self.llmclient:
            # throw everything but the kitchen sink at the LLMClientHelper
            self._llmclient_helper = LLMClientHelper(
                request=self.smarter_request,
                session_key=self.session.session_key if self.session else None,
                name=self._llmclient.name if self._llmclient else self.llmclient_name,
                llmclient_id=self._llmclient.id if self._llmclient else None,  # type: ignore[union-attr]
                account=self.account,
                user=self.user,
                user_profile=self.user_profile,
            )
        else:
            self._llmclient_helper = LLMClientHelper(
                request=self.smarter_request,
                name=self.llmclient_name or self.smarter_request_llmclient_name,
                session_key=self.session.session_key if self.session else None,
                account=self.account,
                user=self.user,
                user_profile=self.user_profile,
            )
        if self._llmclient_helper:
            logger.debug(
                "%s.llmclient_helper property - instantiated LLMClientHelper with llmclient=%s, name=%s",
                self.formatted_class_name,
                self._llmclient_helper.llmclient,
                self._llmclient_helper.name,
            )
        else:
            logger.warning(
                "%s.llmclient_helper property - could not instantiate LLMClientHelper", self.formatted_class_name
            )
        return self._llmclient_helper

    @llmclient_helper.setter
    def llmclient_helper(self, value: Optional[LLMClientHelper]):
        self._llmclient_helper = value
        if self._llmclient_helper and self._llmclient_helper.llmclient:
            self._llmclient = self._llmclient_helper.llmclient
            self.account = self._llmclient_helper.account
            self.user = self._llmclient_helper.user
            self.user_profile = self._llmclient_helper.user_profile
            verbose_logger.debug(
                "%s - llmclient_helper() setter llmclient=%s", self.formatted_class_name, self.llmclient
            )
        else:
            self._llmclient = None
            verbose_logger.debug("%s - llmclient_helper() setter llmclient is unset", self.formatted_class_name)

    def clean_url(self, url: str) -> str:
        """Clean the url of any query strings and trailing '/config/' strings."""
        retval = clean_url(url)
        if retval.endswith("/config/"):
            retval = retval[:-8]
        return retval

    def legacy_config(self, config: Union[dict[str, Any], list[Any]], replace_str: str, with_str: str) -> Any:
        """
        Recursively replaces any key value of 'llmclient' with 'chatbot' for legacy.

        support of older versions of the React app that expect 'chatbot' instead of 'llmclient'.
        """
        retval = search_replace(config, replace_str="llmclient", with_str="chatbot")
        retval = search_replace(retval, replace_str="account_number", with_str="accountNumber")
        retval = search_replace(retval, replace_str="prompt_history", with_str="chat_history")
        return retval

    def config(self) -> dict[str, Any]:
        """
        Assemble and return the configuration dictionary required by the ReactJS prompt UI component.

        This method gathers all relevant context and configuration data for the prompt session and llmclient,
        and returns it as a dictionary suitable for JSON serialization. This configuration is consumed by
        the ReactJS frontend to initialize and render the prompt interface.

        **Key Features:**

        - **Django Template-Based:**
          This logic is part of a Django class-based view and does not use Django REST Framework (DRF) serializers
          for the main response, though serializers are used for some nested data.

        - **CSRF Exempt:**
          The parent view is CSRF exempt because this endpoint is strictly read-only and does not modify server-side data.

        - **ReactJS UI Integration:**
          The returned dictionary provides all configuration and context information needed by the ReactJS prompt component,
          including llmclient metadata, plugin information, session keys, and prompt history.

        - **Session-Based:**
          The configuration is tied to a unique prompt session, as defined by the :class:`SmarterPromptSession` helper,
          which uses a combination of the user's IP address and device-identifying information to uniquely identify
          each session.

        - **Performance:**
          Since this endpoint is called on every browser load and refresh, the logic is optimized to minimize database
          queries and serialization overhead. Only a limited number of plugins (see ``MAX_RETURNED_PLUGINS``) are returned
          to keep payloads small and response times fast.

        Returns
        -------
        dict
            A dictionary containing all configuration data required by the ReactJS prompt UI component. The structure includes:

            - ``session_key``: Unique identifier for the prompt session.
            - ``sandbox_mode``: Boolean indicating if the llmclient is running in sandbox mode.
            - ``debug_mode``: Boolean indicating if debug mode is enabled.
            - ``llmclient``: Serialized llmclient configuration.
            - ``history``: Prompt and plugin selector history for the session.
            - ``meta_data``: Additional metadata for the llmclient.
            - ``plugins``: Plugin metadata and a limited list of plugins.

        Raises
        ------
        SmarterValueError
            If the session or llmclient helper is not set.

        See Also
        --------
        SmarterPromptSession : Helper class for managing prompt sessions.
        LLMClientConfigSerializer, LLMClientPluginSerializer : Serializers for llmclient and plugin data.
        LLMClientHelper : Helper for llmclient-related operations.
        """
        # add llmclient_request_history and plugin_selector_history to history
        # these have to be added here due to circular import issues.
        if self.session is None:
            logger.error(
                "%s.config() - session is None. Cannot retrieve llmclient request history.", self.formatted_class_name
            )
            return {}
        if self.llmclient_helper is None:
            logger.error(
                "%s.config() - LLMClientHelper is None. Cannot retrieve llmclient request history.",
                self.formatted_class_name,
            )
            return {}

        llmclient_serializer = (
            LLMClientConfigSerializer(self.llmclient, context={"request": self.smarter_request})
            if self.llmclient
            else None
        )

        # plugins context. the main thing we need here is to constrain the number of plugins
        # returned to some reasonable number, since we'll probaably have cases where
        # the llmclient has a lot of plugins (hundreds, thousands...).
        llmclient_plugins_count = LLMClientPlugin.objects.filter(llmclient=self.llmclient).count()
        llmclient_plugins = LLMClientPlugin.objects.filter(llmclient=self.llmclient).order_by("-pk")[
            :MAX_RETURNED_PLUGINS
        ]
        llmclient_plugin_serializer = LLMClientPluginSerializer(llmclient_plugins, many=True)

        llmclient_functions_count = LLMClientFunctions.objects.filter(llmclient=self.llmclient).count()
        llmclient_functions = LLMClientFunctions.objects.filter(llmclient=self.llmclient).order_by("-pk")[
            :MAX_RETURNED_PLUGINS
        ]
        llmclient_functions_serializer = LLMClientFunctionsSerializer(llmclient_functions, many=True)

        history = self.session.chat_helper.history if self.session.chat_helper else {}

        llmclient_requests_queryset = LLMClientRequests.objects.filter(session_key=self.session.session_key).order_by(
            "-id"
        )
        llmclient_requests_serializer = LLMClientRequestsSerializer(llmclient_requests_queryset, many=True)
        history["llmclient_request_history"] = llmclient_requests_serializer.data

        plugin_selector_history_queryset = PluginSelectorHistory.objects.filter(session_key=self.session.session_key)
        plugin_selector_history_serializer = PluginSelectorHistorySerializer(
            plugin_selector_history_queryset, many=True
        )
        history["plugin_selector_history"] = plugin_selector_history_serializer.data

        retval = {
            "data": {
                SMARTER_CHAT_SESSION_KEY_NAME: self.session.session_key,
                "sandbox_mode": self.llmclient_helper.is_llmclient_sandbox_url,
                "debug_mode": waffle.switch_is_active(SmarterWaffleSwitches.ENABLE_REACTAPP_DEBUG_MODE),
                "llmclient": llmclient_serializer.data if llmclient_serializer else None,
                "history": history,
                "meta_data": self.llmclient_helper.to_json(),
                "plugins": {
                    "meta_data": {
                        "total_plugins": llmclient_plugins_count,
                        "plugins_returned": len(llmclient_plugins),
                    },
                    "plugins": llmclient_plugin_serializer.data,
                },
                "functions": {
                    "meta_data": {
                        "total_functions": llmclient_functions_count,
                        "functions_returned": len(llmclient_functions),
                    },
                    "functions": llmclient_functions_serializer.data,
                },
            },
        }
        # Legacy support for older versions of the React app that expect
        # 'chatbot' instead of 'llmclient'
        # ---------------------------------------------------------------------
        retval = self.to_snake_case(retval)
        retval = self.legacy_config(retval, replace_str="llmclient", with_str="chatbot")
        retval = self.legacy_config(retval, replace_str="account_number", with_str="accountNumber")
        prompt_config_invoked.send(sender=self.__class__, instance=self, request=self.smarter_request, data=retval)
        return retval

    def dispatch(
        self, request: HttpRequest, *args, **kwargs
    ) -> Union[JsonResponse, HttpResponse, SmarterJournaledJsonErrorResponse]:
        """
        Handles incoming HTTP requests for the prompt configuration endpoint.

        This method is responsible for orchestrating the retrieval and assembly of all configuration data
        required by the ReactJS prompt UI component. It is invoked on every user-facing browser load and refresh,
        making performance a critical concern.

        **Key Details:**

        - **Django Template-Based:**
          This view uses Django's class-based view and template system, not Django REST Framework (DRF).
          The response is a JSON object, but the view logic is not DRF-based.

        - **CSRF Exempt:**
          The view is decorated with ``@csrf_exempt`` because it is strictly read-only and does not modify server-side data.
          This avoids unnecessary CSRF validation for GET and POST requests that only retrieve configuration data.

        - **ReactJS UI Integration:**
          The endpoint provides all configuration and context information needed by the ReactJS prompt component,
          including llmclient metadata, plugin information, session keys, and prompt history.

        - **Session-Based:**
          Sessions are managed by the :class:`SmarterPromptSession` helper, which uniquely defines a prompt session
          using a combination of the user's IP address and device-identifying information. This ensures each device/browser
          instance receives a unique session key, which is used to track prompt history and plugin usage.

        - **Performance:**
          Since this endpoint is called on every browser load and refresh, it is optimized to minimize database queries
          and serialization overhead. Only a limited number of plugins are returned (see ``MAX_RETURNED_PLUGINS``)
          to keep payloads small and response times fast.

        Parameters
        ----------
        request : HttpRequest
            The incoming HTTP request object.
        llmclient_id : Optional[int], default=None
            The ID of the llmclient to retrieve configuration for, if specified.
        *args
            Additional positional arguments.
        **kwargs
            Additional keyword arguments.

        Returns
        -------
        Union[JsonResponse, HttpResponse, SmarterJournaledJsonErrorResponse]
            A JSON response containing all configuration data required by the ReactJS prompt UI component,
            or an error response if the request is invalid or unauthorized.

        See Also
        --------
        SmarterPromptSession : Helper class for managing prompt sessions.
        LLMClientConfigSerializer, LLMClientPluginSerializer : Serializers for llmclient and plugin data.
        LLMClientHelper : Helper for llmclient-related operations.
        """
        hashed_id = kwargs.pop("hashed_id", None)
        if hashed_id:
            llmclient_id = LLMClient.id_from_hashed_id(hashed_id)
        else:
            llmclient_id = kwargs.pop("llmclient_id", None)

        if llmclient_id is not None:
            try:
                self._llmclient = LLMClient.get_cached_object(pk=llmclient_id)
                self.llmclient_name = self._llmclient.name
                verbose_logger.debug(
                    "%s.dispatch() - set llmclient=%s from llmclient_id=%s",
                    self.formatted_class_name,
                    self._llmclient,
                    llmclient_id,
                )
            except LLMClient.DoesNotExist:
                verbose_logger.error(
                    "%s.dispatch() - LLMClient with id=%s does not exist. Returning 404.",
                    self.formatted_class_name,
                    llmclient_id,
                )
                return JsonResponse({"error": "Not found"}, status=HTTPStatus.NOT_FOUND.value)
        else:
            self.llmclient_name = kwargs.get("name")
            try:
                self._llmclient = get_cached_llmclient_by_request(request=request)
                if not self._llmclient:
                    verbose_logger.debug(
                        "%s.dispatch() - get_cached_llmclient_by_request() returned None. Attempting to instantiate LLMClientHelper with additional info",
                        self.formatted_class_name,
                    )
                    self.llmclient_helper = LLMClientHelper(
                        request=self.smarter_request,
                        session_key=self.session_key,
                        llmclient_id=llmclient_id,
                        name=self.llmclient_name,
                        account=self.account,
                        user=self.user,
                        user_profile=self.user_profile,
                    )
            except LLMClient.DoesNotExist:
                return JsonResponse({"error": "Not found"}, status=HTTPStatus.NOT_FOUND.value)

        # Initialize the prompt session for this request. session_key is generated
        # and managed by the /config/ endpoint for the llmclient
        #
        # examples:
        # - https://customer-support.3141-5926-5359.api.example.com/workbench/config/?session_key=123456
        # - http://localhost:9357/api/v1/llm-clients/1556/prompt/config/?session_key=0733c7b3a33e7eb733c95f6d7fc88d671b6c957e6857a04d05b3f5905167116f
        #
        # The React app calls this endpoint at app initialization to get a
        # json dict that includes, among other pertinent info, this session_key
        # which uniquely identifies the device and the individual llmclient session
        # for the device.
        self.session = SmarterPromptSession(request, session_key=self.session_key, llmclient=self.llmclient)

        if (
            self.llmclient_helper
            and self.llmclient_helper.is_authentication_required
            and not is_authenticated_request(request)
        ):
            return SmarterHttpResponseForbidden(
                request,
                "Authentication failed. Are you logged in? Smarter sessions automatically expire after 24 hours.",
            )

        verbose_logger.debug(
            "%s - llmclient=%s - llmclient_helper=%s",
            self.formatted_class_name,
            self.llmclient,
            self.llmclient_helper,
        )

        if not self.llmclient:
            return JsonResponse({"error": "Not found"}, status=HTTPStatus.NOT_FOUND.value)

        self.thing = SmarterJournalThings(SmarterJournalThings.PROMPT_CONFIG)
        self.command = SmarterJournalCliCommands(SmarterJournalCliCommands.PROMPT_CONFIG)

        verbose_logger.debug(
            "%s.dispatch() completed with llmclient=%s, session_key=%s",
            self.formatted_class_name,
            self.llmclient,
            self.session.session_key if self.session else "(Missing session)",
        )
        return super().dispatch(request, *args, **kwargs)  # type: ignore[return-value]

    def __str__(self):
        return str(self.llmclient) if self.llmclient else "PromptConfigView"

    # pylint: disable=unused-argument
    def post(self, request: HttpRequest, *args, **kwargs) -> SmarterJournaledJsonResponse:
        """Get the llmclient configuration."""
        logger.debug("%s - post()", self.formatted_class_name)
        data = self.config()
        return SmarterJournaledJsonResponse(request=request, data=data, thing=self.thing, command=self.command)

    # pylint: disable=unused-argument
    def get(self, request: HttpRequest, *args, **kwargs) -> Union[SmarterJournaledJsonResponse, HttpResponseNotAllowed]:
        """Get the llmclient configuration."""
        logger.warning(
            "%s - get() %s should be invoked via POST instead of GET.", self.formatted_class_name, request.path
        )
        if not waffle.switch_is_active(SmarterWaffleSwitches.ALLOW_API_GET):

            logger.error(
                "%s.get() %s is not allowed because %s switch is inactive.",
                self.formatted_class_name,
                request.path,
                SmarterWaffleSwitches.ALLOW_API_GET,
            )
            return HttpResponseNotAllowed(permitted_methods=[SmarterHttpMethods.POST])
        data = self.config()
        return SmarterJournaledJsonResponse(request=request, data=data, thing=self.thing, command=self.command)
