# pylint: disable=missing-module-docstring,missing-class-docstring,missing-function-docstring
# Generated by Django 5.0.6 on 2024-05-31 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import smarter.lib.journal.enum


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SAMJournal",
            fields=[
                (
                    "key",
                    models.CharField(
                        default=None,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "thing",
                    models.CharField(
                        choices=[
                            (
                                smarter.lib.journal.enum.SmarterJournalThings["PLUGIN"],
                                smarter.lib.journal.enum.SmarterJournalThings["PLUGIN"],
                            ),
                            (
                                smarter.lib.journal.enum.SmarterJournalThings["ACCOUNT"],
                                smarter.lib.journal.enum.SmarterJournalThings["ACCOUNT"],
                            ),
                            (
                                smarter.lib.journal.enum.SmarterJournalThings["APIKEY"],
                                smarter.lib.journal.enum.SmarterJournalThings["APIKEY"],
                            ),
                            (
                                smarter.lib.journal.enum.SmarterJournalThings["USER"],
                                smarter.lib.journal.enum.SmarterJournalThings["USER"],
                            ),
                            (
                                smarter.lib.journal.enum.SmarterJournalThings["CHAT"],
                                smarter.lib.journal.enum.SmarterJournalThings["CHAT"],
                            ),
                            (
                                smarter.lib.journal.enum.SmarterJournalThings["CHAT_CONFIG"],
                                smarter.lib.journal.enum.SmarterJournalThings["CHAT_CONFIG"],
                            ),
                            (
                                smarter.lib.journal.enum.SmarterJournalThings["CHAT_HISTORY"],
                                smarter.lib.journal.enum.SmarterJournalThings["CHAT_HISTORY"],
                            ),
                            (
                                smarter.lib.journal.enum.SmarterJournalThings["CHAT_PLUGIN_USAGE"],
                                smarter.lib.journal.enum.SmarterJournalThings["CHAT_PLUGIN_USAGE"],
                            ),
                            (
                                smarter.lib.journal.enum.SmarterJournalThings["CHAT_TOOL_CALL"],
                                smarter.lib.journal.enum.SmarterJournalThings["CHAT_TOOL_CALL"],
                            ),
                            (
                                smarter.lib.journal.enum.SmarterJournalThings["CHATBOT"],
                                smarter.lib.journal.enum.SmarterJournalThings["CHATBOT"],
                            ),
                            (
                                smarter.lib.journal.enum.SmarterJournalThings["SQLCONNECTION"],
                                smarter.lib.journal.enum.SmarterJournalThings["SQLCONNECTION"],
                            ),
                            # (
                            #     smarter.lib.journal.enum.SmarterJournalThings["APICONNECTION"],
                            #     smarter.lib.journal.enum.SmarterJournalThings["APICONNECTION"],
                            # ),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "command",
                    models.CharField(
                        choices=[
                            (
                                smarter.lib.journal.enum.SmarterJournalCliCommands["APPLY"],
                                smarter.lib.journal.enum.SmarterJournalCliCommands["APPLY"],
                            ),
                            (
                                smarter.lib.journal.enum.SmarterJournalCliCommands["CHAT"],
                                smarter.lib.journal.enum.SmarterJournalCliCommands["CHAT"],
                            ),
                            (
                                smarter.lib.journal.enum.SmarterJournalCliCommands["CHAT_CONFIG"],
                                smarter.lib.journal.enum.SmarterJournalCliCommands["CHAT_CONFIG"],
                            ),
                            (
                                smarter.lib.journal.enum.SmarterJournalCliCommands["DELETE"],
                                smarter.lib.journal.enum.SmarterJournalCliCommands["DELETE"],
                            ),
                            (
                                smarter.lib.journal.enum.SmarterJournalCliCommands["DEPLOY"],
                                smarter.lib.journal.enum.SmarterJournalCliCommands["DEPLOY"],
                            ),
                            (
                                smarter.lib.journal.enum.SmarterJournalCliCommands["DESCRIBE"],
                                smarter.lib.journal.enum.SmarterJournalCliCommands["DESCRIBE"],
                            ),
                            (
                                smarter.lib.journal.enum.SmarterJournalCliCommands["GET"],
                                smarter.lib.journal.enum.SmarterJournalCliCommands["GET"],
                            ),
                            (
                                smarter.lib.journal.enum.SmarterJournalCliCommands["JOURNAL"],
                                smarter.lib.journal.enum.SmarterJournalCliCommands["JOURNAL"],
                            ),
                            (
                                smarter.lib.journal.enum.SmarterJournalCliCommands["LOGS"],
                                smarter.lib.journal.enum.SmarterJournalCliCommands["LOGS"],
                            ),
                            (
                                smarter.lib.journal.enum.SmarterJournalCliCommands["MANIFEST_EXAMPLE"],
                                smarter.lib.journal.enum.SmarterJournalCliCommands["MANIFEST_EXAMPLE"],
                            ),
                            (
                                smarter.lib.journal.enum.SmarterJournalCliCommands["STATUS"],
                                smarter.lib.journal.enum.SmarterJournalCliCommands["STATUS"],
                            ),
                            (
                                smarter.lib.journal.enum.SmarterJournalCliCommands["VERSION"],
                                smarter.lib.journal.enum.SmarterJournalCliCommands["VERSION"],
                            ),
                            (
                                smarter.lib.journal.enum.SmarterJournalCliCommands["UNDEPLOY"],
                                smarter.lib.journal.enum.SmarterJournalCliCommands["UNDEPLOY"],
                            ),
                            (
                                smarter.lib.journal.enum.SmarterJournalCliCommands["WHOAMI"],
                                smarter.lib.journal.enum.SmarterJournalCliCommands["WHOAMI"],
                            ),
                        ],
                        max_length=24,
                    ),
                ),
                ("request", models.JSONField()),
                ("response", models.JSONField()),
                ("status_code", models.PositiveSmallIntegerField(default=200)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
