# pylint: disable=all
# Generated by Django 5.2.10 on 2026-04-10 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="samjournal",
            name="thing",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Plugin", "Plugin"),
                    ("ApiPlugin", "ApiPlugin"),
                    ("SqlPlugin", "SqlPlugin"),
                    ("ApiConnection", "ApiConnection"),
                    ("SqlConnection", "SqlConnection"),
                    ("Account", "Account"),
                    ("AuthToken", "AuthToken"),
                    ("User", "User"),
                    ("Chat", "Chat"),
                    ("ChatConfig", "ChatConfig"),
                    ("ChatHistory", "ChatHistory"),
                    ("ChatPluginUsage", "ChatPluginUsage"),
                    ("ChatToolCall", "ChatToolCall"),
                    ("Chatbot", "Chatbot"),
                    ("Provider", "Provider"),
                    ("Secret", "Secret"),
                    ("Vectorstore", "Vectorstore"),
                ],
                default="Chat",
                max_length=24,
            ),
        ),
    ]
