# pylint: disable=all
# Generated by Django 6.0.5 on 2026-06-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0002_alter_samjournal_command"),
    ]

    operations = [
        migrations.AlterField(
            model_name="samjournal",
            name="thing",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Account", "Account"),
                    ("ApiConnection", "ApiConnection"),
                    ("ApiPlugin", "ApiPlugin"),
                    ("SmarterAuthToken", "SmarterAuthToken"),
                    ("LLMClient", "LLMClient"),
                    ("Prompt", "Prompt"),
                    ("ChatConfig", "ChatConfig"),
                    ("Proxy", "Proxy"),
                    ("Provider", "Provider"),
                    ("Secret", "Secret"),
                    ("SqlConnection", "SqlConnection"),
                    ("SqlPlugin", "SqlPlugin"),
                    ("Plugin", "Plugin"),
                    ("User", "User"),
                    ("Vectorstore", "Vectorstore"),
                ],
                default="Prompt",
                max_length=24,
            ),
        ),
    ]
