# pylint: disable=all
"""
SAMJournal: add the WebsearchPlugin thing.

Also includes a pending update to the command choices.
"""

# Generated by Django 6.0.5 on 2026-09-30 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0003_alter_samjournal_thing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="samjournal",
            name="command",
            field=models.CharField(
                blank=True,
                choices=[
                    ("apply", "apply"),
                    ("prompt", "prompt"),
                    ("chat_config", "chat_config"),
                    ("delete", "delete"),
                    ("deploy", "deploy"),
                    ("describe", "describe"),
                    ("get", "get"),
                    ("journal", "journal"),
                    ("logs", "logs"),
                    ("example_manifest", "example_manifest"),
                    ("status", "status"),
                    ("json_schema", "json_schema"),
                    ("version", "version"),
                    ("undeploy", "undeploy"),
                    ("whoami", "whoami"),
                    ("resources", "resources"),
                ],
                default="prompt",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="samjournal",
            name="thing",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Account", "Account"),
                    ("ApiConnection", "ApiConnection"),
                    ("ApiPlugin", "ApiPlugin"),
                    ("SmarterAuthToken", "SmarterAuthToken"),
                    ("Guardrail", "Guardrail"),
                    ("LLMClient", "LLMClient"),
                    ("MCPClient", "MCPClient"),
                    ("Orchestrator", "Orchestrator"),
                    ("Prompt", "Prompt"),
                    ("ChatConfig", "ChatConfig"),
                    ("Proxy", "Proxy"),
                    ("Provider", "Provider"),
                    ("Secret", "Secret"),
                    ("SkillPlugin", "SkillPlugin"),
                    ("SqlConnection", "SqlConnection"),
                    ("SqlPlugin", "SqlPlugin"),
                    ("Plugin", "Plugin"),
                    ("User", "User"),
                    ("Vectorsearch", "Vectorsearch"),
                    ("Vectorstore", "Vectorstore"),
                    ("WebsearchPlugin", "WebsearchPlugin"),
                ],
                default="Prompt",
                max_length=24,
            ),
        ),
    ]
