# Generated by Django 5.1.3 on 2025-01-31 19:14
# pylint: disable=missing-module-docstring,missing-class-docstring,missing-function-docstring

from django.db import migrations, models

import smarter.lib.journal.enum


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0004_alter_samjournal_thing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="samjournal",
            name="command",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        smarter.lib.journal.enum.SmarterJournalCliCommands["APPLY"],
                        smarter.lib.journal.enum.SmarterJournalCliCommands["APPLY"],
                    ),
                    (
                        smarter.lib.journal.enum.SmarterJournalCliCommands["CHAT"],
                        smarter.lib.journal.enum.SmarterJournalCliCommands["CHAT"],
                    ),
                    (
                        smarter.lib.journal.enum.SmarterJournalCliCommands["CHAT_CONFIG"],
                        smarter.lib.journal.enum.SmarterJournalCliCommands["CHAT_CONFIG"],
                    ),
                    (
                        smarter.lib.journal.enum.SmarterJournalCliCommands["DELETE"],
                        smarter.lib.journal.enum.SmarterJournalCliCommands["DELETE"],
                    ),
                    (
                        smarter.lib.journal.enum.SmarterJournalCliCommands["DEPLOY"],
                        smarter.lib.journal.enum.SmarterJournalCliCommands["DEPLOY"],
                    ),
                    (
                        smarter.lib.journal.enum.SmarterJournalCliCommands["DESCRIBE"],
                        smarter.lib.journal.enum.SmarterJournalCliCommands["DESCRIBE"],
                    ),
                    (
                        smarter.lib.journal.enum.SmarterJournalCliCommands["GET"],
                        smarter.lib.journal.enum.SmarterJournalCliCommands["GET"],
                    ),
                    (
                        smarter.lib.journal.enum.SmarterJournalCliCommands["JOURNAL"],
                        smarter.lib.journal.enum.SmarterJournalCliCommands["JOURNAL"],
                    ),
                    (
                        smarter.lib.journal.enum.SmarterJournalCliCommands["LOGS"],
                        smarter.lib.journal.enum.SmarterJournalCliCommands["LOGS"],
                    ),
                    (
                        smarter.lib.journal.enum.SmarterJournalCliCommands["MANIFEST_EXAMPLE"],
                        smarter.lib.journal.enum.SmarterJournalCliCommands["MANIFEST_EXAMPLE"],
                    ),
                    (
                        smarter.lib.journal.enum.SmarterJournalCliCommands["STATUS"],
                        smarter.lib.journal.enum.SmarterJournalCliCommands["STATUS"],
                    ),
                    (
                        smarter.lib.journal.enum.SmarterJournalCliCommands["SCHEMA"],
                        smarter.lib.journal.enum.SmarterJournalCliCommands["SCHEMA"],
                    ),
                    (
                        smarter.lib.journal.enum.SmarterJournalCliCommands["VERSION"],
                        smarter.lib.journal.enum.SmarterJournalCliCommands["VERSION"],
                    ),
                    (
                        smarter.lib.journal.enum.SmarterJournalCliCommands["UNDEPLOY"],
                        smarter.lib.journal.enum.SmarterJournalCliCommands["UNDEPLOY"],
                    ),
                    (
                        smarter.lib.journal.enum.SmarterJournalCliCommands["WHOAMI"],
                        smarter.lib.journal.enum.SmarterJournalCliCommands["WHOAMI"],
                    ),
                ],
                max_length=24,
                null=True,
            ),
        ),
    ]
