# Generated by Django 6.0.8 on 2026-10-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0005_alter_samjournal_thing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="samjournal",
            name="command",
            field=models.CharField(
                blank=True,
                choices=[
                    ("apply", "apply"),
                    ("prompt", "prompt"),
                    ("chat_config", "chat_config"),
                    ("delete", "delete"),
                    ("deploy", "deploy"),
                    ("describe", "describe"),
                    ("get", "get"),
                    ("journal", "journal"),
                    ("logs", "logs"),
                    ("example_manifest", "example_manifest"),
                    ("status", "status"),
                    ("json_schema", "json_schema"),
                    ("version", "version"),
                    ("undeploy", "undeploy"),
                    ("validate", "validate"),
                    ("whoami", "whoami"),
                    ("resources", "resources"),
                ],
                default="prompt",
                max_length=24,
            ),
        ),
    ]
