# Generated by Django 5.1.7 on 2025-05-07 14:28
# pylint: disable=missing-module-docstring,missing-function-docstring,missing-class-docstring

from django.db import migrations, models

import smarter.lib.journal.enum


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0006_alter_samjournal_thing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="samjournal",
            name="thing",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        smarter.lib.journal.enum.SmarterJournalThings["STATIC_PLUGIN"],
                        smarter.lib.journal.enum.SmarterJournalThings["STATIC_PLUGIN"],
                    ),
                    (
                        smarter.lib.journal.enum.SmarterJournalThings["API_PLUGIN"],
                        smarter.lib.journal.enum.SmarterJournalThings["API_PLUGIN"],
                    ),
                    (
                        smarter.lib.journal.enum.SmarterJournalThings["SQL_PLUGIN"],
                        smarter.lib.journal.enum.SmarterJournalThings["SQL_PLUGIN"],
                    ),
                    (
                        smarter.lib.journal.enum.SmarterJournalThings["API_CONNECTION"],
                        smarter.lib.journal.enum.SmarterJournalThings["API_CONNECTION"],
                    ),
                    (
                        smarter.lib.journal.enum.SmarterJournalThings["SQL_CONNECTION"],
                        smarter.lib.journal.enum.SmarterJournalThings["SQL_CONNECTION"],
                    ),
                    (
                        smarter.lib.journal.enum.SmarterJournalThings["ACCOUNT"],
                        smarter.lib.journal.enum.SmarterJournalThings["ACCOUNT"],
                    ),
                    (
                        smarter.lib.journal.enum.SmarterJournalThings["AUTH_TOKEN"],
                        smarter.lib.journal.enum.SmarterJournalThings["AUTH_TOKEN"],
                    ),
                    (
                        smarter.lib.journal.enum.SmarterJournalThings["USER"],
                        smarter.lib.journal.enum.SmarterJournalThings["USER"],
                    ),
                    (
                        smarter.lib.journal.enum.SmarterJournalThings["CHAT"],
                        smarter.lib.journal.enum.SmarterJournalThings["CHAT"],
                    ),
                    (
                        smarter.lib.journal.enum.SmarterJournalThings["CHAT_CONFIG"],
                        smarter.lib.journal.enum.SmarterJournalThings["CHAT_CONFIG"],
                    ),
                    (
                        smarter.lib.journal.enum.SmarterJournalThings["CHAT_HISTORY"],
                        smarter.lib.journal.enum.SmarterJournalThings["CHAT_HISTORY"],
                    ),
                    (
                        smarter.lib.journal.enum.SmarterJournalThings["CHAT_PLUGIN_USAGE"],
                        smarter.lib.journal.enum.SmarterJournalThings["CHAT_PLUGIN_USAGE"],
                    ),
                    (
                        smarter.lib.journal.enum.SmarterJournalThings["CHAT_TOOL_CALL"],
                        smarter.lib.journal.enum.SmarterJournalThings["CHAT_TOOL_CALL"],
                    ),
                    (
                        smarter.lib.journal.enum.SmarterJournalThings["CHATBOT"],
                        smarter.lib.journal.enum.SmarterJournalThings["CHATBOT"],
                    ),
                    (
                        smarter.lib.journal.enum.SmarterJournalThings["SECRET"],
                        smarter.lib.journal.enum.SmarterJournalThings["SECRET"],
                    ),
                ],
                max_length=24,
                null=True,
            ),
        ),
    ]
