# Generated by Django 5.1.7 on 2025-06-16 12:50
# pylint: disable=missing-module-docstring,missing-function-docstring,missing-class-docstring

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0007_alter_samjournal_thing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="samjournal",
            name="command",
            field=models.CharField(
                blank=True,
                choices=[
                    ("apply", "apply"),
                    ("chat", "chat"),
                    ("chat_config", "chat_config"),
                    ("delete", "delete"),
                    ("deploy", "deploy"),
                    ("describe", "describe"),
                    ("get", "get"),
                    ("journal", "journal"),
                    ("logs", "logs"),
                    ("example_manifest", "example_manifest"),
                    ("status", "status"),
                    ("schema", "schema"),
                    ("version", "version"),
                    ("undeploy", "undeploy"),
                    ("whoami", "whoami"),
                ],
                default="chat",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="samjournal",
            name="thing",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Plugin", "Plugin"),
                    ("ApiPlugin", "ApiPlugin"),
                    ("SqlPlugin", "SqlPlugin"),
                    ("ApiConnection", "ApiConnection"),
                    ("SqlConnection", "SqlConnection"),
                    ("Account", "Account"),
                    ("AuthToken", "AuthToken"),
                    ("User", "User"),
                    ("Chat", "Chat"),
                    ("ChatConfig", "ChatConfig"),
                    ("ChatHistory", "ChatHistory"),
                    ("ChatPluginUsage", "ChatPluginUsage"),
                    ("ChatToolCall", "ChatToolCall"),
                    ("Chatbot", "Chatbot"),
                    ("Provider", "Provider"),
                    ("Secret", "Secret"),
                ],
                default="Chat",
                max_length=24,
            ),
        ),
    ]
