# Generated by Django 5.1.7 on 2025-06-27 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "account",
            "0011_user_alter_charge_user_alter_dailybillingrecord_user_and_more",
        ),
        ("journal", "0008_alter_samjournal_command_alter_samjournal_thing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="samjournal",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.user",
            ),
        ),
    ]
