# pylint: disable=missing-module-docstring,missing-function-docstring,missing-class-docstring
# Generated by Django 5.2.7 on 2026-01-09 07:34

from django.db import migrations, models

import smarter.lib.json


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0009_alter_samjournal_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="samjournal",
            name="request",
            field=models.JSONField(encoder=smarter.lib.json.SmarterJSONEncoder),
        ),
        migrations.AlterField(
            model_name="samjournal",
            name="response",
            field=models.JSONField(encoder=smarter.lib.json.SmarterJSONEncoder),
        ),
    ]
