# pylint: disable=all
# Generated by Django 6.0.5 on 2026-07-07 23:15

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models

import smarter.common.mixins.helper_mixin
import smarter.lib.django.validators
import smarter.lib.json


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0003_alter_aggregatedcharges_options"),
        ("secret", "0001_initial"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        ("vectorstore", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vectorsearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name in camelCase, e.g., 'apiKey', no special characters.",
                        max_length=255,
                        validators=[
                            smarter.lib.django.validators.SmarterValidator.validate_snake_case,
                            smarter.lib.django.validators.SmarterValidator.validate_no_spaces,
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="A brief description of this resource. Be verbose, but not too verbose.",
                        null=True,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        default="1.0.0",
                        help_text="Semantic version in the format MAJOR.MINOR.PATCH, e.g., '1.0.0'.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "annotations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        encoder=smarter.lib.json.SmarterJSONEncoder,
                        help_text="Key-value pairs for annotating this resource.",
                        null=True,
                    ),
                ),
                (
                    "search_type",
                    models.CharField(
                        choices=[
                            ("similarity", "Similarity"),
                            (
                                "similarity_score_threshold",
                                "Similarity w/ Score Threshold",
                            ),
                            ("mmr", "Maximal Marginal Relevance"),
                        ],
                        default="similarity",
                        help_text="The retrieval strategy to use when querying the VectorstoreMeta.",
                        max_length=32,
                    ),
                ),
                (
                    "k",
                    models.PositiveSmallIntegerField(
                        default=4,
                        help_text="Number of top results to return from the search.",
                    ),
                ),
                (
                    "score_threshold",
                    models.FloatField(
                        blank=True,
                        help_text="Minimum relevance score (0.0-1.0) a result must meet to be included. Only applicable when search_type='similarity_score_threshold'.",
                        null=True,
                    ),
                ),
                (
                    "fetch_k",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Number of candidate documents to fetch before applying MMR re-ranking. Only applicable when search_type='mmr'.",
                        null=True,
                    ),
                ),
                (
                    "lambda_mult",
                    models.FloatField(
                        blank=True,
                        help_text="Diversity vs. relevance trade-off for MMR, between 0.0 (max diversity) and 1.0 (max relevance). Only applicable when search_type='mmr'.",
                        null=True,
                    ),
                ),
                (
                    "metadata_filter",
                    models.JSONField(
                        blank=True,
                        help_text="Optional metadata filter applied to the VectorstoreMeta query, e.g. {'source': 'faq'}.",
                        null=True,
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this Vectorsearch is active and eligible to be queried.",
                    ),
                ),
                (
                    "auth_secret",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional credential used to authenticate against the VectorstoreMeta, if required.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vectorsearches",
                        to="secret.secret",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="Tags for categorizing and organizing this resource.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.userprofile",
                    ),
                ),
                (
                    "vectorstore",
                    models.ForeignKey(
                        help_text="The locally-hosted VectorstoreMeta this search queries against.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vectorsearches",
                        to="vectorstore.vectorstoremeta",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Vectorsearches",
                "unique_together": {("user_profile", "name")},
            },
            bases=(models.Model, smarter.common.mixins.helper_mixin.SmarterHelperMixin),
        ),
    ]
