# Generated by Django 5.1.7 on 2025-05-16 14:53
# pylint: disable=missing-docstring,missing-module-docstring,missing-class-docstring,missing-function-docstring

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drf", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smarterauthtoken",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="smarterauthtoken",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
    ]
