# pylint: disable=all
# Generated by Django 5.2.10 on 2026-03-14 22:57

from django.db import migrations, models

import smarter.lib.json


class Migration(migrations.Migration):

    dependencies = [
        ("drf", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smarterauthtoken",
            name="annotations",
            field=models.JSONField(
                blank=True,
                default=list,
                encoder=smarter.lib.json.SmarterJSONEncoder,
                help_text="Key-value pairs for annotating this resource.",
                null=True,
            ),
        ),
    ]
