# pylint: disable=missing-docstring,missing-module-docstring,missing-class-docstring,missing-function-docstring
# Generated by Django 5.1.7 on 2025-05-16 14:53

import taggit.managers
from django.db import migrations, models

import smarter.lib.json


class Migration(migrations.Migration):

    dependencies = [
        ("drf", "0002_alter_smarterauthtoken_created_at_and_more"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="smarterauthtoken",
            name="annotations",
            field=models.JSONField(
                blank=True,
                default=list,
                encoder=smarter.lib.json.SmarterJSONEncoder,
                help_text="Key-value pairs for annotating this resource.",
            ),
        ),
        migrations.AddField(
            model_name="smarterauthtoken",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="Tags for categorizing and organizing this resource.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="smarterauthtoken",
            name="version",
            field=models.CharField(default="1.0.0", max_length=255),
        ),
    ]
