# pylint: disable=missing-docstring,missing-module-docstring,missing-class-docstring,missing-function-docstring
# Generated by Django 5.2.7 on 2026-01-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drf", "0003_smarterauthtoken_annotations_smarterauthtoken_tags_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="smarterauthtoken",
            name="tags",
        ),
        migrations.AddField(
            model_name="smarterauthtoken",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
