# pylint: disable=all
# Generated by Django 5.2.10 on 2026-03-25 15:09

import taggit.managers
from django.db import migrations, models

import smarter.lib.django.models
import smarter.lib.django.validators


class Migration(migrations.Migration):

    dependencies = [
        ("drf", "0003_alter_smarterauthtoken_version"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="smarterauthtoken",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="A brief description of this resource. Be verbose, but not too verbose.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="smarterauthtoken",
            name="name",
            field=models.CharField(
                help_text="Name in camelCase, e.g., 'apiKey', no special characters.",
                max_length=255,
                validators=[
                    smarter.lib.django.validators.SmarterValidator.validate_snake_case,
                    smarter.lib.django.models.validate_no_spaces,
                ],
            ),
        ),
        migrations.RemoveField(
            model_name="smarterauthtoken",
            name="tags",
        ),
        migrations.AddField(
            model_name="smarterauthtoken",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="Tags for categorizing and organizing this resource.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
