# pylint: disable=missing-docstring,missing-module-docstring,missing-class-docstring,missing-function-docstring
# Generated by Django 5.2.7 on 2026-01-11 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0018_alter_account_annotations_alter_secret_annotations_and_more"),
        ("drf", "0004_remove_smarterauthtoken_tags_smarterauthtoken_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="smarterauthtoken",
            name="account",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="account.account",
            ),
            preserve_default=False,
        ),
    ]
