# Generated by Django 5.1.7 on 2025-05-07 14:28
# pylint: disable=missing-module-docstring,missing-function-docstring,missing-class-docstring

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
        ("plugin", "0006_alter_pluginprompt_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="PluginMetaApi",
            fields=[],
            options={
                "verbose_name": "Plugin Meta (API)",
                "verbose_name_plural": "Plugin Meta (API)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("plugin.pluginmeta",),
        ),
        migrations.CreateModel(
            name="PluginMetaSql",
            fields=[],
            options={
                "verbose_name": "Plugin Meta (SQL)",
                "verbose_name_plural": "Plugin Meta (SQL)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("plugin.pluginmeta",),
        ),
        migrations.CreateModel(
            name="PluginMetaStatic",
            fields=[],
            options={
                "verbose_name": "Plugin Meta (Static)",
                "verbose_name_plural": "Plugin Meta (Static)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("plugin.pluginmeta",),
        ),
    ]
