# Generated by Django 5.1.7 on 2025-05-16 14:53
# pylint: disable=missing-module-docstring,missing-function-docstring,missing-class-docstring


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_pluginmetaapi_pluginmetasql_pluginmetastatic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailcontactlist",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="emailcontactlist",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
    ]
