# Generated by Django 5.1.7 on 2025-06-27 16:31
# pylint: disable=missing-module-docstring,missing-function-docstring,missing-class-docstring

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_alter_emailcontactlist_created_at_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PluginMetaApi",
        ),
        migrations.DeleteModel(
            name="PluginMetaSql",
        ),
        migrations.DeleteModel(
            name="PluginMetaStatic",
        ),
    ]
