# pylint: disable=all
# Generated by Django 6.0.5 on 2026-09-30 17:42

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models

import smarter.common.mixins.helper_mixin
import smarter.lib.django.validators
import smarter.lib.json


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0003_alter_aggregatedcharges_options"),
        ("llmclient", "0002_initial"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Guardrail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name in camelCase, e.g., 'apiKey', no special characters.",
                        max_length=255,
                        validators=[
                            smarter.lib.django.validators.SmarterValidator.validate_snake_case,
                            smarter.lib.django.validators.SmarterValidator.validate_no_spaces,
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="A brief description of this resource. Be verbose, but not too verbose.",
                        null=True,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        default="1.0.0",
                        help_text="Semantic version in the format MAJOR.MINOR.PATCH, e.g., '1.0.0'.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "annotations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        encoder=smarter.lib.json.SmarterJSONEncoder,
                        help_text="Key-value pairs for annotating this resource.",
                        null=True,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("input", "Input (the user's message)"),
                            ("output", "Output (the LLM's reply)"),
                            ("both", "Input & Output"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("pii", "PII / Personal Data"),
                            ("secrets", "Secrets / Credentials"),
                            ("prompt_injection", "Prompt Injection"),
                            ("jailbreak", "Jailbreak"),
                            ("toxicity", "Toxicity / Harassment"),
                            ("self_harm", "Self-harm"),
                            ("hallucination", "Hallucination / Factuality"),
                            ("off_topic", "Off-topic / Scope"),
                            ("compliance", "Regulatory / Compliance"),
                            ("formatting", "Formatting"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=32,
                    ),
                ),
                (
                    "strategy",
                    models.CharField(
                        choices=[
                            ("regex", "Regular Expression"),
                            ("keyword", "Keyword List"),
                            ("detector", "Built-in Detectors"),
                            ("semantic", "Semantic Similarity"),
                            ("moderation", "Moderation Model"),
                            ("llm_judge", "LLM-as-Judge"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "pattern",
                    models.TextField(
                        blank=True,
                        help_text="The regex strategy's regular expression.",
                        null=True,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="The strategy's other fields: flags, keywords, detectors, referenceTexts, categories, judgePrompt, etc.",
                        null=True,
                    ),
                ),
                (
                    "threshold",
                    models.FloatField(
                        blank=True,
                        help_text="The minimum confidence at which the semantic, moderation and llm_judge strategies trigger.",
                        null=True,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("log", "Log"),
                            ("flag", "Flag for Review"),
                            ("redact", "Redact & Continue"),
                            ("transform", "Transform & Continue"),
                            ("block", "Block"),
                            ("escalate", "Escalate to Human Review"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "replacement",
                    models.TextField(
                        blank=True,
                        help_text="What redact and transform replace each match with.",
                        null=True,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="What block returns to the user.",
                        null=True,
                    ),
                ),
                (
                    "severity",
                    models.PositiveSmallIntegerField(default=3, help_text="1 (low) to 5 (critical)."),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("enforce", "Enforce"), ("monitor", "Monitor")],
                        default="enforce",
                        max_length=16,
                    ),
                ),
                (
                    "fail_closed",
                    models.BooleanField(
                        default=False,
                        help_text="Block if the check itself fails, e.g. because the LLM provider is unavailable.",
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=100,
                        help_text="The order in which guardrails run; lower runs first.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="Tags for categorizing and organizing this resource.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Guardrails",
                "unique_together": {("user_profile", "name")},
            },
            bases=(models.Model, smarter.common.mixins.helper_mixin.SmarterHelperMixin),
        ),
        migrations.CreateModel(
            name="GuardrailEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "guardrail_name",
                    models.CharField(
                        help_text="The guardrail's name, in case it is deleted.",
                        max_length=255,
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        help_text="The prompt's session key.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("input", "Input (the user's message)"),
                            ("output", "Output (the LLM's reply)"),
                            ("both", "Input & Output"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("pii", "PII / Personal Data"),
                            ("secrets", "Secrets / Credentials"),
                            ("prompt_injection", "Prompt Injection"),
                            ("jailbreak", "Jailbreak"),
                            ("toxicity", "Toxicity / Harassment"),
                            ("self_harm", "Self-harm"),
                            ("hallucination", "Hallucination / Factuality"),
                            ("off_topic", "Off-topic / Scope"),
                            ("compliance", "Regulatory / Compliance"),
                            ("formatting", "Formatting"),
                            ("custom", "Custom"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "strategy",
                    models.CharField(
                        choices=[
                            ("regex", "Regular Expression"),
                            ("keyword", "Keyword List"),
                            ("detector", "Built-in Detectors"),
                            ("semantic", "Semantic Similarity"),
                            ("moderation", "Moderation Model"),
                            ("llm_judge", "LLM-as-Judge"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("log", "Log"),
                            ("flag", "Flag for Review"),
                            ("redact", "Redact & Continue"),
                            ("transform", "Transform & Continue"),
                            ("block", "Block"),
                            ("escalate", "Escalate to Human Review"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("enforce", "Enforce"), ("monitor", "Monitor")],
                        max_length=16,
                    ),
                ),
                (
                    "disposition",
                    models.CharField(
                        choices=[
                            ("logged", "Logged"),
                            ("flagged", "Flagged"),
                            ("redacted", "Redacted"),
                            ("transformed", "Transformed"),
                            ("blocked", "Blocked"),
                            ("escalated", "Escalated"),
                            ("monitored", "Monitored (would have acted)"),
                            ("error", "Error"),
                        ],
                        max_length=16,
                    ),
                ),
                ("severity", models.PositiveSmallIntegerField(default=3)),
                ("confidence", models.FloatField(blank=True, null=True)),
                (
                    "excerpt",
                    models.TextField(
                        blank=True,
                        help_text="What triggered the guardrail, masked for pii and secrets.",
                        null=True,
                    ),
                ),
                ("rationale", models.TextField(blank=True, null=True)),
                (
                    "error",
                    models.TextField(
                        blank=True,
                        help_text="Why the guardrail failed to run, if it did.",
                        null=True,
                    ),
                ),
                ("reviewed", models.BooleanField(default=False)),
                (
                    "guardrail",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="guardrail.guardrail",
                    ),
                ),
                (
                    "llmclient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="guardrail_events",
                        to="llmclient.llmclient",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Guardrail Events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["disposition", "reviewed"],
                        name="guardrail_g_disposi_35da56_idx",
                    )
                ],
            },
            bases=(models.Model, smarter.common.mixins.helper_mixin.SmarterHelperMixin),
        ),
    ]
