# pylint: disable=all
# Generated by Django 6.0.5 on 2026-07-12 23:55

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models

import smarter.common.mixins.helper_mixin
import smarter.lib.django.validators
import smarter.lib.json


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0003_alter_aggregatedcharges_options"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Guardrail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name in camelCase, e.g., 'apiKey', no special characters.",
                        max_length=255,
                        validators=[
                            smarter.lib.django.validators.SmarterValidator.validate_snake_case,
                            smarter.lib.django.validators.SmarterValidator.validate_no_spaces,
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="A brief description of this resource. Be verbose, but not too verbose.",
                        null=True,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        default="1.0.0",
                        help_text="Semantic version in the format MAJOR.MINOR.PATCH, e.g., '1.0.0'.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "annotations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        encoder=smarter.lib.json.SmarterJSONEncoder,
                        help_text="Key-value pairs for annotating this resource.",
                        null=True,
                    ),
                ),
                (
                    "guardrail_type",
                    models.CharField(
                        choices=[
                            ("input", "Input (pre-prompt)"),
                            ("output", "Output (post-completion)"),
                            ("both", "Input & Output"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("pii", "PII / Sensitive Data"),
                            ("jailbreak", "Jailbreak / Prompt Injection"),
                            ("toxicity", "Toxicity / Harassment"),
                            ("hallucination", "Hallucination / Factuality"),
                            ("off_topic", "Off-topic / Scope Drift"),
                            ("compliance", "Regulatory / Compliance"),
                            ("custom", "Custom"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "match_strategy",
                    models.CharField(
                        choices=[
                            ("regex", "Regex"),
                            ("keyword", "Keyword List"),
                            ("semantic", "Semantic / Embedding Similarity"),
                            ("model", "Classifier Model Call"),
                            ("llm_judge", "LLM-as-Judge"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "pattern",
                    models.TextField(
                        blank=True,
                        help_text="Regex, keyword list (newline/comma), or judge prompt template depending on match_strategy.",
                        null=True,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Strategy-specific params: similarity_threshold, model_id, temperature, few-shot examples, etc.",
                        null=True,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("allow", "Allow (log only)"),
                            ("flag", "Flag for Review"),
                            ("redact", "Redact & Continue"),
                            ("transform", "Transform/Rewrite"),
                            ("block", "Block Request"),
                            ("escalate", "Escalate to Human"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "severity",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="1=low ... 5=critical; drives alerting/escalation thresholds.",
                    ),
                ),
                (
                    "confidence_threshold",
                    models.FloatField(
                        blank=True,
                        help_text="Minimum confidence score to trigger action, for model/semantic strategies.",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_blocking",
                    models.BooleanField(
                        default=False,
                        help_text="If False, action runs in shadow/log-only mode regardless of `action`.",
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=100,
                        help_text="Execution order when multiple guardrails match; lower runs first.",
                    ),
                ),
                (
                    "fallback_message",
                    models.TextField(
                        blank=True,
                        help_text="User-facing message returned when action=BLOCK.",
                        null=True,
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="Tags for categorizing and organizing this resource.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Guardrails",
                "unique_together": {("user_profile", "name")},
            },
            bases=(models.Model, smarter.common.mixins.helper_mixin.SmarterHelperMixin),
        ),
    ]
