apiVersion: smarter.sh/v1
kind: AuthToken
metadata:
  description: An example Smarter API manifest for a SmarterAuthToken
  name: snake-case-name
  version: 1.0.0
spec:
  config:
    isActive: true
    username: valid_smarter_username
