apiVersion: smarter.sh/v1
kind: Secret
metadata:
  annotations: []
  description: an example secret manifest for the Smarter API Secret
  name: example_secret
  tags:
    - example
    - secret
  version: 1.0.0
spec:
  config:
    expiration_date: 2026-06-05
    value: <** your unencrypted credential value **>
