# Generated by Django 6.0.8 on 2026-10-06 19:38

from django.db import migrations, models

import smarter.common.mixins.helper_mixin


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InfrastructureResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "provider",
                    models.CharField(help_text="The cloud provider, e.g. aws.", max_length=32),
                ),
                (
                    "service",
                    models.CharField(help_text="The infrastructure service, e.g. dns.", max_length=32),
                ),
                (
                    "resource_type",
                    models.CharField(help_text="The kind of resource, e.g. dns.zone.", max_length=64),
                ),
                (
                    "resource_name",
                    models.CharField(
                        help_text="The resource's name, e.g. example.com.",
                        max_length=255,
                    ),
                ),
                (
                    "resource_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The provider's id of the resource, if any.",
                        max_length=512,
                    ),
                ),
                (
                    "billable",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the provider bills for the resource.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("destroyed", "Destroyed")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("destroyed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Infrastructure Resource",
                "verbose_name_plural": "Infrastructure Resources",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["provider", "resource_type", "resource_name"],
                        name="infrastruct_provide_01a2bb_idx",
                    ),
                    models.Index(
                        fields=["status", "billable"],
                        name="infrastruct_status_c33cc2_idx",
                    ),
                ],
            },
            bases=(models.Model, smarter.common.mixins.helper_mixin.SmarterHelperMixin),
        ),
    ]
