# pylint: disable=all
# Generated by Django 5.2.7 on 2026-01-25 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import smarter.lib.json


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SAMJournal",
            fields=[
                (
                    "key",
                    models.CharField(
                        default=None,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "thing",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Plugin", "Plugin"),
                            ("ApiPlugin", "ApiPlugin"),
                            ("SqlPlugin", "SqlPlugin"),
                            ("ApiConnection", "ApiConnection"),
                            ("SqlConnection", "SqlConnection"),
                            ("Account", "Account"),
                            ("AuthToken", "AuthToken"),
                            ("User", "User"),
                            ("Chat", "Chat"),
                            ("ChatConfig", "ChatConfig"),
                            ("ChatHistory", "ChatHistory"),
                            ("ChatPluginUsage", "ChatPluginUsage"),
                            ("ChatToolCall", "ChatToolCall"),
                            ("Chatbot", "Chatbot"),
                            ("Provider", "Provider"),
                            ("Secret", "Secret"),
                        ],
                        default="Chat",
                        max_length=24,
                    ),
                ),
                (
                    "command",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("apply", "apply"),
                            ("chat", "chat"),
                            ("chat_config", "chat_config"),
                            ("delete", "delete"),
                            ("deploy", "deploy"),
                            ("describe", "describe"),
                            ("get", "get"),
                            ("journal", "journal"),
                            ("logs", "logs"),
                            ("example_manifest", "example_manifest"),
                            ("status", "status"),
                            ("schema", "schema"),
                            ("version", "version"),
                            ("undeploy", "undeploy"),
                            ("whoami", "whoami"),
                        ],
                        default="chat",
                        max_length=24,
                    ),
                ),
                (
                    "request",
                    models.JSONField(encoder=smarter.lib.json.SmarterJSONEncoder),
                ),
                (
                    "response",
                    models.JSONField(encoder=smarter.lib.json.SmarterJSONEncoder),
                ),
                ("status_code", models.PositiveSmallIntegerField(default=200)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
