# pylint: disable=missing-module-docstring,missing-function-docstring,missing-class-docstring
# Generated by Django 5.0.4 on 2024-04-23 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "session_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name_plural": "Chats",
            },
        ),
        migrations.CreateModel(
            name="ChatHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("request", models.JSONField(blank=True, null=True)),
                ("response", models.JSONField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Chat Histories",
            },
        ),
        migrations.CreateModel(
            name="ChatToolCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "function_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "function_args",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("request", models.JSONField(blank=True, null=True)),
                ("response", models.JSONField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Chat Tool Call Histories",
            },
        ),
        migrations.CreateModel(
            name="PluginUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("input_text", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Plugin Selection Histories",
            },
        ),
    ]
