# -*- coding: utf-8 -*-
# pylint: disable=missing-module-docstring,missing-module-docstring,missing-function-docstring,missing-class-docstring
# Generated by Django 5.0.2 on 2024-02-26 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("plugin", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("input_text", models.TextField(blank=True, null=True)),
                ("model", models.CharField(blank=True, max_length=255, null=True)),
                ("messages", models.JSONField(blank=True, null=True)),
                ("tools", models.JSONField(blank=True, max_length=255, null=True)),
                ("temperature", models.FloatField(blank=True, null=True)),
                ("max_tokens", models.IntegerField(blank=True, null=True)),
                ("response", models.JSONField(blank=True, null=True)),
                ("response_id", models.CharField(blank=True, max_length=255, null=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name_plural": "Chat History",
            },
        ),
        migrations.CreateModel(
            name="ChatToolCallHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.CharField(
                        blank=True, choices=[("called", "Called"), ("received", "Received")], max_length=255, null=True
                    ),
                ),
                ("input_text", models.TextField(blank=True, null=True)),
                ("model", models.CharField(blank=True, max_length=255, null=True)),
                ("messages", models.JSONField(blank=True, null=True)),
                ("response", models.JSONField(blank=True, null=True)),
                ("response_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "plugin",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="plugin.pluginmeta"
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name_plural": "Chat Tool Call History",
            },
        ),
        migrations.CreateModel(
            name="PluginUsageHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.CharField(
                        blank=True, choices=[("selected", "Selected"), ("called", "Called")], max_length=255, null=True
                    ),
                ),
                ("data", models.JSONField(blank=True, null=True)),
                ("model", models.CharField(blank=True, max_length=255, null=True)),
                ("messages", models.JSONField(blank=True, null=True)),
                ("temperature", models.FloatField(blank=True, null=True)),
                ("max_tokens", models.IntegerField(blank=True, null=True)),
                ("custom_tool", models.JSONField(blank=True, null=True)),
                ("input_text", models.TextField(blank=True, null=True)),
                ("inquiry_type", models.CharField(blank=True, max_length=255, null=True)),
                ("inquiry_return", models.TextField(blank=True, null=True)),
                ("plugin", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="plugin.pluginmeta")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name_plural": "Plugin Selection History",
            },
        ),
    ]
