# -*- coding: utf-8 -*-
# pylint: disable=C0114,C0115
# Generated by Django 5.0.2 on 2024-03-01 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chat", "0001_initial"),
        ("plugin", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chattoolcallhistory",
            name="plugin",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="plugin.pluginmeta"
            ),
        ),
        migrations.AddField(
            model_name="chattoolcallhistory",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="pluginusagehistory",
            name="plugin",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="plugin.pluginmeta"),
        ),
        migrations.AddField(
            model_name="pluginusagehistory",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
