# Generated by Django 5.1.3 on 2025-01-28 19:49
# pylint: disable=missing-module-docstring,missing-function-docstring,missing-class-docstring

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_alter_accountcontact_unique_together"),
        ("chat", "0005_chathistory_messages"),
        ("chatbot", "0006_alter_chatbotrequests_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="account",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="account.account"),
        ),
        migrations.AlterField(
            model_name="chat",
            name="chatbot",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="chatbot.chatbot"),
        ),
        migrations.AlterField(
            model_name="chat",
            name="ip_address",
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name="chat",
            name="session_key",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="chat",
            name="url",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="chat",
            name="user_agent",
            field=models.CharField(max_length=255),
        ),
    ]
