# pylint: disable=all
# Generated by Django 5.2.7 on 2026-01-25 15:29

import django.core.validators
import django.db.models.deletion
import taggit.managers
from django.db import migrations, models

import smarter.apps.plugin.models
import smarter.common.mixins
import smarter.lib.django.model_helpers
import smarter.lib.django.validators
import smarter.lib.json


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0001_initial"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PluginDataBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="A brief description of what this plugin returns. Be verbose, but not too verbose."
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=smarter.lib.json.SmarterJSONEncoder,
                        help_text="A JSON dict containing parameter names and data types. Example: {'required': [], 'properties': {'max_cost': {'type': 'float', 'description': 'the maximum cost that a student is willing to pay for a course.'}, 'description': {'enum': ['AI', 'mobile', 'web', 'database', 'network', 'neural networks'], 'type': 'string', 'description': 'areas of specialization for courses in the catalogue.'}}}",
                        null=True,
                        validators=[smarter.apps.plugin.models.validate_openai_parameters_dict],
                    ),
                ),
                (
                    "test_values",
                    models.JSONField(
                        blank=True,
                        encoder=smarter.lib.json.SmarterJSONEncoder,
                        help_text="A JSON dict containing test values for each parameter. Example: {'city': 'San Francisco'}",
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, smarter.common.mixins.SmarterHelperMixin),
        ),
        migrations.CreateModel(
            name="ApiConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name in camelCase, e.g., 'apiKey', no special characters.",
                        max_length=255,
                        validators=[
                            smarter.lib.django.validators.SmarterValidator.validate_snake_case,
                            smarter.lib.django.model_helpers.validate_no_spaces,
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="A brief description of this resource. Be verbose, but not too verbose.",
                    ),
                ),
                ("version", models.CharField(default="1.0.0", max_length=255)),
                (
                    "annotations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        encoder=smarter.lib.json.SmarterJSONEncoder,
                        help_text="Key-value pairs for annotating this resource.",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("SqlConnection", "SqlConnection"),
                            ("ApiConnection", "ApiConnection"),
                        ],
                        help_text="The kind of connection. Example: 'SQL', 'API'.",
                        max_length=50,
                    ),
                ),
                (
                    "base_url",
                    models.URLField(help_text="The root domain of the API. Example: 'https://api.example.com'."),
                ),
                (
                    "auth_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "None"),
                            ("basic", "Basic Auth"),
                            ("token", "Token Auth"),
                            ("oauth", "OAuth"),
                        ],
                        default="none",
                        help_text="The authentication method to use. Example: 'Basic Auth', 'Token Auth'.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "timeout",
                    models.IntegerField(
                        blank=True,
                        default=30,
                        help_text="The timeout for the API request in seconds. Default is 30 seconds.",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "proxy_protocol",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("http", "HTTP"),
                            ("https", "HTTPS"),
                            ("socks", "SOCKS"),
                        ],
                        default="http",
                        help_text="The protocol to use for the proxy connection.",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("proxy_host", models.CharField(blank=True, max_length=255, null=True)),
                ("proxy_port", models.IntegerField(blank=True, null=True)),
                (
                    "proxy_username",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "api_key",
                    models.ForeignKey(
                        blank=True,
                        help_text="The API key for authentication, if required.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_connections_api_key",
                        to="account.secret",
                    ),
                ),
                (
                    "proxy_password",
                    models.ForeignKey(
                        blank=True,
                        help_text="The proxy password for authentication, if required.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_connections_proxy_password",
                        to="account.secret",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="Tags for categorizing and organizing this resource.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="account.userprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, smarter.common.mixins.SmarterHelperMixin),
        ),
        migrations.CreateModel(
            name="PluginDataStatic",
            fields=[
                (
                    "plugindatabase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="plugin.plugindatabase",
                    ),
                ),
                (
                    "static_data",
                    models.JSONField(
                        default=dict,
                        encoder=smarter.lib.json.SmarterJSONEncoder,
                        help_text="The JSON data that this plugin returns to OpenAI API when invoked by the user prompt.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plugin Static Data",
                "verbose_name_plural": "Plugin Static Data",
            },
            bases=("plugin.plugindatabase",),
        ),
        migrations.CreateModel(
            name="PluginMeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name in camelCase, e.g., 'apiKey', no special characters.",
                        max_length=255,
                        validators=[
                            smarter.lib.django.validators.SmarterValidator.validate_snake_case,
                            smarter.lib.django.model_helpers.validate_no_spaces,
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="A brief description of this resource. Be verbose, but not too verbose.",
                    ),
                ),
                ("version", models.CharField(default="1.0.0", max_length=255)),
                (
                    "annotations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        encoder=smarter.lib.json.SmarterJSONEncoder,
                        help_text="Key-value pairs for annotating this resource.",
                    ),
                ),
                (
                    "plugin_class",
                    models.CharField(
                        choices=[("static", "static"), ("sql", "sql"), ("api", "api")],
                        default="PluginMeta",
                        help_text="The class name of the plugin",
                        max_length=255,
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="Tags for categorizing and organizing this resource.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="account.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plugin",
                "verbose_name_plural": "Plugins",
                "unique_together": {("user_profile", "name")},
            },
            bases=(models.Model, smarter.common.mixins.SmarterHelperMixin),
        ),
        migrations.AddField(
            model_name="plugindatabase",
            name="plugin",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plugin_data_base_plugin",
                to="plugin.pluginmeta",
            ),
        ),
        migrations.CreateModel(
            name="PluginMetaApi",
            fields=[],
            options={
                "verbose_name": "Plugin Meta (API)",
                "verbose_name_plural": "Plugin Meta (API)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("plugin.pluginmeta",),
        ),
        migrations.CreateModel(
            name="PluginMetaSql",
            fields=[],
            options={
                "verbose_name": "Plugin Meta (SQL)",
                "verbose_name_plural": "Plugin Meta (SQL)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("plugin.pluginmeta",),
        ),
        migrations.CreateModel(
            name="PluginMetaStatic",
            fields=[],
            options={
                "verbose_name": "Plugin Meta (Static)",
                "verbose_name_plural": "Plugin Meta (Static)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("plugin.pluginmeta",),
        ),
        migrations.CreateModel(
            name="PluginPrompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "provider",
                    models.TextField(
                        blank=True,
                        default="openai",
                        help_text="The name of the LLM provider for the plugin. Example: 'openai'.",
                        null=True,
                    ),
                ),
                (
                    "system_role",
                    models.TextField(
                        blank=True,
                        default="You are a helful assistant.",
                        help_text="The role of the system in the conversation.",
                        null=True,
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        default="gpt-4o-mini",
                        help_text="The model to use for the completion.",
                        max_length=255,
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(
                        default=0.5,
                        help_text="The higher the temperature, the more creative the result.",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "max_completion_tokens",
                    models.IntegerField(
                        default=2048,
                        help_text="The maximum number of tokens for both input and output.",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(8192),
                        ],
                    ),
                ),
                (
                    "plugin",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plugin_prompt_plugin",
                        to="plugin.pluginmeta",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, smarter.common.mixins.SmarterHelperMixin),
        ),
        migrations.CreateModel(
            name="PluginSelector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "directive",
                    models.CharField(
                        choices=[
                            ("search_terms", "search_terms"),
                            ("always", "always"),
                            ("llm", "llm"),
                        ],
                        default="search_terms",
                        help_text="The selection strategy to use for this plugin.",
                        max_length=255,
                    ),
                ),
                (
                    "search_terms",
                    models.JSONField(
                        blank=True,
                        default=list,
                        encoder=smarter.lib.json.SmarterJSONEncoder,
                        help_text="search terms in JSON format that, if detected in the user prompt, will incentivize Smarter to load this plugin.",
                        null=True,
                    ),
                ),
                (
                    "plugin",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plugin_selector_plugin",
                        to="plugin.pluginmeta",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, smarter.common.mixins.SmarterHelperMixin),
        ),
        migrations.CreateModel(
            name="PluginSelectorHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "search_term",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "messages",
                    models.JSONField(
                        blank=True,
                        default=list,
                        encoder=smarter.lib.json.SmarterJSONEncoder,
                        help_text="The user prompt messages.",
                        null=True,
                    ),
                ),
                (
                    "session_key",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "plugin_selector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plugin_selector_history_plugin_selector",
                        to="plugin.pluginselector",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Plugin Selector History",
            },
            bases=(models.Model, smarter.common.mixins.SmarterHelperMixin),
        ),
        migrations.CreateModel(
            name="SqlConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name in camelCase, e.g., 'apiKey', no special characters.",
                        max_length=255,
                        validators=[
                            smarter.lib.django.validators.SmarterValidator.validate_snake_case,
                            smarter.lib.django.model_helpers.validate_no_spaces,
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="A brief description of this resource. Be verbose, but not too verbose.",
                    ),
                ),
                ("version", models.CharField(default="1.0.0", max_length=255)),
                (
                    "annotations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        encoder=smarter.lib.json.SmarterJSONEncoder,
                        help_text="Key-value pairs for annotating this resource.",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("SqlConnection", "SqlConnection"),
                            ("ApiConnection", "ApiConnection"),
                        ],
                        help_text="The kind of connection. Example: 'SQL', 'API'.",
                        max_length=50,
                    ),
                ),
                (
                    "db_engine",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("django.db.backends.mysql", "django.db.backends.mysql"),
                            (
                                "django.db.backends.postgresql",
                                "django.db.backends.postgresql",
                            ),
                            (
                                "django.db.backends.sqlite3",
                                "django.db.backends.sqlite3",
                            ),
                            ("django.db.backends.oracle", "django.db.backends.oracle"),
                            ("django.db.backends.mssql", "django.db.backends.mssql"),
                            ("django.db.backends.sybase", "django.db.backends.sybase"),
                        ],
                        default="django.db.backends.mysql",
                        help_text="The type of database management system. Example: 'MySQL', 'PostgreSQL', 'MS SQL Server', 'Oracle'.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "authentication_method",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("tcpip", "Tcpip"),
                            ("tcpip_ssh", "Tcpip Ssh"),
                            ("ldap_user_pwd", "Ldap User Pwd"),
                        ],
                        default="tcpip",
                        help_text="The authentication method to use for the connection. Example: 'Standard TCP/IP', 'Standard TCP/IP over SSH', 'LDAP User/Password'.",
                        max_length=255,
                    ),
                ),
                (
                    "timeout",
                    models.IntegerField(
                        blank=True,
                        default=30,
                        help_text="The timeout for the database connection in seconds. Default is 30 seconds.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "use_ssl",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="Whether to use SSL/TLS for the connection.",
                        null=True,
                    ),
                ),
                (
                    "ssl_cert",
                    models.TextField(
                        blank=True,
                        help_text="The SSL certificate for the connection, if required.",
                        null=True,
                    ),
                ),
                (
                    "ssl_key",
                    models.TextField(
                        blank=True,
                        help_text="The SSL key for the connection, if required.",
                        null=True,
                    ),
                ),
                (
                    "ssl_ca",
                    models.TextField(
                        blank=True,
                        help_text="The Certificate Authority (CA) certificate for verifying the server.",
                        null=True,
                    ),
                ),
                (
                    "hostname",
                    models.CharField(
                        help_text="The remote host of the SQL connection. Should be a valid internet domain name.",
                        max_length=255,
                    ),
                ),
                (
                    "port",
                    models.IntegerField(
                        blank=True,
                        default=3306,
                        help_text="The port of the SQL connection. example: 3306 for MySQL.",
                        null=True,
                    ),
                ),
                (
                    "database",
                    models.CharField(
                        help_text="The name of the database to connect to.",
                        max_length=255,
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        help_text="The database username.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "pool_size",
                    models.IntegerField(
                        blank=True,
                        default=5,
                        help_text="The size of the connection pool.",
                        null=True,
                    ),
                ),
                (
                    "max_overflow",
                    models.IntegerField(
                        blank=True,
                        default=10,
                        help_text="The maximum number of connections to allow beyond the pool size.",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "proxy_protocol",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("http", "HTTP"),
                            ("https", "HTTPS"),
                            ("socks", "SOCKS"),
                        ],
                        default="http",
                        help_text="The protocol to use for the proxy connection.",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "proxy_host",
                    models.CharField(
                        blank=True,
                        help_text="The remote host of the SQL proxy connection. Should be a valid internet domain name.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "proxy_port",
                    models.IntegerField(
                        blank=True,
                        help_text="The port of the SQL proxy connection.",
                        null=True,
                    ),
                ),
                (
                    "proxy_username",
                    models.CharField(
                        blank=True,
                        help_text="The username for the proxy connection.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "ssh_known_hosts",
                    models.TextField(
                        blank=True,
                        help_text="The known_hosts file content for verifying SSH connections. Usually comes from ~/.ssh/known_hosts.",
                        null=True,
                    ),
                ),
                (
                    "password",
                    models.ForeignKey(
                        blank=True,
                        help_text="The password for authentication, if required.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sql_connections_password",
                        to="account.secret",
                    ),
                ),
                (
                    "proxy_password",
                    models.ForeignKey(
                        blank=True,
                        help_text="The API key for authentication, if required.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sql_connections_proxy_password",
                        to="account.secret",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="Tags for categorizing and organizing this resource.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="account.userprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, smarter.common.mixins.SmarterHelperMixin),
        ),
        migrations.CreateModel(
            name="PluginDataApi",
            fields=[
                (
                    "plugindatabase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="plugin.plugindatabase",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GET", "GET"),
                            ("POST", "POST"),
                            ("PUT", "PUT"),
                            ("DELETE", "DELETE"),
                        ],
                        default="GET",
                        help_text="The HTTP method to use for the API request. Example: 'GET', 'POST'.",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "endpoint",
                    models.CharField(
                        help_text="The endpoint path for the API. Example: '/v1/weather'.",
                        max_length=255,
                    ),
                ),
                (
                    "url_params",
                    models.JSONField(
                        blank=True,
                        encoder=smarter.lib.json.SmarterJSONEncoder,
                        help_text="A JSON dict containing URL parameters. Example: {'city': 'San Francisco', 'state': 'CA'}",
                        null=True,
                    ),
                ),
                (
                    "headers",
                    models.JSONField(
                        blank=True,
                        encoder=smarter.lib.json.SmarterJSONEncoder,
                        help_text="A JSON dict containing headers to be sent with the API request. Example: {'Authorization': 'Bearer <token>'}",
                        null=True,
                    ),
                ),
                (
                    "body",
                    models.JSONField(
                        blank=True,
                        encoder=smarter.lib.json.SmarterJSONEncoder,
                        help_text="A JSON dict containing the body of the API request, if applicable.",
                        null=True,
                    ),
                ),
                (
                    "limit",
                    models.IntegerField(
                        blank=True,
                        help_text="The maximum number of rows to return from the API response.",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        help_text="The API connection associated with this plugin.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plugin_data_api_connection",
                        to="plugin.apiconnection",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("plugin.plugindatabase",),
        ),
        migrations.CreateModel(
            name="PluginDataSql",
            fields=[
                (
                    "plugindatabase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="plugin.plugindatabase",
                    ),
                ),
                (
                    "sql_query",
                    models.TextField(
                        help_text="The SQL query that this plugin will execute when invoked by the user prompt."
                    ),
                ),
                (
                    "limit",
                    models.IntegerField(
                        blank=True,
                        help_text="The maximum number of rows to return from the query.",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plugin_data_sql_connection",
                        to="plugin.sqlconnection",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("plugin.plugindatabase",),
        ),
    ]
