# -*- coding: utf-8 -*-
# pylint: disable=C0114,C0115,C0116
# Generated by Django 5.0.2 on 2024-02-16 23:49

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0001_initial"),
        ("taggit", "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="PluginMeta",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(default="PluginMeta", max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("version", models.CharField(default="1.0.0", max_length=255)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plugins",
                        to="account.account",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plugins",
                        to="account.userprofile",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plugin",
                "verbose_name_plural": "Plugins",
            },
        ),
        migrations.CreateModel(
            name="PluginData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("return_data", models.JSONField(default=dict)),
                (
                    "plugin",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="plugin_data", to="plugin.pluginmeta"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PluginPrompt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("system_role", models.TextField(blank=True, null=True)),
                ("model", models.CharField(default="gpt-3.5-turbo-1106", max_length=255)),
                ("temperature", models.FloatField(default=0.5)),
                ("max_tokens", models.IntegerField(default=256)),
                (
                    "plugin",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="prompt", to="plugin.pluginmeta"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PluginSelector",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("directive", models.CharField(default="search_terms", max_length=255)),
                ("search_terms", models.JSONField(default=list)),
                (
                    "plugin",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="selector", to="plugin.pluginmeta"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
