# Generated by Django 5.1.3 on 2024-12-30 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plugin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pluginprompt",
            name="provider",
            field=models.TextField(
                blank=True,
                default="openai",
                help_text="The name of the LLM provider for the plugin. Example: 'openai'.",
                null=True,
            ),
        ),
    ]
