# Generated by Django 5.0.4 on 2024-05-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plugin", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pluginmeta",
            name="name",
            field=models.CharField(
                help_text="The name of the plugin. Example: 'HR Policy Update' or 'Public Relation Talking Points'.",
                max_length=255,
            ),
        ),
    ]
