# pylint: disable=all
# Generated by Django 6.0.5 on 2026-07-07 15:48

import django.db.models.deletion
from django.db import migrations, models

import smarter.lib.json


class Migration(migrations.Migration):

    dependencies = [
        ("plugin", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PluginDataSkill",
            fields=[
                (
                    "plugindatabase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="plugin.plugindatabase",
                    ),
                ),
                (
                    "skill_document",
                    models.TextField(
                        help_text="The raw contents of the SKILL.md file for this plugin: a YAML frontmatter block (name, description, and optionally license and allowed-tools) followed by a Markdown body containing the instructions returned to the LLM when this plugin is invoked by the user prompt."
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=smarter.lib.json.SmarterJSONEncoder,
                        help_text="Parsed YAML frontmatter from skill_document (name, description, license, allowed-tools, and any additional custom keys).",
                    ),
                ),
                (
                    "allowed_tools",
                    models.JSONField(
                        blank=True,
                        default=list,
                        encoder=smarter.lib.json.SmarterJSONEncoder,
                        help_text="Optional list of tool names this skill is permitted to invoke, mirroring the SKILL.md 'allowed-tools' frontmatter key.",
                    ),
                ),
                (
                    "resources",
                    models.JSONField(
                        blank=True,
                        default=list,
                        encoder=smarter.lib.json.SmarterJSONEncoder,
                        help_text="Optional list of bundled resource file references (e.g. scripts/, references/, assets/ paths) that accompany this skill, expressed as relative paths.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plugin Skill Data",
                "verbose_name_plural": "Plugin Skill Data",
            },
            bases=("plugin.plugindatabase",),
        ),
        migrations.AlterField(
            model_name="pluginmeta",
            name="plugin_class",
            field=models.CharField(
                choices=[
                    ("api", "api"),
                    ("skill", "skill"),
                    ("sql", "sql"),
                    ("static", "static"),
                ],
                default="PluginMeta",
                help_text="The class name of the plugin",
                max_length=255,
            ),
        ),
    ]
