# Generated by Django 5.1.3 on 2025-01-09 18:52
# pylint: disable=missing-module-docstring,missing-function-docstring,missing-class-docstring

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plugin", "0002_pluginprompt_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="pluginselectorhistory",
            name="session_key",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
