# pylint: disable=all
# Generated by Django 5.2.10 on 2026-03-14 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plugin", "0002_alter_apiconnection_annotations_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apiconnection",
            name="version",
            field=models.CharField(
                blank=True,
                default="1.0.0",
                help_text="Semantic version in the format MAJOR.MINOR.PATCH, e.g., '1.0.0'.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pluginmeta",
            name="version",
            field=models.CharField(
                blank=True,
                default="1.0.0",
                help_text="Semantic version in the format MAJOR.MINOR.PATCH, e.g., '1.0.0'.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sqlconnection",
            name="version",
            field=models.CharField(
                blank=True,
                default="1.0.0",
                help_text="Semantic version in the format MAJOR.MINOR.PATCH, e.g., '1.0.0'.",
                max_length=255,
                null=True,
            ),
        ),
    ]
