# Generated by Django 5.1.3 on 2025-02-10 17:49
# pylint: disable=missing-module-docstring,missing-function-docstring,missing-class-docstring

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plugin", "0003_pluginselectorhistory_session_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pluginprompt",
            name="max_tokens",
            field=models.IntegerField(
                default=2048,
                help_text="The maximum number of tokens for both input and output.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(8192),
                ],
            ),
        ),
    ]
