# pylint: disable=all
"""
PluginDataWebsearch: the configuration of the experimental WebsearchPlugin, its admin proxy.

model, and the websearch plugin class.
"""

# Generated by Django 6.0.5 on 2026-09-30 01:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import smarter.lib.json


class Migration(migrations.Migration):

    dependencies = [
        ("plugin", "0003_plugindataskill_source_resources"),
        ("secret", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PluginMetaWebsearch",
            fields=[],
            options={
                "verbose_name": "Plugin Meta (Websearch)",
                "verbose_name_plural": "Plugin Meta (Websearch)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("plugin.pluginmeta",),
        ),
        migrations.AlterField(
            model_name="pluginmeta",
            name="plugin_class",
            field=models.CharField(
                choices=[
                    ("api", "api"),
                    ("skill", "skill"),
                    ("sql", "sql"),
                    ("static", "static"),
                    ("websearch", "websearch"),
                ],
                default="PluginMeta",
                help_text="The class name of the plugin",
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="PluginDataWebsearch",
            fields=[
                (
                    "plugindatabase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="plugin.plugindatabase",
                    ),
                ),
                (
                    "search_provider",
                    models.CharField(
                        blank=True,
                        choices=[("brave", "brave"), ("tavily", "tavily")],
                        help_text="The web search API. Null if web search is disabled.",
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "search_max_results",
                    models.PositiveSmallIntegerField(
                        default=5,
                        help_text="The maximum number of results per search.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                (
                    "search_safe_search",
                    models.CharField(
                        choices=[
                            ("off", "off"),
                            ("moderate", "moderate"),
                            ("strict", "strict"),
                        ],
                        default="moderate",
                        help_text="Adult content filtering of search results.",
                        max_length=16,
                    ),
                ),
                (
                    "search_country",
                    models.CharField(
                        blank=True,
                        help_text="An ISO 3166-1 alpha-2 country code, to localize results.",
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "search_language",
                    models.CharField(
                        blank=True,
                        help_text="An ISO 639-1 language code, to localize results.",
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "search_freshness",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("day", "day"),
                            ("week", "week"),
                            ("month", "month"),
                            ("year", "year"),
                        ],
                        help_text="By default, restrict results to those published within the last day, week, month or year.",
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "fetch_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the plugin can read web pages by URL.",
                    ),
                ),
                (
                    "fetch_max_characters",
                    models.PositiveIntegerField(
                        default=20000,
                        help_text="The maximum number of characters of a web page to return.",
                        validators=[
                            django.core.validators.MinValueValidator(1000),
                            django.core.validators.MaxValueValidator(100000),
                        ],
                    ),
                ),
                (
                    "fetch_respect_robots_txt",
                    models.BooleanField(
                        default=True,
                        help_text="Whether to obey websites' robots.txt files.",
                    ),
                ),
                (
                    "allowed_domains",
                    models.JSONField(
                        blank=True,
                        default=list,
                        encoder=smarter.lib.json.SmarterJSONEncoder,
                        help_text="If not empty, only these domains, and their subdomains, may be searched and read.",
                    ),
                ),
                (
                    "blocked_domains",
                    models.JSONField(
                        blank=True,
                        default=list,
                        encoder=smarter.lib.json.SmarterJSONEncoder,
                        help_text="These domains, and their subdomains, are never searched nor read.",
                    ),
                ),
                (
                    "timeout",
                    models.PositiveSmallIntegerField(
                        default=15,
                        help_text="Seconds to wait for each web request.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(60),
                        ],
                    ),
                ),
                (
                    "cache_ttl",
                    models.PositiveIntegerField(
                        default=900,
                        help_text="Seconds to cache search results and web pages. 0 disables caching.",
                        validators=[django.core.validators.MaxValueValidator(86400)],
                    ),
                ),
                (
                    "search_api_key",
                    models.ForeignKey(
                        blank=True,
                        help_text="The Secret that contains the web search API's api key.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plugin_data_websearch_api_key",
                        to="secret.secret",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plugin Websearch Data",
                "verbose_name_plural": "Plugin Websearch Data",
            },
            bases=("plugin.plugindatabase",),
        ),
    ]
