# pylint: disable=all
# Generated by Django 5.2.10 on 2026-03-25 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_alter_account_version_alter_secret_version_and_more"),
        (
            "plugin",
            "0003_alter_apiconnection_version_alter_pluginmeta_version_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apiconnection",
            options={
                "verbose_name": "API Connection",
                "verbose_name_plural": "API Connections",
            },
        ),
        migrations.AlterModelOptions(
            name="sqlconnection",
            options={
                "verbose_name": "SQL Connection",
                "verbose_name_plural": "SQL Connections",
            },
        ),
        migrations.AlterUniqueTogether(
            name="apiconnection",
            unique_together={("user_profile", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="sqlconnection",
            unique_together={("user_profile", "name")},
        ),
    ]
