# Generated by Django 5.1.3 on 2025-02-10 19:50
# pylint: disable=missing-module-docstring,missing-function-docstring,missing-class-docstring

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plugin", "0004_alter_pluginprompt_max_tokens"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pluginselector",
            name="search_terms",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="search terms in JSON format that, if detected in the user prompt, will incentivize Smarter to load this plugin.",
                null=True,
            ),
        ),
    ]
