# pylint: disable=all
# Generated by Django 5.2.10 on 2026-04-12 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connection", "0001_initial"),
        ("plugin", "0004_alter_apiconnection_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plugindataapi",
            name="connection",
            field=models.ForeignKey(
                help_text="The API connection associated with this plugin.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plugin_data_api_connection",
                to="connection.apiconnection",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sqlconnection",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="sqlconnection",
            name="password",
        ),
        migrations.RemoveField(
            model_name="sqlconnection",
            name="proxy_password",
        ),
        migrations.RemoveField(
            model_name="sqlconnection",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="sqlconnection",
            name="user_profile",
        ),
        migrations.AlterField(
            model_name="plugindatasql",
            name="connection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plugin_data_sql_connection",
                to="connection.sqlconnection",
            ),
        ),
        migrations.DeleteModel(
            name="ApiConnection",
        ),
        migrations.DeleteModel(
            name="SqlConnection",
        ),
    ]
