# Generated by Django 6.0.8 on 2026-10-09 12:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import smarter.lib.json


class Migration(migrations.Migration):

    dependencies = [
        ("plugin", "0004_plugindatawebsearch"),
    ]

    operations = [
        migrations.CreateModel(
            name="PluginDataImageSearch",
            fields=[
                (
                    "plugindatabase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="plugin.plugindatabase",
                    ),
                ),
                (
                    "api_key_secret_name",
                    models.CharField(
                        default="brave_search_api_key",
                        help_text="The name of the Secret that contains the Brave Search API key.",
                        max_length=255,
                    ),
                ),
                (
                    "query_terms",
                    models.CharField(
                        blank=True,
                        help_text="Search terms appended to every query that the LLM sends.",
                        max_length=400,
                        null=True,
                    ),
                ),
                (
                    "llm_search_params",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the LLM may set every search parameter in each tool call. The others are then defaults.",
                    ),
                ),
                (
                    "count",
                    models.PositiveSmallIntegerField(
                        default=10,
                        help_text="The maximum number of images per search.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        help_text="A two letter country code, or all for worldwide results.",
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "search_lang",
                    models.CharField(
                        blank=True,
                        help_text="Prefer images from content in this language, e.g. en.",
                        max_length=8,
                        null=True,
                    ),
                ),
                (
                    "safesearch",
                    models.CharField(
                        choices=[("off", "off"), ("strict", "strict")],
                        default="strict",
                        help_text="Adult content filtering: strict or off.",
                        max_length=8,
                    ),
                ),
                (
                    "spellcheck",
                    models.BooleanField(
                        default=True,
                        help_text="Whether Brave may correct the spelling of the query.",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        blank=True,
                        help_text="Only images of these file types, e.g. jpg|png.",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "min_width",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Only images at least this many pixels wide. Images of unknown width are skipped.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10000),
                        ],
                    ),
                ),
                (
                    "min_height",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Only images at least this many pixels high. Images of unknown height are skipped.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10000),
                        ],
                    ),
                ),
                (
                    "allowed_domains",
                    models.JSONField(
                        blank=True,
                        default=list,
                        encoder=smarter.lib.json.SmarterJSONEncoder,
                        help_text="If not empty, only images from web pages on these domains, and their subdomains.",
                    ),
                ),
                (
                    "blocked_domains",
                    models.JSONField(
                        blank=True,
                        default=list,
                        encoder=smarter.lib.json.SmarterJSONEncoder,
                        help_text="Never images on these domains, nor from web pages on them, including their subdomains.",
                    ),
                ),
                (
                    "validate_urls",
                    models.BooleanField(
                        default=True,
                        help_text="Only return image urls that respond to a request with HTTP 200.",
                    ),
                ),
                (
                    "timeout",
                    models.PositiveSmallIntegerField(
                        default=10,
                        help_text="Seconds to wait for each web request.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(60),
                        ],
                    ),
                ),
                (
                    "cache_ttl",
                    models.PositiveIntegerField(
                        default=900,
                        help_text="Seconds to cache search results. 0 disables caching.",
                        validators=[django.core.validators.MaxValueValidator(86400)],
                    ),
                ),
            ],
            options={
                "verbose_name": "Plugin Image Search Data",
                "verbose_name_plural": "Plugin Image Search Data",
            },
            bases=("plugin.plugindatabase",),
        ),
        migrations.CreateModel(
            name="PluginMetaImageSearch",
            fields=[],
            options={
                "verbose_name": "Plugin Meta (Image Search)",
                "verbose_name_plural": "Plugin Meta (Image Search)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("plugin.pluginmeta",),
        ),
        migrations.AlterField(
            model_name="pluginmeta",
            name="plugin_class",
            field=models.CharField(
                choices=[
                    ("api", "api"),
                    ("skill", "skill"),
                    ("sql", "sql"),
                    ("static", "static"),
                    ("websearch", "websearch"),
                    ("imagesearch", "imagesearch"),
                ],
                default="PluginMeta",
                help_text="The class name of the plugin",
                max_length=255,
            ),
        ),
    ]
