# Generated by Django 5.1.3 on 2025-02-14 13:45
# pylint: disable=missing-module-docstring,missing-function-docstring,missing-class-docstring

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plugin", "0005_alter_pluginselector_search_terms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pluginprompt",
            name="model",
            field=models.CharField(
                default="gpt-4o-mini",
                help_text="The model to use for the completion.",
                max_length=255,
            ),
        ),
    ]
