# Generated by Django 5.1.7 on 2025-05-07 19:19
# pylint: disable=missing-module-docstring,missing-function-docstring,missing-class-docstring

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plugin", "0008_sqlconnection_ssh_known_hosts_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sqlconnection",
            name="authentication_method",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("tcpip", "Tcpip"),
                    ("tcpip_ssh", "Tcpip Ssh"),
                    ("ldap_user_pwd", "Ldap User Pwd"),
                ],
                default="tcpip",
                help_text="The authentication method to use for the connection. Example: 'Standard TCP/IP', 'Standard TCP/IP over SSH', 'LDAP User/Password'.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="sqlconnection",
            name="db_engine",
            field=models.CharField(
                blank=True,
                choices=[
                    ("django.db.backends.mysql", "MySQL"),
                    ("django.db.backends.postgresql", "PostgreSQL"),
                    ("django.db.backends.sqlite3", "SQLite3"),
                    ("django.db.backends.oracle", "Oracle"),
                    ("django.db.backends.mssql", "MS SQL Server"),
                    ("django.db.backends.sybase", "Sybase"),
                ],
                default="django.db.backends.mysql",
                help_text="The type of database management system. Example: 'MySQL', 'PostgreSQL', 'MS SQL Server', 'Oracle'.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sqlconnection",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="A brief description of the connection. Be verbose, but not too verbose.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sqlconnection",
            name="max_overflow",
            field=models.IntegerField(
                blank=True,
                default=10,
                help_text="The maximum number of connections to allow beyond the pool size.",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="sqlconnection",
            name="pool_size",
            field=models.IntegerField(
                blank=True,
                default=5,
                help_text="The size of the connection pool.",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="sqlconnection",
            name="proxy_protocol",
            field=models.CharField(
                blank=True,
                choices=[("http", "HTTP"), ("https", "HTTPS"), ("socks", "SOCKS")],
                default="http",
                help_text="The protocol to use for the proxy connection.",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sqlconnection",
            name="timeout",
            field=models.IntegerField(
                blank=True,
                default=30,
                help_text="The timeout for the database connection in seconds. Default is 30 seconds.",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="sqlconnection",
            name="use_ssl",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Whether to use SSL/TLS for the connection.",
                null=True,
            ),
        ),
    ]
