# Generated by Django 5.1.7 on 2025-05-08 20:11
# pylint: disable=missing-module-docstring,missing-function-docstring,missing-class-docstring

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plugin", "0009_alter_sqlconnection_authentication_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plugindataapi",
            name="limit",
            field=models.IntegerField(
                blank=True,
                help_text="The maximum number of rows to return from the API response.",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="pluginmeta",
            name="plugin_class",
            field=models.CharField(
                choices=[("static", "static"), ("sql", "sql"), ("api", "api")],
                default="PluginMeta",
                help_text="The class name of the plugin",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="sqlconnection",
            name="pool_size",
            field=models.IntegerField(
                blank=True,
                default=5,
                help_text="The size of the connection pool.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sqlconnection",
            name="port",
            field=models.IntegerField(
                blank=True,
                default=3306,
                help_text="The port of the SQL connection. example: 3306 for MySQL.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sqlconnection",
            name="timeout",
            field=models.IntegerField(
                blank=True,
                default=30,
                help_text="The timeout for the database connection in seconds. Default is 30 seconds.",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
