# Generated by Django 5.1.7 on 2025-05-09 15:05
# pylint: disable=missing-module-docstring,missing-function-docstring,missing-class-docstring

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plugin", "0010_plugindataapi_limit_alter_pluginmeta_plugin_class_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plugindatasql",
            name="name",
        ),
    ]
