# Generated by Django 5.1.7 on 2025-05-09 17:38
# pylint: disable=missing-module-docstring,missing-function-docstring,missing-class-docstring

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plugin", "0011_remove_plugindatasql_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="plugindataapi",
            name="url_params",
            field=models.JSONField(
                blank=True,
                help_text="A JSON dict containing URL parameters. Example: {'city': 'San Francisco', 'state': 'CA'}",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="plugindataapi",
            name="body",
            field=models.JSONField(
                blank=True,
                help_text="A JSON dict containing the body of the API request, if applicable.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="plugindataapi",
            name="headers",
            field=models.JSONField(
                blank=True,
                help_text="A JSON dict containing headers to be sent with the API request. Example: {'Authorization': 'Bearer <token>'}",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="plugindataapi",
            name="parameters",
            field=models.JSONField(
                blank=True,
                help_text="A JSON dict containing parameter names and data types. Example: {'city': {'type': 'string', 'description': 'City name'}}",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="plugindataapi",
            name="test_values",
            field=models.JSONField(
                blank=True,
                help_text="A JSON dict containing test values for each parameter. Example: {'city': 'San Francisco'}",
                null=True,
            ),
        ),
    ]
