# Generated by Django 5.1.7 on 2025-05-12 18:34
# pylint: disable=missing-module-docstring,missing-function-docstring,missing-class-docstring

from django.db import migrations, models

import smarter.apps.plugin.models
import smarter.lib.django.validators


class Migration(migrations.Migration):

    dependencies = [
        ("plugin", "0012_plugindataapi_url_params_alter_plugindataapi_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apiconnection",
            name="name",
            field=models.CharField(
                help_text="The name of the API connection, camelCase, without spaces. Example: 'weatherApi', 'stockApi'.",
                max_length=255,
                validators=[
                    smarter.lib.django.validators.SmarterValidator.validate_snake_case,
                    smarter.apps.plugin.models.validate_no_spaces,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="pluginmeta",
            name="name",
            field=models.CharField(
                help_text="The name of the plugin. Example: 'HR Policy Update' or 'Public Relation Talking Points'.",
                max_length=255,
                validators=[
                    smarter.lib.django.validators.SmarterValidator.validate_snake_case,
                    smarter.apps.plugin.models.validate_no_spaces,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="sqlconnection",
            name="db_engine",
            field=models.CharField(
                blank=True,
                choices=[
                    ("django.db.backends.mysql", "django.db.backends.mysql"),
                    ("django.db.backends.postgresql", "django.db.backends.postgresql"),
                    ("django.db.backends.sqlite3", "django.db.backends.sqlite3"),
                    ("django.db.backends.oracle", "django.db.backends.oracle"),
                    ("django.db.backends.mssql", "django.db.backends.mssql"),
                    ("django.db.backends.sybase", "django.db.backends.sybase"),
                ],
                default="django.db.backends.mysql",
                help_text="The type of database management system. Example: 'MySQL', 'PostgreSQL', 'MS SQL Server', 'Oracle'.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sqlconnection",
            name="name",
            field=models.CharField(
                help_text="The name of the connection, without spaces. Example: 'HRDatabase', 'SalesDatabase', 'InventoryDatabase'.",
                max_length=255,
                validators=[
                    smarter.lib.django.validators.SmarterValidator.validate_snake_case,
                    smarter.apps.plugin.models.validate_no_spaces,
                ],
            ),
        ),
    ]
