# Generated by Django 5.1.7 on 2025-05-16 14:53
# pylint: disable=missing-module-docstring,missing-function-docstring,missing-class-docstring

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plugin", "0013_alter_apiconnection_name_alter_pluginmeta_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apiconnection",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="apiconnection",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="plugindatabase",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="plugindatabase",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="pluginmeta",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="pluginmeta",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="pluginprompt",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="pluginprompt",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="pluginselector",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="pluginselector",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="pluginselectorhistory",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="pluginselectorhistory",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="sqlconnection",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="sqlconnection",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
    ]
