# Generated by Django 5.1.7 on 2025-05-21 22:26
# pylint: disable=missing-module-docstring,missing-function-docstring,missing-class-docstring

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plugin", "0014_alter_apiconnection_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiconnection",
            name="version",
            field=models.CharField(
                blank=True,
                default="1.0.0",
                help_text="The version of the connection. Example: '1.0.0'.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sqlconnection",
            name="version",
            field=models.CharField(
                blank=True,
                default="1.0.0",
                help_text="The version of the connection. Example: '1.0.0'.",
                max_length=255,
                null=True,
            ),
        ),
    ]
