# pylint: disable=missing-module-docstring,missing-function-docstring,missing-class-docstring
# Generated by Django 5.1.7 on 2025-05-29 18:28

import django.db.models.deletion
from django.db import migrations, models

import smarter.apps.plugin.models
import smarter.lib.django.validators


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0009_alter_account_created_at_alter_account_updated_at_and_more"),
        ("plugin", "0015_apiconnection_version_sqlconnection_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiconnection",
            name="kind",
            field=models.CharField(
                choices=[
                    ("SqlConnection", "SqlConnection"),
                    ("ApiConnection", "ApiConnection"),
                ],
                default="api",
                help_text="The kind of connection. Example: 'SQL', 'API'.",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sqlconnection",
            name="kind",
            field=models.CharField(
                choices=[
                    ("SqlConnection", "SqlConnection"),
                    ("ApiConnection", "ApiConnection"),
                ],
                default="api",
                help_text="The kind of connection. Example: 'SQL', 'API'.",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="apiconnection",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_connections",
                to="account.account",
            ),
        ),
        migrations.AlterField(
            model_name="apiconnection",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="A brief description of the connection. Be verbose, but not too verbose.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="apiconnection",
            name="name",
            field=models.CharField(
                help_text="The name of the connection, without spaces. Example: 'HRDatabase', 'SalesDatabase', 'InventoryDatabase'.",
                max_length=255,
                validators=[
                    smarter.lib.django.validators.SmarterValidator.validate_snake_case,
                    smarter.apps.plugin.models.validate_no_spaces,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="sqlconnection",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sql_connections",
                to="account.account",
            ),
        ),
    ]
