# pylint: disable=missing-module-docstring,missing-function-docstring,missing-class-docstring
# Generated by Django 5.1.7 on 2025-06-01 04:48

from django.db import migrations, models

import smarter.apps.plugin.models
import smarter.lib.django.validators


class Migration(migrations.Migration):

    dependencies = [
        ("plugin", "0016_apiconnection_kind_sqlconnection_kind_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apiconnection",
            name="name",
            field=models.CharField(
                help_text="The name of the connection, without spaces. Example: 'hr_database', 'sales_db', 'inventory_api'.",
                max_length=255,
                validators=[
                    smarter.lib.django.validators.SmarterValidator.validate_snake_case,
                    smarter.apps.plugin.models.validate_no_spaces,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="sqlconnection",
            name="name",
            field=models.CharField(
                help_text="The name of the connection, without spaces. Example: 'hr_database', 'sales_db', 'inventory_api'.",
                max_length=255,
                validators=[
                    smarter.lib.django.validators.SmarterValidator.validate_snake_case,
                    smarter.apps.plugin.models.validate_no_spaces,
                ],
            ),
        ),
    ]
