# Generated by Django 5.1.7 on 2025-06-16 12:29
# pylint: disable=missing-module-docstring,missing-function-docstring,missing-class-docstring

from django.db import migrations, models

import smarter.apps.plugin.models


class Migration(migrations.Migration):

    dependencies = [
        ("plugin", "0017_alter_apiconnection_name_alter_sqlconnection_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plugindataapi",
            name="test_values",
        ),
        migrations.AlterField(
            model_name="plugindatasql",
            name="parameters",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="A JSON dict containing parameter names and data types. Example: {'unit': {'type': 'string', 'enum': ['Celsius', 'Fahrenheit'], 'description': 'The temperature unit to use. Infer this from the user's location.'}}",
                null=True,
            ),
        ),
    ]
