# Generated by Django 5.1.7 on 2025-06-23 23:43
# pylint: disable=missing-module-docstring,missing-function-docstring,missing-class-docstring

from django.db import migrations, models

import smarter.apps.plugin.models


class Migration(migrations.Migration):

    dependencies = [
        ("plugin", "0018_remove_plugindataapi_test_values_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plugindataapi",
            name="parameters",
        ),
        migrations.RemoveField(
            model_name="plugindatasql",
            name="parameters",
        ),
        migrations.AddField(
            model_name="plugindatabase",
            name="parameters",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="A JSON dict containing parameter names and data types. Example: {'required': [], 'properties': {'max_cost': {'type': 'float', 'description': 'the maximum cost that a student is willing to pay for a course.'}, 'description': {'enum': ['AI', 'mobile', 'web', 'database', 'network', 'neural networks'], 'type': 'string', 'description': 'areas of specialization for courses in the catalogue.'}}}",
                null=True,
                validators=[smarter.apps.plugin.models.validate_openai_parameters_dict],
            ),
        ),
        migrations.AlterField(
            model_name="plugindatasql",
            name="test_values",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="A JSON list containing test values for each parameter. Example: [{'name': 'description', 'value': 'AI'}, {'name': 'max_cost', 'value': '500.0'}]",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pluginselector",
            name="directive",
            field=models.CharField(
                choices=[
                    ("search_terms", "search_terms"),
                    ("always", "always"),
                    ("llm", "llm"),
                ],
                default="search_terms",
                help_text="The selection strategy to use for this plugin.",
                max_length=255,
            ),
        ),
    ]
