# Generated by Django 5.1.7 on 2025-06-26 19:00
# pylint: disable=missing-module-docstring,missing-function-docstring,missing-class-docstring


import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plugin", "0019_remove_plugindataapi_parameters_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apiconnection",
            name="auth_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", "None"),
                    ("basic", "Basic Auth"),
                    ("token", "Token Auth"),
                    ("oauth", "OAuth"),
                ],
                default="none",
                help_text="The authentication method to use. Example: 'Basic Auth', 'Token Auth'.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="apiconnection",
            name="proxy_protocol",
            field=models.CharField(
                blank=True,
                choices=[("http", "HTTP"), ("https", "HTTPS"), ("socks", "SOCKS")],
                default="http",
                help_text="The protocol to use for the proxy connection.",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="apiconnection",
            name="timeout",
            field=models.IntegerField(
                blank=True,
                default=30,
                help_text="The timeout for the API request in seconds. Default is 30 seconds.",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
