# Generated by Django 5.1.7 on 2025-06-26 19:19
# pylint: disable=missing-module-docstring,missing-function-docstring,missing-class-docstring


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plugin", "0020_alter_apiconnection_auth_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plugindataapi",
            name="test_values",
            field=models.JSONField(
                blank=True,
                help_text="A JSON dict containing test values for each parameter. Example: {'city': 'San Francisco'}",
                null=True,
            ),
        ),
    ]
