# Generated by Django 5.1.7 on 2025-06-26 19:55
# pylint: disable=missing-module-docstring,missing-function-docstring,missing-class-docstring


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plugin", "0021_plugindataapi_test_values"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plugindataapi",
            name="test_values",
        ),
        migrations.RemoveField(
            model_name="plugindatasql",
            name="test_values",
        ),
        migrations.AddField(
            model_name="plugindatabase",
            name="test_values",
            field=models.JSONField(
                blank=True,
                help_text="A JSON dict containing test values for each parameter. Example: {'city': 'San Francisco'}",
                null=True,
            ),
        ),
    ]
