# Generated by Django 5.1.7 on 2025-06-26 20:08
# pylint: disable=missing-module-docstring,missing-function-docstring,missing-class-docstring

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plugin", "0022_remove_plugindataapi_test_values_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plugindataapi",
            name="method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("GET", "GET"),
                    ("POST", "POST"),
                    ("PUT", "PUT"),
                    ("DELETE", "DELETE"),
                ],
                default="GET",
                help_text="The HTTP method to use for the API request. Example: 'GET', 'POST'.",
                max_length=10,
                null=True,
            ),
        ),
    ]
