# Generated by Django 5.2.5 on 2025-09-05 17:28
# pylint: disable=missing-module-docstring,missing-function-docstring,missing-class-docstring

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plugin", "0024_pluginmetaapi_pluginmetasql_pluginmetastatic"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pluginprompt",
            old_name="max_tokens",
            new_name="max_completion_tokens",
        ),
        migrations.AlterField(
            model_name="pluginprompt",
            name="model",
            field=models.CharField(
                default="gpt-5-nano",
                help_text="The model to use for the completion.",
                max_length=255,
            ),
        ),
    ]
