# Generated by Django 5.2.7 on 2025-12-12 13:46
# pylint: disable=missing-module-docstring,missing-function-docstring,missing-class-docstring

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "plugin",
            "0025_rename_max_tokens_pluginprompt_max_completion_tokens_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="pluginprompt",
            name="model",
            field=models.CharField(
                default="gpt-4o-mini",
                help_text="The model to use for the completion.",
                max_length=255,
            ),
        ),
    ]
