# pylint: disable=missing-module-docstring,missing-function-docstring,missing-class-docstring
# Generated by Django 5.2.7 on 2025-12-31 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0017_alter_account_country_alter_account_currency_and_more"),
        ("plugin", "0029_alter_apiconnection_name_alter_pluginmeta_name_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="pluginmeta",
            unique_together={("account", "name")},
        ),
    ]
