# pylint: disable=missing-module-docstring,missing-function-docstring,missing-class-docstring
# Generated by Django 5.2.7 on 2026-01-09 07:34

from django.db import migrations, models

import smarter.apps.plugin.models
import smarter.lib.json


class Migration(migrations.Migration):

    dependencies = [
        ("plugin", "0030_alter_pluginmeta_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apiconnection",
            name="annotations",
            field=models.JSONField(
                blank=True,
                default=list,
                encoder=smarter.lib.json.SmarterJSONEncoder,
                help_text="Key-value pairs for annotating this resource.",
            ),
        ),
        migrations.AlterField(
            model_name="apiconnection",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="A brief description of this resource. Be verbose, but not too verbose.",
            ),
        ),
        migrations.AlterField(
            model_name="apiconnection",
            name="version",
            field=models.CharField(default="1.0.0", max_length=255),
        ),
        migrations.AlterField(
            model_name="plugindataapi",
            name="body",
            field=models.JSONField(
                blank=True,
                encoder=smarter.lib.json.SmarterJSONEncoder,
                help_text="A JSON dict containing the body of the API request, if applicable.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="plugindataapi",
            name="headers",
            field=models.JSONField(
                blank=True,
                encoder=smarter.lib.json.SmarterJSONEncoder,
                help_text="A JSON dict containing headers to be sent with the API request. Example: {'Authorization': 'Bearer <token>'}",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="plugindataapi",
            name="url_params",
            field=models.JSONField(
                blank=True,
                encoder=smarter.lib.json.SmarterJSONEncoder,
                help_text="A JSON dict containing URL parameters. Example: {'city': 'San Francisco', 'state': 'CA'}",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="plugindatabase",
            name="parameters",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=smarter.lib.json.SmarterJSONEncoder,
                help_text="A JSON dict containing parameter names and data types. Example: {'required': [], 'properties': {'max_cost': {'type': 'float', 'description': 'the maximum cost that a student is willing to pay for a course.'}, 'description': {'enum': ['AI', 'mobile', 'web', 'database', 'network', 'neural networks'], 'type': 'string', 'description': 'areas of specialization for courses in the catalogue.'}}}",
                null=True,
                validators=[smarter.apps.plugin.models.validate_openai_parameters_dict],
            ),
        ),
        migrations.AlterField(
            model_name="plugindatabase",
            name="test_values",
            field=models.JSONField(
                blank=True,
                encoder=smarter.lib.json.SmarterJSONEncoder,
                help_text="A JSON dict containing test values for each parameter. Example: {'city': 'San Francisco'}",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="plugindatastatic",
            name="static_data",
            field=models.JSONField(
                default=dict,
                encoder=smarter.lib.json.SmarterJSONEncoder,
                help_text="The JSON data that this plugin returns to OpenAI API when invoked by the user prompt.",
            ),
        ),
        migrations.AlterField(
            model_name="pluginmeta",
            name="annotations",
            field=models.JSONField(
                blank=True,
                default=list,
                encoder=smarter.lib.json.SmarterJSONEncoder,
                help_text="Key-value pairs for annotating this resource.",
            ),
        ),
        migrations.AlterField(
            model_name="pluginselector",
            name="search_terms",
            field=models.JSONField(
                blank=True,
                default=list,
                encoder=smarter.lib.json.SmarterJSONEncoder,
                help_text="search terms in JSON format that, if detected in the user prompt, will incentivize Smarter to load this plugin.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pluginselectorhistory",
            name="messages",
            field=models.JSONField(
                blank=True,
                default=list,
                encoder=smarter.lib.json.SmarterJSONEncoder,
                help_text="The user prompt messages.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sqlconnection",
            name="annotations",
            field=models.JSONField(
                blank=True,
                default=list,
                encoder=smarter.lib.json.SmarterJSONEncoder,
                help_text="Key-value pairs for annotating this resource.",
            ),
        ),
        migrations.AlterField(
            model_name="sqlconnection",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="A brief description of this resource. Be verbose, but not too verbose.",
            ),
        ),
        migrations.AlterField(
            model_name="sqlconnection",
            name="version",
            field=models.CharField(default="1.0.0", max_length=255),
        ),
    ]
