name: Build production

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  ENVIRONMENT: production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        id: checkout_code
        uses: actions/checkout@v4

      - name: Deploy
        uses: ./.github/actions/build
        with:
          environment: ${{ env.ENVIRONMENT }}
