name: Deploy staging

on:
  workflow_dispatch:

env:
  ENVIRONMENT: staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        id: checkout_code
        uses: actions/checkout@v4

      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          environment: ${{ env.ENVIRONMENT }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          pinecone-api-key: ${{ secrets.PINECONE_API_KEY }}
          pinecone-environment: ${{ secrets.PINECONE_ENVIRONMENT }}
          google-maps-api-key: ${{ secrets.GOOGLE_MAPS_API_KEY }}
