---
#------------------------------------------------------------------------------
# - Build from Dockerfile
# - Run manage.py unit tests
#------------------------------------------------------------------------------
name: Send Test Email

on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-2
  ROOT_DOMAIN: "smarter.sh"

jobs:
  email:
    runs-on: ubuntu-latest
    steps:
      - name: Send email notification
        if: success() # This ensures the email is only sent if the workflow succeeds
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: email-smtp.us-east-2.amazonaws.com
          server_port: 25
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: Deployment to succeeded
          body: The deployment has completed successfully.
          to: lpm0073@gmail.com
          from: no-reply@platform.smarter.sh
