---
#------------------------------------------------------------------------------
# - Build from Dockerfile
# - Run manage.py unit tests
#------------------------------------------------------------------------------
name: Send Test Email

on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-2
  ROOT_DOMAIN: "smarter.sh"

jobs:
  email:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Send Email
        run: |
          aws ses send-email \
            --from "no-reply@platform.beta.smarter.sh" \
            --destination "ToAddresses=lpm0073@gmail.com" \
            --message "Subject={Data=Deployment succeeded,Charset=utf8},Body={Text={Data=The deployment has completed successfully.,Charset=utf8}}" \
            --reply-to-addresses "no-reply@platform.beta.smarter.sh"
