---
#------------------------------------------------------------------------------
# - Build from Dockerfile
# - Run manage.py unit tests
#------------------------------------------------------------------------------
name: Test-Build

on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-2
  ROOT_DOMAIN: "smarter.sh"
  python-version: "3.11"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v4

      - name: Check branch name
        run: |
          if [[ "${{ github.ref }}" != "refs/heads/alpha" && "${{ github.ref }}" != "refs/heads/beta" && "${{ github.ref }}" != "refs/heads/next" && "${{ github.ref }}" != "refs/heads/main" ]]; then
            echo "This workflow can only run on alpha, beta, next, or main branches"
            exit 1
          fi

      - name: Set environment variable
        id: setenv
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/alpha" ]]; then
            echo "::set-output name=environment::alpha"
          elif [[ "${{ github.ref }}" == "refs/heads/beta" ]]; then
            echo "::set-output name=environment::beta"
          elif [[ "${{ github.ref }}" == "refs/heads/next" ]]; then
            echo "::set-output name=environment::next"
          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "::set-output name=environment::production"
          fi

      - name: Test
        uses: ./.github/actions/test
        with:
          environment: ${{ steps.setenv.outputs.environment }}
          root-domain: "${{ env.ROOT_DOMAIN }}"
          python-version: "${{ env.python-version}}"
          google-maps-api-key: "${{ secrets.GOOGLE_MAPS_API_KEY }}"
          openai-api-key: "${{ secrets.OPENAI_API_KEY }}"
          pinecone-api-key: "${{ secrets.PINECONE_API_KEY }}"
          pinecone-environment: "${{ secrets.PINECONE_ENVIRONMENT }}"
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v4

      - name: Build
        uses: ./.github/actions/build
        with:
          environment: ${{ needs.test.outputs.environment }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
