# pylint: disable=W0613,C0302
"""
ChatConfigView is a Django class-based view responsible for providing
configuration data to the ReactJS chat UI component in the Smarter
web application.
"""

import logging
from http import HTTPStatus
from typing import Any, Optional, Union

from django.http import (
    HttpRequest,
    HttpResponse,
    HttpResponseNotAllowed,
    JsonResponse,
)

from smarter.apps.chatbot.models import (
    ChatBot,
    ChatBotFunctions,
    ChatBotHelper,
    ChatBotPlugin,
    ChatBotRequests,
    ChatBotRequestsSerializer,
    get_cached_chatbot_by_request,
)
from smarter.apps.chatbot.serializers import (
    ChatBotConfigSerializer,
    ChatBotFunctionsSerializer,
    ChatBotPluginSerializer,
)
from smarter.apps.plugin.models import (
    PluginSelectorHistory,
    PluginSelectorHistorySerializer,
)
from smarter.apps.prompt.signals import chat_config_invoked
from smarter.apps.prompt.views.detailview.chatapp_workbench_view import (
    SmarterChatSession,
)
from smarter.common.conf import smarter_settings
from smarter.common.const import (
    SMARTER_CHAT_SESSION_KEY_NAME,
    SmarterHttpMethods,
)
from smarter.common.helpers.url_helpers import clean_url
from smarter.common.utils import is_authenticated_request
from smarter.lib.django import waffle
from smarter.lib.django.http.shortcuts import (
    SmarterHttpResponseForbidden,
)
from smarter.lib.django.views import (
    SmarterAuthenticatedNeverCachedWebView,
)
from smarter.lib.django.waffle import SmarterWaffleSwitches
from smarter.lib.drf.views.helpers import UnauthenticatedPermissionClass
from smarter.lib.journal.enum import SmarterJournalCliCommands, SmarterJournalThings
from smarter.lib.journal.http import (
    SmarterJournaledJsonErrorResponse,
    SmarterJournaledJsonResponse,
)
from smarter.lib.logging import WaffleSwitchedLoggerWrapper

MAX_RETURNED_PLUGINS = 10


def should_log(level):
    """Check if logging should be done based on the waffle switch."""
    return waffle.switch_is_active(SmarterWaffleSwitches.PROMPT_LOGGING)


base_logger = logging.getLogger(__name__)
logger = WaffleSwitchedLoggerWrapper(base_logger, should_log)


def should_log_verbose(level):
    """Check if logging should be done based on the waffle switch."""
    return smarter_settings.verbose_logging


verbose_logger = WaffleSwitchedLoggerWrapper(base_logger, should_log_verbose)


class ChatConfigView(SmarterAuthenticatedNeverCachedWebView):
    """
    Chat configuration view for the Smarter web application.

    This view is responsible for providing all configuration information required by the ReactJS chat UI component.
    It is designed to be performant and efficient, as it is invoked on every user-facing browser load and refresh.

    **Key Features:**

    - **Django Template-Based:**
      This view uses Django's template system for rendering and does not rely on Django REST Framework (DRF) serializers for its main response.
      The configuration data is returned as a JSON response, but the view itself is structured as a Django class-based view.

    - **CSRF Exempt:**
      The view is decorated with `@csrf_exempt` because it is read-only and does not modify server-side data. This exemption is safe in this context
      and avoids unnecessary CSRF validation for GET and POST requests that only retrieve configuration data.

    - **ReactJS UI Integration:**
      The endpoint provides all necessary configuration and context information for the ReactJS chat component. This includes chatbot metadata,
      plugin information, session keys, and historical data relevant to the chat session. The React app consumes this configuration to initialize
      and render the chat UI in the user's browser.

    - **Session-Based Architecture:**
      Each chat session is uniquely identified and managed by a globally unique 64-character session key. The session key is generated by
      RequestHelper.generate_session_key() and is persisted by the browser in a domain and path-specific cookie, meaning that this design supports
      an unlimited number of concurrent sessions per user, one per device per chatbot.

    - **Performance Considerations:**
      Since this endpoint is called on every browser load and refresh, performance is a primary concern. The view is optimized to minimize database
      queries and serialization overhead. Only a limited number of plugins (as defined by `MAX_RETURNED_PLUGINS`) are returned to avoid excessive payload sizes.
      Caching and efficient queryset usage are employed where possible to ensure fast response times for end users.

    **Example Usage:**

        https://smarter.3141-5926-5359.alpha.api.example.com/config/

    **Returns:**
        JSON response containing:
            - `session_key`: Unique identifier for the chat session.
            - `sandbox_mode`: Boolean indicating if the chatbot is running in sandbox mode.
            - `debug_mode`: Boolean indicating if debug mode is enabled.
            - `chatbot`: Serialized chatbot configuration.
            - `history`: Chat and plugin selector history for the session.
            - `meta_data`: Additional metadata for the chatbot.
            - `plugins`: Plugin metadata and a limited list of plugins.

    **Security:**
        - The view is protected and requires the user to be authenticated, unless the chatbot is configured to allow unauthenticated access.
        - If authentication is required and the user is not authenticated, a 403 Forbidden response is returned.

    **See Also:**
        - `SmarterChatSession`: Helper class for managing chat sessions.
        - `ChatBotConfigSerializer`, `ChatBotPluginSerializer`: Serializers for chatbot and plugin data.
        - `ChatBotHelper`: Helper for chatbot-related operations.
    """

    authentication_classes = None
    permission_classes = (UnauthenticatedPermissionClass,)

    thing: Optional[SmarterJournalThings] = None
    command: Optional[SmarterJournalCliCommands] = None
    session: Optional[SmarterChatSession] = None
    chatbot_name: Optional[str] = None
    _chatbot_helper: Optional[ChatBotHelper] = None
    _chatbot: Optional[ChatBot] = None

    @property
    def chatbot(self) -> Optional[ChatBot]:
        return self._chatbot

    @property
    def chatbot_helper(self) -> Optional[ChatBotHelper]:
        if self._chatbot_helper:
            return self._chatbot_helper
        if self.chatbot:
            # throw everything but the kitchen sink at the ChatBotHelper
            self._chatbot_helper = ChatBotHelper(
                request=self.smarter_request,
                session_key=self.session.session_key if self.session else None,
                name=self._chatbot.name if self._chatbot else self.chatbot_name,
                chatbot_id=self._chatbot.id if self._chatbot else None,  # type: ignore[union-attr]
                account=self.account,
                user=self.user,
                user_profile=self.user_profile,
            )
        else:
            self._chatbot_helper = ChatBotHelper(
                request=self.smarter_request,
                name=self.chatbot_name or self.smarter_request_chatbot_name,
                session_key=self.session.session_key if self.session else None,
                account=self.account,
                user=self.user,
                user_profile=self.user_profile,
            )
        return self._chatbot_helper

    @chatbot_helper.setter
    def chatbot_helper(self, value: Optional[ChatBotHelper]):
        self._chatbot_helper = value
        if self._chatbot_helper and self._chatbot_helper.chatbot:
            self._chatbot = self._chatbot_helper.chatbot
            self.account = self._chatbot_helper.account
            self.user = self._chatbot_helper.user
            self.user_profile = self._chatbot_helper.user_profile
            verbose_logger.debug("%s - chatbot_helper() setter chatbot=%s", self.formatted_class_name, self.chatbot)
        else:
            self._chatbot = None
            verbose_logger.debug("%s - chatbot_helper() setter chatbot is unset", self.formatted_class_name)

    def clean_url(self, url: str) -> str:
        """
        Clean the url of any query strings and trailing '/config/' strings.
        """
        retval = clean_url(url)
        if retval.endswith("/config/"):
            retval = retval[:-8]
        return retval

    def config(self) -> dict[str, Any]:
        """
        Assemble and return the configuration dictionary required by the ReactJS chat UI component.

        This method gathers all relevant context and configuration data for the chat session and chatbot,
        and returns it as a dictionary suitable for JSON serialization. This configuration is consumed by
        the ReactJS frontend to initialize and render the chat interface.

        **Key Features:**

        - **Django Template-Based:**
          This logic is part of a Django class-based view and does not use Django REST Framework (DRF) serializers
          for the main response, though serializers are used for some nested data.

        - **CSRF Exempt:**
          The parent view is CSRF exempt because this endpoint is strictly read-only and does not modify server-side data.

        - **ReactJS UI Integration:**
          The returned dictionary provides all configuration and context information needed by the ReactJS chat component,
          including chatbot metadata, plugin information, session keys, and chat history.

        - **Session-Based:**
          The configuration is tied to a unique chat session, as defined by the :class:`SmarterChatSession` helper,
          which uses a combination of the user's IP address and device-identifying information to uniquely identify
          each session.

        - **Performance:**
          Since this endpoint is called on every browser load and refresh, the logic is optimized to minimize database
          queries and serialization overhead. Only a limited number of plugins (see ``MAX_RETURNED_PLUGINS``) are returned
          to keep payloads small and response times fast.

        Returns
        -------
        dict
            A dictionary containing all configuration data required by the ReactJS chat UI component. The structure includes:

            - ``session_key``: Unique identifier for the chat session.
            - ``sandbox_mode``: Boolean indicating if the chatbot is running in sandbox mode.
            - ``debug_mode``: Boolean indicating if debug mode is enabled.
            - ``chatbot``: Serialized chatbot configuration.
            - ``history``: Chat and plugin selector history for the session.
            - ``meta_data``: Additional metadata for the chatbot.
            - ``plugins``: Plugin metadata and a limited list of plugins.

        Raises
        ------
        SmarterValueError
            If the session or chatbot helper is not set.

        See Also
        --------
        SmarterChatSession : Helper class for managing chat sessions.
        ChatBotConfigSerializer, ChatBotPluginSerializer : Serializers for chatbot and plugin data.
        ChatBotHelper : Helper for chatbot-related operations.
        """
        # add chatbot_request_history and plugin_selector_history to history
        # these have to be added here due to circular import issues.
        if self.session is None:
            logger.error(
                "%s.config() - session is None. Cannot retrieve chatbot request history.", self.formatted_class_name
            )
            return {}
        if self.chatbot_helper is None:
            logger.error(
                "%s.config() - ChatBotHelper is None. Cannot retrieve chatbot request history.",
                self.formatted_class_name,
            )
            return {}

        chatbot_serializer = (
            ChatBotConfigSerializer(self.chatbot, context={"request": self.smarter_request}) if self.chatbot else None
        )

        # plugins context. the main thing we need here is to constrain the number of plugins
        # returned to some reasonable number, since we'll probaably have cases where
        # the chatbot has a lot of plugins (hundreds, thousands...).
        chatbot_plugins_count = ChatBotPlugin.objects.filter(chatbot=self.chatbot).count()
        chatbot_plugins = ChatBotPlugin.objects.filter(chatbot=self.chatbot).order_by("-pk")[:MAX_RETURNED_PLUGINS]
        chatbot_plugin_serializer = ChatBotPluginSerializer(chatbot_plugins, many=True)

        chatbot_functions_count = ChatBotFunctions.objects.filter(chatbot=self.chatbot).count()
        chatbot_functions = ChatBotFunctions.objects.filter(chatbot=self.chatbot).order_by("-pk")[:MAX_RETURNED_PLUGINS]
        chatbot_functions_serializer = ChatBotFunctionsSerializer(chatbot_functions, many=True)

        history = self.session.chat_helper.history if self.session.chat_helper else {}

        chatbot_requests_queryset = ChatBotRequests.objects.filter(session_key=self.session.session_key).order_by("-id")
        chatbot_requests_serializer = ChatBotRequestsSerializer(chatbot_requests_queryset, many=True)
        history["chatbot_request_history"] = chatbot_requests_serializer.data

        plugin_selector_history_queryset = PluginSelectorHistory.objects.filter(session_key=self.session.session_key)
        plugin_selector_history_serializer = PluginSelectorHistorySerializer(
            plugin_selector_history_queryset, many=True
        )
        history["plugin_selector_history"] = plugin_selector_history_serializer.data

        retval = {
            "data": {
                SMARTER_CHAT_SESSION_KEY_NAME: self.session.session_key,
                "sandbox_mode": self.chatbot_helper.is_chatbot_sandbox_url,
                "debug_mode": waffle.switch_is_active(SmarterWaffleSwitches.ENABLE_REACTAPP_DEBUG_MODE),
                "chatbot": chatbot_serializer.data if chatbot_serializer else None,
                "history": history,
                "meta_data": self.chatbot_helper.to_json(),
                "plugins": {
                    "meta_data": {
                        "total_plugins": chatbot_plugins_count,
                        "plugins_returned": len(chatbot_plugins),
                    },
                    "plugins": chatbot_plugin_serializer.data,
                },
                "functions": {
                    "meta_data": {
                        "total_functions": chatbot_functions_count,
                        "functions_returned": len(chatbot_functions),
                    },
                    "functions": chatbot_functions_serializer.data,
                },
            },
        }
        chat_config_invoked.send(sender=self.__class__, instance=self, request=self.smarter_request, data=retval)
        return retval

    def dispatch(
        self, request: HttpRequest, *args, **kwargs
    ) -> Union[JsonResponse, HttpResponse, SmarterJournaledJsonErrorResponse]:
        """
        Handles incoming HTTP requests for the chat configuration endpoint.

        This method is responsible for orchestrating the retrieval and assembly of all configuration data
        required by the ReactJS chat UI component. It is invoked on every user-facing browser load and refresh,
        making performance a critical concern.

        **Key Details:**

        - **Django Template-Based:**
          This view uses Django's class-based view and template system, not Django REST Framework (DRF).
          The response is a JSON object, but the view logic is not DRF-based.

        - **CSRF Exempt:**
          The view is decorated with ``@csrf_exempt`` because it is strictly read-only and does not modify server-side data.
          This avoids unnecessary CSRF validation for GET and POST requests that only retrieve configuration data.

        - **ReactJS UI Integration:**
          The endpoint provides all configuration and context information needed by the ReactJS chat component,
          including chatbot metadata, plugin information, session keys, and chat history.

        - **Session-Based:**
          Sessions are managed by the :class:`SmarterChatSession` helper, which uniquely defines a chat session
          using a combination of the user's IP address and device-identifying information. This ensures each device/browser
          instance receives a unique session key, which is used to track chat history and plugin usage.

        - **Performance:**
          Since this endpoint is called on every browser load and refresh, it is optimized to minimize database queries
          and serialization overhead. Only a limited number of plugins are returned (see ``MAX_RETURNED_PLUGINS``)
          to keep payloads small and response times fast.

        Parameters
        ----------
        request : HttpRequest
            The incoming HTTP request object.
        chatbot_id : Optional[int], default=None
            The ID of the chatbot to retrieve configuration for, if specified.
        *args
            Additional positional arguments.
        **kwargs
            Additional keyword arguments.

        Returns
        -------
        Union[JsonResponse, HttpResponse, SmarterJournaledJsonErrorResponse]
            A JSON response containing all configuration data required by the ReactJS chat UI component,
            or an error response if the request is invalid or unauthorized.

        See Also
        --------
        SmarterChatSession : Helper class for managing chat sessions.
        ChatBotConfigSerializer, ChatBotPluginSerializer : Serializers for chatbot and plugin data.
        ChatBotHelper : Helper for chatbot-related operations.
        """
        hashed_id = kwargs.pop("hashed_id", None)
        if hashed_id:
            chatbot_id = ChatBot.id_from_hashed_id(hashed_id)
        else:
            chatbot_id = kwargs.pop("chatbot_id", None)

        if chatbot_id is not None:
            try:
                self._chatbot = ChatBot.get_cached_object(pk=chatbot_id)
                self.chatbot_name = self._chatbot.name
                verbose_logger.debug(
                    "%s.dispatch() - set chatbot=%s from chatbot_id=%s",
                    self.formatted_class_name,
                    self._chatbot,
                    chatbot_id,
                )
            except ChatBot.DoesNotExist:
                verbose_logger.error(
                    "%s.dispatch() - ChatBot with id=%s does not exist. Returning 404.",
                    self.formatted_class_name,
                    chatbot_id,
                )
                return JsonResponse({"error": "Not found"}, status=HTTPStatus.NOT_FOUND.value)
        else:
            self.chatbot_name = kwargs.get("name")
            try:
                self._chatbot = get_cached_chatbot_by_request(request=request)
                if not self._chatbot:
                    verbose_logger.debug(
                        "%s.dispatch() - get_cached_chatbot_by_request() returned None. Attempting to instantiate ChatBotHelper with additional info",
                        self.formatted_class_name,
                    )
                    self.chatbot_helper = ChatBotHelper(
                        request=self.smarter_request,
                        session_key=self.session_key,
                        chatbot_id=chatbot_id,
                        name=self.chatbot_name,
                        account=self.account,
                        user=self.user,
                        user_profile=self.user_profile,
                    )
            except ChatBot.DoesNotExist:
                return JsonResponse({"error": "Not found"}, status=HTTPStatus.NOT_FOUND.value)

        # Initialize the chat session for this request. session_key is generated
        # and managed by the /config/ endpoint for the chatbot
        #
        # examples:
        # - https://customer-support.3141-5926-5359.api.example.com/workbench/config/?session_key=123456
        # - http://localhost:9357/api/v1/chatbots/1556/chat/config/?session_key=0733c7b3a33e7eb733c95f6d7fc88d671b6c957e6857a04d05b3f5905167116f
        #
        # The React app calls this endpoint at app initialization to get a
        # json dict that includes, among other pertinent info, this session_key
        # which uniquely identifies the device and the individual chatbot session
        # for the device.
        self.session = SmarterChatSession(request, session_key=self.session_key, chatbot=self.chatbot)

        if (
            self.chatbot_helper
            and self.chatbot_helper.is_authentication_required
            and not is_authenticated_request(request)
        ):
            return SmarterHttpResponseForbidden(
                request,
                "Authentication failed. Are you logged in? Smarter sessions automatically expire after 24 hours.",
            )

        verbose_logger.debug(
            "%s - chatbot=%s - chatbot_helper=%s", self.formatted_class_name, self.chatbot, self.chatbot_helper
        )

        if not self.chatbot:
            return JsonResponse({"error": "Not found"}, status=HTTPStatus.NOT_FOUND.value)

        self.thing = SmarterJournalThings(SmarterJournalThings.CHAT_CONFIG)
        self.command = SmarterJournalCliCommands(SmarterJournalCliCommands.CHAT_CONFIG)

        verbose_logger.debug(
            "%s.dispatch() completed with chatbot=%s, session_key=%s",
            self.formatted_class_name,
            self.chatbot,
            self.session.session_key if self.session else "(Missing session)",
        )
        return super().dispatch(request, *args, **kwargs)  # type: ignore[return-value]

    def __str__(self):
        return str(self.chatbot) if self.chatbot else "ChatConfigView"

    # pylint: disable=unused-argument
    def post(self, request: HttpRequest, *args, **kwargs) -> SmarterJournaledJsonResponse:
        """
        Get the chatbot configuration.
        """
        logger.debug("%s - post()", self.formatted_class_name)
        data = self.config()
        return SmarterJournaledJsonResponse(request=request, data=data, thing=self.thing, command=self.command)

    # pylint: disable=unused-argument
    def get(self, request: HttpRequest, *args, **kwargs) -> Union[SmarterJournaledJsonResponse, HttpResponseNotAllowed]:
        """
        Get the chatbot configuration.
        """
        logger.warning(
            "%s - get() %s should be invoked via POST instead of GET.", self.formatted_class_name, request.path
        )
        if not waffle.switch_is_active(SmarterWaffleSwitches.ALLOW_API_GET):

            logger.error(
                "%s.get() %s is not allowed because %s switch is inactive.",
                self.formatted_class_name,
                request.path,
                SmarterWaffleSwitches.ALLOW_API_GET,
            )
            return HttpResponseNotAllowed(permitted_methods=[SmarterHttpMethods.POST])
        data = self.config()
        return SmarterJournaledJsonResponse(request=request, data=data, thing=self.thing, command=self.command)
