# Generated by Django 5.2.5 on 2025-09-05 17:28
# pylint: disable=missing-module-docstring,missing-function-docstring,missing-class-docstring

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("provider", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="providermodel",
            old_name="max_tokens",
            new_name="max_completion_tokens",
        ),
    ]
