# Generated by Django 5.1.7 on 2025-06-27 16:31
# pylint: disable=missing-module-docstring,missing-function-docstring,missing-class-docstring

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "account",
            "0011_user_alter_charge_user_alter_dailybillingrecord_user_and_more",
        ),
        ("provider", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provider",
            name="owner",
            field=models.ForeignKey(
                help_text="The users that owns the provider.",
                on_delete=django.db.models.deletion.CASCADE,
                to="account.user",
            ),
        ),
        migrations.AlterField(
            model_name="provider",
            name="tos_accepted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who accepted the terms of service.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tos_accepted_by",
                to="account.user",
            ),
        ),
    ]
