# pylint: disable=all
# Generated by Django 6.0.4 on 2026-04-23 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
        ("provider", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="provider",
            name="user_profile",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="account.userprofile"),
        ),
    ]
