# Generated by Django 6.0.8 on 2026-10-04 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("provider", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="providerverification",
            name="verification_type",
            field=models.CharField(
                choices=[
                    ("api_connectivity", "Api Connectivity"),
                    ("logo", "Logo"),
                    ("contact_email", "Contact Email"),
                    ("support_email", "Support Email"),
                    ("website_url", "Website URL"),
                    ("tos_url", "Terms of Service URL"),
                    ("docs_url", "Documentation URL"),
                    ("privacy_policy_url", "Privacy Policy URL"),
                    ("tos_acceptance", "Terms of Service Acceptance"),
                    ("production_api_key", "Production API Key"),
                ],
                default="api_connectivity",
                max_length=32,
            ),
        ),
    ]
