# pylint: disable=missing-module-docstring,missing-function-docstring,missing-class-docstring
# Generated by Django 5.2.6 on 2025-09-19 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("provider", "0002_rename_max_tokens_providermodel_max_completion_tokens"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provider",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="The logo of the provider.",
                null=True,
                upload_to="provider/provider_logos/",
            ),
        ),
    ]
