# pylint: disable=all
# Generated by Django 6.0.4 on 2026-04-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("provider", "0003_provider_is_default_alter_provider_user_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="default_model",
            field=models.CharField(
                blank=True,
                help_text="The default model to use for the provider.",
                max_length=255,
                null=True,
            ),
        ),
    ]
