# pylint: disable=missing-module-docstring,missing-function-docstring,missing-class-docstring
# Generated by Django 5.2.7 on 2025-12-27 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0013_userprofile_annotations_userprofile_description_and_more"),
        (
            "provider",
            "0004_provider_annotations_provider_tags_provider_version_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="provider",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="account.account",
            ),
        ),
    ]
