# pylint: disable=missing-module-docstring,missing-function-docstring,missing-class-docstring
# Generated by Django 5.2.7 on 2025-12-29 21:42

from django.db import migrations, models

import smarter.lib.django.model_helpers
import smarter.lib.django.validators


class Migration(migrations.Migration):

    dependencies = [
        ("provider", "0005_alter_provider_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provider",
            name="name",
            field=models.CharField(
                help_text="Name in camelCase, e.g., 'apiKey', no special characters.",
                max_length=255,
                validators=[
                    smarter.lib.django.validators.SmarterValidator.validate_snake_case,
                    smarter.lib.django.model_helpers.validate_no_spaces,
                ],
            ),
        ),
    ]
