# pylint: disable=missing-module-docstring,missing-function-docstring,missing-class-docstring
# Generated by Django 5.2.7 on 2026-01-09 07:34

from django.db import migrations, models

import smarter.lib.json


class Migration(migrations.Migration):

    dependencies = [
        ("provider", "0006_alter_provider_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provider",
            name="annotations",
            field=models.JSONField(
                blank=True,
                default=list,
                encoder=smarter.lib.json.SmarterJSONEncoder,
                help_text="Key-value pairs for annotating this resource.",
            ),
        ),
    ]
